### ISSUE TITLE
@ItzCrazyKns Can you help having the correct configurations that must be adapted everywhere universally?

### ISSUE THREAD

**Issue by arunkumarakvr** [ItzCrazyKns/Perplexica#10]
@ItzCrazyKns Is this Perplexica repo already production ready? If not, when will it become production ready?

![Screenshot_20240418_155627_Chrome.png](https://github.com/ItzCrazyKns/Perplexica/assets/146523874/cfbdb673-98b7-4230-8101-04eefc589c92)

This is not working on GitHub CodeSpace. Why? Anyways to restart the containers or to check if env var setup working properly?

_Originally posted by @arunkumarakvr in https://github.com/ItzCrazyKns/Perplexica/issues/8#issuecomment-2063486742_

**Comment by ItzCrazyKns** [comment]
It might be because the websocket connection couldn't be established due to configuration reasons. Please update those in the Docker compose file before rebuilding the images. And yes, Perpexica is under heavy development so I won't recommend it for production yet but lets see in the future

**Comment by ItzCrazyKns** [comment]
Hello, could you please respond to this issue within the next 24 hours? If I don't hear back from you by then, I'll assume that everything is resolved and will mark it as completed and closed.

**Comment by ItzCrazyKns** [comment]
I've set up a Discord server to improve communication and provide support more effectively. It will be easier to share files, message, and address your issues. You can join the server here: https://discord.gg/HUDjfQvM.

**Comment by ItzCrazyKns** [comment]
> > > This is not working on GitHub CodeSpace. Why? Anyways to..
> > 
> > 
> > Github codespaces aren't meant to run things on production so we'll not talk it about here but all I can say about it is that the frontend is not being able to connect to the websocket as the environment variable passed by Docker is meant for local uses. To deploy it you can make use of Docker but you would have to change the environment variables in the docker compose file, specially the backend API URL and the websocket address (you need to change the IP to the IP of the server you are using to deploy it). I believe if you are deploying it somewhere to use it with multiple devices you must have even a little knowledge about Docker then you'll be able to do it with ease.
> 
> Please help with the right IP address that must be used in the docker-compose file. Is it 0.0.0.0:3001 or 'external ip of server like vm':3001 or any docker internal domain cited in the ollama feat issues that must be changed or should I change such an IP wherever localhost or 127.0.0.1 across this entire Perplexica repo?

If you are using the old `feat/ollama` branch kindly update to the latest version of the `master` branch as it contains the latest code supporting local models. Before we make it run on the network we need to make sure it runs locally on the computer. As I said in the other issue, please update the Ollama URL to `http://host.docker.internal:11434`. This should fix the issue for no output from the model. Afterwards you can change the IP to the private IP of the computer where it is hosted and it should work completely fine.

**Comment by gscfwid** [comment]
> I've set up a Discord server to improve communication and provide support more effectively. It will be easier to share files, message, and address your issues. You can join the server here: https://discord.gg/HUDjfQvM.

The discord link is not available now, @ItzCrazyKns could you please update it?

**Comment by ItzCrazyKns** [comment]
> > I've set up a Discord server to improve communication and provide support more effectively. It will be easier to share files, message, and address your issues. You can join the server here: https://discord.gg/HUDjfQvM.
> 
> The discord link is not available now, @ItzCrazyKns could you please update it?

https://discord.gg/jFc3nnF3

**Comment by ItzCrazyKns** [comment]
Documentation for this has been added https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md
