### ISSUE TITLE
Help fix the bugs adding the LLM API providers config details right on the UI instead of or in addition to .toml or .env

### ISSUE THREAD

**Issue by arunkumarakvr** [ItzCrazyKns/Perplexica#106]
**Describe the bug**

**Help fix the bugs adding the LLM API providers config details right on the UI say under Settings instead of or in addition to .toml or .env and make it work seamlessly**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ItzCrazyKns** [comment]
Please provide more context

**Comment by ItzCrazyKns** [comment]
Please open only 1 issue https://github.com/ItzCrazyKns/Perplexica/issues/107, we can continue there
