### ISSUE TITLE
None of these LLM APIs providers for ollama LLMs or Azure OpenAI LLMs or embeddings models or any other LLMs don't work at all despite those changes.

### ISSUE THREAD

**Issue by arunkumarakvr** [ItzCrazyKns/Perplexica#107]
@ItzCrazyKns none of these LLM APIs providers for ollama LLMs or Azure OpenAI LLMs or embeddings models or any other LLMs don't work at all despite those changes per your docs cited there.

_Originally posted by @arunkumarakvr in https://github.com/ItzCrazyKns/Perplexica/issues/10#issuecomment-2105953814_

**Comment by ItzCrazyKns** [comment]
More context..

**Comment by ItzCrazyKns** [comment]
What error are you facing? How are you configuring it? share some logs, screen shots or something?

**Comment by xbl916** [comment]
你是想要通过本地兼容openai api方式运行嘛
