### ISSUE TITLE
The Discover and Library pages are showing a 404 error

### ISSUE THREAD

**Issue by llmadd** [ItzCrazyKns/Perplexica#114]
I deployed the latest version using Docker.

config setting:
[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

[API_KEYS]
OPENAI = "my_openai_key"
GROQ = "my_groq_key"

[API_ENDPOINTS]
SEARXNG = "http://localhost:32768" # SearxNG API URL
OLLAMA = "" # Ollama API URL - http://host.docker.internal:11434

The Discover and Library pages are showing a 404 error, and the Library navigation button is not triggering the click effect.
Please help me, thank you！
<img width="1445" alt="image" src="https://github.com/developersdigest/llm-answer-engine/assets/38323944/f0514228-3272-48b6-be24-b75175a89422">

<img width="1445" alt="image" src="https://github.com/developersdigest/llm-answer-engine/assets/38323944/1651356b-77b3-45a3-8e87-99e5df9573f8">

**Comment by llmadd** [comment]
The issue has been resolved by adding the corresponding content under the `ui/app/` path.

**Comment by hekmon** [comment]
I have the same issue, what do you mean by "the corresponding content" ?

**Comment by llmadd** [comment]
> I have the same issue, what do you mean by "the corresponding content" ?我有同样的问题，您所说的“相应内容”是什么意思？

"Create a 404 folder and page.tsx file in the frontend."
"This is for when a route is not found, it's part of Next.js knowledge."
