### ISSUE TITLE
cannot change the Chat model Provider to ollama

### ISSUE THREAD

**Issue by adithyaric** [ItzCrazyKns/Perplexica#117]
**I want to change the Chat model Provider to my ollama on wsl but its not automatically changed**

i have tried this

> OLLAMA: Your Ollama API URL. You should enter it as http://host.docker.internal:PORT_NUMBER. If you installed Ollama on port 11434, use http://host.docker.internal:11434. For other ports, adjust accordingly. You need to fill this if you wish to use Ollama's models instead of OpenAI's.

and this https://github.com/ItzCrazyKns/Perplexica/?tab=readme-ov-file#ollama-connection-errors
but result are same. my ollama run at _http://localhost:11434_

**Screenshot**
![image](https://github.com/ItzCrazyKns/Perplexica/assets/69343456/f732007c-2b2a-4ca9-8329-e57ab46cb273)
![image](https://github.com/ItzCrazyKns/Perplexica/assets/69343456/f337f560-99e4-404d-8970-31dd73177c6d)
![image](https://github.com/ItzCrazyKns/Perplexica/assets/69343456/d55efb46-a06f-4b19-929c-ee30c67990d9)

**Comment by ItzCrazyKns** [comment]
Seems like its not able to connect to Ollama. Why are you using localhost:11434 instead of host.docker.internal:11434 or private_ip:11434?

**Comment by adithyaric** [comment]
> Seems like its not able to connect to Ollama. Why are you using localhost:11434 instead of host.docker.internal:11434 or private_ip:11434?

My Ollama server is running at localhost:11434, and I also tried hosting it at host.docker.internal:11434, but it seems like it's not working.

**Comment by TomWest61** [comment]
i have the same proble under win 11: I renamed sample.config.toml to config.toml  then: "docker compose up -d"
and start at: http://localhost:3000/. Message: "internal server error" and no models are shown.
(ollama is runnung. docker is running. Testet with "ollama list" and  "docker --version")

**Comment by DriKel** [comment]
your error is not about ollama or backend, but searxng not being able run checks by connecting to soundcloud, find it lines (soundcloud) in ./searxng/settings.yml and remove

**Comment by IAmStoxe** [comment]
I'm having a similar issue unrelated to soundcloud.

I have removed the network specification even from the docker-compose. Other docker containers connect without issue to the Ollama instance. 

I am not seeing any errors when tailing the logs of the searchnx and background services.
---

Opened PR #137 that seemingly fixes this.

**Comment by Pioshin** [comment]
> **I want to change the Chat model Provider to my ollama on wsl but its not automatically changed**
> 
> i have tried this
> 
> > OLLAMA: Your Ollama API URL. You should enter it as http://host.docker.internal:PORT_NUMBER. If you installed Ollama on port 11434, use http://host.docker.internal:11434. For other ports, adjust accordingly. You need to fill this if you wish to use Ollama's models instead of OpenAI's.
> 
> and this https://github.com/ItzCrazyKns/Perplexica/?tab=readme-ov-file#ollama-connection-errors but result are same. my ollama run at _http://localhost:11434_
> 
> **Screenshot** ![image](https://private-user-images.githubusercontent.com/69343456/331542726-f732007c-2b2a-4ca9-8329-e57ab46cb273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTEwMzUsIm5iZiI6MTczMjA5MDczNSwicGF0aCI6Ii82OTM0MzQ1Ni8zMzE1NDI3MjYtZjczMjAwN2MtMmIyYS00Y2E5LTgzMjktZTU3YWI0NmNiMjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA4MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZmQ1YTdkM2IzYTE4YTZmNTQ1MTU2Y2EzOGNkZWUzYTc2ZTQ5NzRiNjQyMTBkYmY5YzU1NGY4OWJlNmU5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B3rQHgj2NiukiGPLZ2ihuIEnBlPkiYcoFZDLNbrirh0) ![image](https://private-user-images.githubusercontent.com/69343456/331544948-f337f560-99e4-404d-8970-31dd73177c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTEwMzUsIm5iZiI6MTczMjA5MDczNSwicGF0aCI6Ii82OTM0MzQ1Ni8zMzE1NDQ5NDgtZjMzN2Y1NjAtOTllNC00MDRkLTg5NzAtMzFkZDczMTc3YzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA4MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMmMzODlmYzUzOWEwMjkyNjYzYmFlNTgwMDJlNDJhZmVmNjFkMDZiMTNlYWMwODVlZGFmNWVmYmRhY2M0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XxmWl1KrymdsLIQ32YQ9INEjJWOP9pFhYvjWG_UKMZs) ![image](https://private-user-images.githubusercontent.com/69343456/331544361-d55efb46-a06f-4b19-929c-ee30c67990d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTEwMzUsIm5iZiI6MTczMjA5MDczNSwicGF0aCI6Ii82OTM0MzQ1Ni8zMzE1NDQzNjEtZDU1ZWZiNDYtYTA2Zi00YjE5LTkyOWMtZWUzMGM2Nzk5MGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA4MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NTI3ZWE5NGM4NmIxODc2YWVjNTJkZjBkNDBlODBjNDIyZDViMjJjZmJiYTQwMTUyMjc4NmVmMGM1OWZhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o_dRC5tQTJFpgnYIKDbTWMiyyhlX0n2SkQpjVFgkMik)

I ended up with the same issue.... any solution? Workaround? I've tryed inside and outside docker, same issue.
May it be a problem with TCP ports? I have Openwebui running on localhost:8080 and i think searxng is trying to use it.

**Comment by Pioshin** [comment]
Uh and, sorry, i forgot to mention this uncomprehensible behavior of the UI settings, where you cannot change chat model provider to anything else but OpenAI... i do not use it, i use ollama!
