### ISSUE TITLE
How to update gracefully?

### ISSUE THREAD

**Issue by wwjCMP** [ItzCrazyKns/Perplexica#123]
I deploy using docker compose

**Comment by ItzCrazyKns** [comment]
Just do git pull and re-build the images.

**Comment by rqi14** [comment]
create this script and put it at somewhere like /path/to/your/script/update_g4f.sh
```
#!/bin/bash
cd /path/to/your/gpt4free
docker compose pull
docker compose stop 
docker compose up -d
```

`docker compose stop` may not be necessary. you can try. Without the stop command, it should simply recreate the container if there is a newer version.

then call `sudo crontab -e`, and add a line `0 5 * * * /path/to/your/script/update_g4f.sh`

It automatically updates g4f at 5am every day if there is a newer version
