### ISSUE TITLE
Copy function doesn't works

### ISSUE THREAD

**Issue by delfireinoso** [ItzCrazyKns/Perplexica#127]
**Describe the bug**
at the end of the search, the COPY icon don't change to OK on triing to copy and the content it's not copied

**To Reproduce**

1. Go to '.Ask anything' and wait a reply..
2. Click on 'Copy Icon.'
3. See error: nothing changes, content is not copied

**Expected behavior**
the icon should change to OK icon.

Perpelxica is the best when this works

**Additional context**
tried on a Mac latest revision, Safari and Firefox.  Perpelxica last built as 21/05/24

**Comment by ItzCrazyKns** [comment]
Are their any errors in the console while pressing the copy button?

**Comment by delfireinoso** [comment]
This problem didn't appear after a new install

Now it's working fine on a computer (not in an IPad or iPhone but this is another thing, not a bug)

Close the bug
