### ISSUE TITLE
LLM does not receive the resources generated by the search engine.

### ISSUE THREAD

**Issue by Reno0vacio** [ItzCrazyKns/Perplexica#129]
**Describe the bug**
I run a search through Ollama with the model "gemmini:2b" and searched the application, but it says LLM in the response:
"It does not have access to the resources and so cannot provide an answer."
(I have also tried with LLama 3-model)
With Docker.

**Screenshots**
![Képernyőkép 2024-05-23 192405](https://github.com/ItzCrazyKns/Perplexica/assets/57655249/8979d007-e1fa-41d9-b20b-bf50b7c7b4fc)

**Comment by jagranata** [comment]
Hey, any idea what the issue was here?
