### ISSUE TITLE
Azure OpenAI Endpoint Support

### ISSUE THREAD

**Issue by rcarmo** [ItzCrazyKns/Perplexica#131]
**Is your feature request related to a problem? Please describe.**
I use Azure OpenAI service for my LLMs. I do not want to pay for an additional OpenAI service.

**Describe the solution you'd like**
Support for using an Azure OpenAI endpoint instead of the OpenAI one. 

**Describe alternatives you've considered**
Using litellm, like in Open Web UI (which bundles the litellm proxy within the Docker container)

**Additional context**
N/A

**Comment by ItzCrazyKns** [comment]
It can be done via the custom OpenAI provider in the settings menu. You just need to add the API URL (supporting OpenAI's format) and it would work completely fine

**Comment by conormcneill** [comment]
@rcarmo
