### ISSUE TITLE
Default copilot mode

### ISSUE THREAD

**Issue by aakast** [ItzCrazyKns/Perplexica#133]
I just want to be able to make the copilot mode default, as it will always take an extra step as of now.

**Comment by ItzCrazyKns** [comment]
Co-pilot mode isn't ready yet, its still in development and the toggle in the UI does nothing for now. So I believe we can reopen this issue when the co-pilot feature has been implemented in the application. Thanks!

**Comment by datascience279** [comment]
@ItzCrazyKns the app is working super amazing! Eagerly waiting for the co-pilot feature. when can we expect it?

 Will it contain agentic workflows?

**Comment by seetimee** [comment]
same question
