### ISSUE TITLE
LM Studio Support 

### ISSUE THREAD

**Issue by mrdjohnson** [ItzCrazyKns/Perplexica#134]
For local inference LM Studio allows easy access to a lot of hugging face models, it would be awesome if this could support LM Studio as well; it does have open ai compatibility but actual first party support would be amazing!

**Comment by ItzCrazyKns** [comment]
Hi mate! I understand your issue and would love to add it but maintaining a lot of providers is sort of an issue. We would need fetch the models from their API then add it again in the providers, I myself think OpenAI support is good enough to be able to use it but if the community demands I'd love to add it.

**Comment by bhupesh-sf** [comment]
I think this is possible very easily. LM studio and many others give openAI compatible API. So you just need to expose openai_base_url and model_name to env vars and everything will work automatically. I am already using it for many other projects.

**Comment by HolyMolyCowMan** [comment]
+1, it does just mimic the openAI api

**Comment by NikMAX2077** [comment]
+1

**Comment by Ratione** [comment]
Bump. I already have a working LM Studio setup. I have no intention of going *back* to ollama
