### ISSUE TITLE
WebSocket Connection Failure in DevTools Console

### ISSUE THREAD

**Issue by arunkumarakvr** [ItzCrazyKns/Perplexica#14]
**Title**: WebSocket Connection Failure in DevTools Console

**Body**:

### Issue Description
When attempting to establish a WebSocket connection, the DevTools console displays the following error message:
```
page-c1977eaac74b29da.js:1 WebSocket connection to 'ws://127.0.0.1:3001/' failed:
```

### Steps to Reproduce
1. Open the DevTools console in the browser.
2. Attempt to connect to the WebSocket server at `ws://127.0.0.1:3001/`.
3. Observe the error message.

### Expected Behavior
The WebSocket connection should be established successfully without any errors.

### Actual Behavior
The connection fails, and the DevTools console logs an error message indicating the failure.

### Possible Solutions
- Check if the WebSocket server is running and listening on the correct port.
- Ensure there are no network issues or firewalls blocking the connection.
- Verify the WebSocket server configuration for any potential issues.

### Additional Context
Please provide any additional information that might be helpful in resolving this issue, such as server logs, network configuration, or browser version.

**Comment by ItzCrazyKns** [comment]
Hi, I understand the problem and I would recommend you to follow the solutions you shared. Make sure the API server is accessible from the browser at http://127.0.0.1:3001. If not please check the configuration, firewall errors or network issues

**Comment by ItzCrazyKns** [comment]
> @ItzCrazyKns It seems that the WebSocket server is not defined in any provided Dockerfiles or the docker-compose.yaml file. So then how do I start or initiate and handle the WebSocket server here? Due to this, Am I getting the different console errors like `page-2abbb79b5568719c.js:1 WebSocket is already in CLOSING or CLOSED state`? Help fix these WebSocket problems.

The WebSocket part is handled by the server. It is defined at `src/websocket/index.ts`

**Comment by noah003** [comment]
> Change your Ollama URL to `http://host.docker.internal:11434`, Ollama should work fine then.

doesn't work for me

**Comment by ItzCrazyKns** [comment]
> > Change your Ollama URL to `http://host.docker.internal:11434`, Ollama should work fine then.
> 
> doesn't work for me

Could you please provide more information?

**Comment by Swiftyos** [comment]
I'm trying to run this on a MacBook, using openai as the provider. 

I keep getting `connection closed` in the logs with no other error message. 
When entering a search the ui changes to the search result page, but nothing else happens. 

No messages in the logs and I can't find anywhere were there is a record of a request being sent to the backend

**Comment by Swiftyos** [comment]
> I'm trying to run this on a MacBook, using openai as the provider.
> 
> I keep getting `connection closed` in the logs with no other error message. When entering a search the ui changes to the search result page, but nothing else happens.
> 
> No messages in the logs and I can't find anywhere were there is a record of a request being sent to the backend

My issue was due to having another service using port 8080 so the SEARXNG server could not bind to the port. 

We need more logging messages to make it easer to debug though @ItzCrazyKns

**Comment by Shiyinq** [comment]
same problem

<img width="1440" alt="image" src="https://github.com/ItzCrazyKns/Perplexica/assets/25049562/9b248540-288b-40c5-97d0-9edf98b0847f">


my config
<img width="859" alt="image" src="https://github.com/ItzCrazyKns/Perplexica/assets/25049562/548006cb-be4a-44b8-a89f-ad72e2f633d0">


docker compose
<img width="693" alt="image" src="https://github.com/ItzCrazyKns/Perplexica/assets/25049562/9e4def41-08b8-4a20-9e2d-106e2dbff714">


api
<img width="406" alt="image" src="https://github.com/ItzCrazyKns/Perplexica/assets/25049562/d4e1181e-01e7-4a02-8af2-b1c393df4cf5">

**Comment by ItzCrazyKns** [comment]
Hi @arunkumarakvr is this issue resolved or your still need support? If you don't respond within the next 24 hours we'll close this issue as completed.
