### ISSUE TITLE
But report: the related question does no match to the querry language.

### ISSUE THREAD

**Issue by getofferhelp** [ItzCrazyKns/Perplexica#143]
**Describe the bug**
The answer corresponsed to the querry language, like Chinese and Japanese, but the related question is still in English

**To Reproduce**
Ask a question in Chinese, like "亚马逊河流在亚洲吗", which means Is Amazon river in Asia?.

Then the related questions would be in En

**Expected behavior**
Would you like to modify the prompt?

**Screenshots**

<img width="545" alt="3" src="https://github.com/ItzCrazyKns/Perplexica/assets/13744916/020d3e03-08a0-4371-8a2a-db822dcc7759">

**Comment by ItzCrazyKns** [comment]
What model are you using?

**Comment by getofferhelp** [comment]
> What model are you using?

GROQ,

I would try openai later.

**Comment by getofferhelp** [comment]
> What model are you using?

GPT3.5turbo  and GROQ are both like this

<img width="554" alt="4" src="https://github.com/ItzCrazyKns/Perplexica/assets/13744916/3872775b-7c8d-40ed-845b-8eef6795649b">

**Comment by getofferhelp** [comment]
> What model are you using?

UPDATE: OPENAI(3.5) work well in, maybe 80%, in most cases.  GROQ is not ok in most cases.

**Comment by miladhatami1393** [comment]
GROQ

**Comment by ItzCrazyKns** [comment]
OpenAI's models (GPT4 and GPT4o) would give responses most of the time in the language the question is asked. Open source models are still reaching the level of closed sourced models but they're still a little dumb so this will be fixed in the future as we get to see more models.
