### ISSUE TITLE
Feature Request - Multi-Model Service Provider Support

### ISSUE THREAD

**Issue by arunkumarakvr** [ItzCrazyKns/Perplexica#15]
GitHub Issue: Feature Request - Multi-Model Service Provider Support

**Is your feature request related to a problem? Please describe.**
The current limitation of supporting only a single model service provider in Perplexica restricts users' options and may not fully meet their diverse needs for AI conversation services.

**Describe the solution you'd like**
Implement support for multiple model service providers in Perplexica to offer users a wider range of choices and enhance the platform's adaptability to various user preferences and requirements.

**Describe alternatives you've considered**
One alternative is to stick with a single model service provider, but this may restrict users' options and limit the platform's flexibility. Another alternative is to develop custom integrations for specific model service providers, but this could be time-consuming and resource-intensive.

**Additional context**
Expanding support to additional model service providers, such as Azure OpenAI, AWS Bedrock, Anthropic (Claude), Google Cloud Vertex AI, Google AI Studio, Groq, OpenRouter, and Together.ai, would further enrich Perplexica's service provider library. Additionally, we are requesting support for more providers like Replicate and Perplexity. Community feedback and discussions are encouraged to prioritize support for additional service providers based on user preferences and requirements.

**Comment by ItzCrazyKns** [comment]
Thanks for the feature request. We're expanding model support, recently adding Ollama, and are exploring more providers like Azure and AWS to better meet user needs.

**Comment by denispol** [comment]
Great software, thank you for making it! Maybe leveraging [openrouter.ai](url) for instance over other service would be a huge win, as it allows access to almost all models available through API's

**Comment by ItzCrazyKns** [comment]
Support for Groq and Ollama has been added, additional support for custom OpenAI endpoints has been added that would allow most of the LLM providers.

**Comment by RazeBerry** [comment]
@ItzCrazyKns Was wondering if there is a plan to add Anthropic's models' support considering they are SOTA? Thanks!

**Comment by willieseabrook** [comment]
For people needing a solution to the small number of providers supported, set up an litellm container. That's what I did.

Then in perplexica config.toml

[MODELS.CUSTOM_OPENAI]
API_KEY = "your key"
API_URL = "http://litellm:4000" (your litellm container)
MODEL_NAME = "the model you set up in litellm"

That way you can use any model litellm supports
