### ISSUE TITLE
Make the WebGUI remotely accessible

### ISSUE THREAD

**Issue by baarsnet** [ItzCrazyKns/Perplexica#154]
**Is your feature request related to a problem? Please describe.**
When i try to load the page it just 'keeps loading'  (like in issue:  "eternal loading #101")

![screenshot](https://github.com/ItzCrazyKns/Perplexica/assets/97163760/43fed07f-5175-4771-8fd1-412f10575fd3)

**Describe the solution you'd like**
I just want the page to load when i remotely access it (or with a reverse proxy), so i can access it from multiple locations.

**Describe alternatives you've considered**
I've tried to run it with a reverse proxy on the same machine as where perplexica is running, but i get the same result.

**Additional context**

**Comment by ItzCrazyKns** [comment]
Hi, please see [this](https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md#expose-perplexica-to-a-network). Since we don't already have your private IP address we've left it for the user to do it themselves.

**Comment by baarsnet** [comment]
Ah [this](https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md#expose-perplexica-to-a-network) works!  \o/
But only if i access it directly on http://<server_ip>:3000 .
When i use a reverse proxy it still keeps loading.

I hope this can be fixed in the future... but for now i'm happy it works :)

Thank you.

**Comment by goalkeepr** [comment]
Following...

**Comment by muhammadammarzahid** [comment]
Same issue. Works on local network but i am unable to set it up behind the reverse proxy manger.

**Comment by gitwittidbit** [comment]
Same here

**Comment by lightshark85** [comment]
Same here
