### ISSUE TITLE
Error after running docker compose. It cannot complete the installation

### ISSUE THREAD

**Issue by VirtualZardoz** [ItzCrazyKns/Perplexica#159]
**Describe the bug**
I get an error message in step 5/5  
=> ERROR [perplexica-frontend 5/5] RUN yarn build 

**To Reproduce**

run the command: docker compose up -d

**Expected behavior**
![Screenshot 2024-06-02 113005](https://github.com/ItzCrazyKns/Perplexica/assets/167669409/68280c28-d429-42fa-878f-8e2159a5c026)

=> ERROR [perplexica-frontend 5/5] RUN yarn build                                                                                                                                                                 20.6s 
------
 > [perplexica-frontend 5/5] RUN yarn build:
0.507 yarn run v1.22.19
0.525 $ next build
1.011 Attention: Next.js now collects completely anonymous telemetry regarding usage.
1.012 This information is used to shape Next.js' roadmap and prioritize features.
1.012 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
1.012 https://nextjs.org/telemetry
1.012
1.096    ▲ Next.js 14.1.4
1.096
1.153    Creating an optimized production build ...
2.602 (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2.602 (Use `node --trace-deprecation ...` to show where the warning was created)
10.99 (node:139) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
10.99 (Use `node --trace-warnings ...` to show where the warning was created)
11.33 (node:139) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
17.12  ✓ Compiled successfully
17.12    Linting and checking validity of types ...
20.43 Failed to compile.
20.43
20.43 ./components/EmptyChat.tsx:15:22
20.43 Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
20.43   Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.
20.43
20.43   13 |   return (
20.43   14 |     <div className="relative">
20.43 > 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
20.43      |                      ^
20.43   16 |
20.43   17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
20.43   18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
20.47 error Command failed with exit code 1.
20.47 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

**Screenshots**

**Additional context**

**Comment by bigsk1** [comment]
passing a prop called size to this component, which is not defined in its props type

add to themes/switcher.tsx 

const ThemeSwitcher = ({ className, size }: { className?: string; size?: number }) => {...}

Fixed

**Comment by cog-data** [comment]
+1

**Comment by cog-data** [comment]
Same bug. The fix is working fine, thanks!

**Comment by VirtualZardoz** [comment]
> passing a prop called size to this component, which is not defined in its props type
> 
> modify in theme/switcher.tsx to read
> 
> const ThemeSwitcher = ({ className, size }: { className?: string; size?: number }) => {
> 
> Fixed

This worked. Thanks a lot !

**Comment by ProjectMoon** [comment]
This should probably be added as a PR right?
