### ISSUE TITLE
Compile Error in ui fold

### ISSUE THREAD

**Issue by DantesLin** [ItzCrazyKns/Perplexica#165]
my env is :
npm -v  :  10.7.0
linux:  archlinux

when I try to run the command in ui fold ,  it return me the follow tips:

[develop@develop ui]$ npm run build

> perplexica-frontend@1.6.0 build
> next build

   ▲ Next.js 14.1.4
   - Environments: .env

   Creating an optimized production build ...

(process:1307104): VIPS-WARNING **: 16:48:58.474: unable to load "/usr/lib/vips-modules-8.15/vips-openslide.so" -- libopenslide.so.1: cannot open shared object file: No such file or directory
(node:1307104) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1307260) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled successfully
   Linting and checking validity of types  ...Failed to compile.

./components/EmptyChat.tsx:15:22
Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
  Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.

  13 |   return (
  14 |     <div className="relative">
> 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
     |                      ^
  16 |
  17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
  18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">

**Comment by DantesLin** [comment]
can't see the code , here is the picture
![Uploading Screenshot_20240603_165843.png…]()

**Comment by WanQuanXie** [comment]
A fix is coming, plz wait

**Comment by bigsk1** [comment]
same as #163 for quick fix

**Comment by ItzCrazyKns** [comment]
Fixed in the latest release
