### ISSUE TITLE
how to install perplexica without using Docker? 

### ISSUE THREAD

**Issue by MisakaGeek** [ItzCrazyKns/Perplexica#17]
I'm confused about the section of Installation in README
Besides configuring the domain within config.toml and .env, what else do I need to do?
how to configure backend and frontend manually?

**Comment by ItzCrazyKns** [comment]
Hi, it's highly recommended to install Perplexica using Docker. If you choose to install it manually, first configure the config and env files. Next, install all dependencies by running `npm i` in both the root and UI directories. Then, execute `npm run build` in both directories. To run Perplexica, use `npm run start` in both the root and UI directories each time. Manual installation is difficult and time-consuming. With Docker, you simply enter a command, and it handles the installation for you.

**Comment by MisakaGeek** [comment]
many thanks!!

**Comment by ItzCrazyKns** [comment]
Should I close this?

**Comment by MisakaGeek** [comment]
maybe hold on, I got another problem when switch to use docker and run "docker compose up -d",  I strictly followed the instructions in the installation section,  here is the log:

 => ERROR [perplexica-backend  9/10] RUN yarn install                                                             92.6s
------
 > [perplexica-backend  9/10] RUN yarn install:
0.466 yarn install v1.22.17
0.508 [1/4] Resolving packages...
0.559 [2/4] Fetching packages...
92.52 error @langchain/openai@0.0.25: The engine "node" is incompatible with this module. Expected version ">=18". Got "17.3.0"
92.52 error Found incompatible module.
92.52 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1

It seems that the nodejs version is incompatible

**Comment by ItzCrazyKns** [comment]
Please update your NodeJS version.

**Comment by MisakaGeek** [comment]
I double check my nodejs with "node --version", and the version is v18.20.0, It should meet the requirements

**Comment by ItzCrazyKns** [comment]
Try `yarn install --ignore-engines`

**Comment by ItzCrazyKns** [comment]
Seems like you tried installing it manually then  installed it using Docker. It could have caused some issues, I would recommend you to clone a fresh version of Perplexica and follow the installation instructions carefully again. I've tried reproducing the issue but it works completely fine for me

**Comment by MisakaGeek** [comment]
okey，i'll try again, thank you very much.

You can close this issue. :)

**Comment by yoohhwz** [comment]
> okey，i'll try again, thank you very much.
>
> You can close this issue. :)

Have you solved it?> okey，i'll try again, thank you very much.
>
> You can close this issue. :)

Did you fix it? I had the same problem.

**Comment by openainext** [comment]
FROM node:20.13.1-buster-slim

**Comment by werthergit** [comment]
Did you fix it? I had the same problem.

**Comment by liyaodev** [comment]
> Seems like you tried installing it manually then installed it using Docker. It could have caused some issues, I would recommend you to clone a fresh version of Perplexica and follow the installation instructions carefully again. I've tried reproducing the issue but it works completely fine for me

I had a similar problem, and deleting the node_modules folder generated by the host's manual installation can solve the problem, thanks again.
