### ISSUE TITLE
Doesn't work with local-hosted Ollama on Linux

### ISSUE THREAD

**Issue by 5a9awneh** [ItzCrazyKns/Perplexica#173]
**Describe the bug**
Interface slow to load, when it does, I receive `Invalid connection` message, in settings (also slow to load) it doesn't detect installed Ollama models

**To Reproduce**

1. Install Ollama locally (not as docker)
2. Tried different Ollama APIs in `config.toml`:
  `http://host.docker.internal:11434`
  `http://localhost:11434`
  `http://private_ip_of_computer_hosting_ollama:11434`
3. Install Perplexica via `docker compose up -d`
4. Browse to `http://localhost:3000` to See error
5. Open Settings, doesn't detect neither Ollama nor Ollama models

**Expected behavior**
It should be able to connect to Ollama and detect installed models

**Additional context**
- System: Linux Mint
- Ollama (Local) is already working fine in both Terminal & Open WebUI (docker)

**Comment by ItzCrazyKns** [comment]
You need to expose Ollama to your network and then use the private IP of the computer + port as the API URL. Feel free to re-open this issue or join our Discord server if you face any issues after performing the steps
