### ISSUE TITLE
ui installation bug/issue    running npm run build

### ISSUE THREAD

**Issue by issa2k23** [ItzCrazyKns/Perplexica#174]
**De(Perplexica) issa@23Lap:~/perplexica/Perplexica/ui$ npm run build

> perplexica-frontend@1.6.0 build
> next build

   ▲ Next.js 14.1.4
   - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types  ...Failed to compile.

./components/EmptyChat.tsx:15:22
Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
  Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.

  13 |   return (
  14 |     <div className="relative">
> 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
     |                      ^
  16 |
  17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
  18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
(Perplexica) issa@23Lap:~/perplexica/Perplexica/ui$scribe the bug**

just follow the steps of the installation process, ui side doesn't build, followed the steps to letter.

**Comment by 5a9awneh** [comment]
Same as #163 ... [Fix](https://github.com/ItzCrazyKns/Perplexica/issues/163#issuecomment-2144034346)

**Comment by kevin4801** [comment]
=> ERROR [perplexica-frontend 5/5] RUN yarn build                                                                                                    24.9s
------
 > [perplexica-frontend 5/5] RUN yarn build:
0.397 yarn run v1.22.19
0.423 $ next build
1.021 Attention: Next.js now collects completely anonymous telemetry regarding usage.
1.022 This information is used to shape Next.js' roadmap and prioritize features.
1.022 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
1.022 https://nextjs.org/telemetry
1.022
1.122    ▲ Next.js 14.1.4
1.122
1.193    Creating an optimized production build ...
2.904 (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2.904 (Use `node --trace-deprecation ...` to show where the warning was created)
12.55 (node:103) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
12.55 (Use `node --trace-warnings ...` to show where the warning was created)
12.99 (node:103) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
20.36  ✓ Compiled successfully
20.36    Linting and checking validity of types ...
24.75 Failed to compile.
24.75
24.75 ./components/EmptyChat.tsx:15:22
24.75 Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
24.75   Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.
24.75
24.75   13 |   return (
24.75   14 |     <div className="relative">
24.75 > 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
24.75      |                      ^
24.75   16 |
24.75   17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
24.75   18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
24.79 error Command failed with exit code 1.
24.79 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1


What should i do ?

**Comment by WanQuanXie** [comment]
You can temporarily remove the `<ThemeSwitcher/>` from **EmptyChat.tsx** and **Navbar.tsx**. Refer to this PR #168

**Comment by ItzCrazyKns** [comment]
Fixed in the latest release, please re-install Perplexica making sure the previous images are deleted (if using Docker).
