### ISSUE TITLE
API_base, api_url

### ISSUE THREAD

**Issue by fatherxtreme123** [ItzCrazyKns/Perplexica#176]
openai api key I hope to support API_base, api_url

**Comment by Rhythmicc** [comment]
I really need it too!

**Comment by Joldnine** [comment]
+1

**Comment by GobDevv** [comment]
+1 to this many projects only use ollama which I understand why, but don't forget us power users!

**Comment by mudler** [comment]
:+1: stumbling into this as I wanted to setup an example using LocalAI https://github.com/mudler/LocalAI

**Comment by ItzCrazyKns** [comment]
It does support custom OpenAI endpoints and API key. You just need to install it and after running it for the first time, just open the settings menu and select the custom OpenAI provider.

**Comment by mudler** [comment]
@ItzCrazyKns that's good! Is there any chance to have an environment variable or something to control this during start? Would be much easier to then deploy this together with other projects without needing user interaction
