### ISSUE TITLE
Running yarn build fails on fresh installation

### ISSUE THREAD

**Issue by mystogan99** [ItzCrazyKns/Perplexica#177]
**Describe the bug**
Running yarn build for the perplexica-frontend project fails with a type error in the EmptyChat.tsx component. The error message indicates that the size property passed to the ThemeSwitcher component does not exist on the expected prop types.

**To Reproduce**

1. Clone the Project
2. Change all the configs as defined in the Readme
3. run `docker compose up -d --build`
```bash
./components/EmptyChat.tsx:15:22
Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
  Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.

  13 |   return (
  14 |     <div className="relative">
> 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
     |                      ^
  16 |
  17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
  18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
  ```

**Expected behavior**
The yarn build command should compile the project successfully without any type errors.

**Screenshots**
<img width="1646" alt="Screenshot 2024-06-07 at 3 50 54 PM" src="https://github.com/ItzCrazyKns/Perplexica/assets/43119272/90ef5677-c227-4677-b640-a93a1a2094ed">

**Additional context**
- The error occurs in the EmptyChat.tsx file on line 15.
- The ThemeSwitcher component is being passed a size prop of type number, but it seems that the component's prop types do not include a size property.

**Comment by WanQuanXie** [comment]
You can temporarily remove the <ThemeSwitcher/> from **EmptyChat.tsx** and **Navbar.tsx** to fix it. 
Refer to this PR #168

**Comment by nuwansamaranayake** [comment]
I am getting the same error. "You can temporarily remove the from EmptyChat.tsx and Navbar.tsx to fix it." what should I remove from EmtpyChat.tsx and Navbar.tsx files ?

**Comment by WanQuanXie** [comment]
> I am getting the same error. "You can temporarily remove the from EmptyChat.tsx and Navbar.tsx to fix it." what should I remove from EmtpyChat.tsx and Navbar.tsx files ?

Sorry, there are some words lost. You should remove the `<ThemeSwitcher/>`. I re-edit my reply above.

**Comment by eviljosh** [comment]
Another workaround:  we can leave `ThemeSwitcher` in place and update the definition.

In `ui/components/theme/Switcher.tsx`, update the existing definition of the component to add an optional `size` prop, e.g.:
```
const ThemeSwitcher = ({ className, size }: { className?: string; size?: number })
```

**Comment by mystogan99** [comment]
@eviljosh Your solution works perfectly well. I am closing this now.
