### ISSUE TITLE
[FR] Preserve the current conversation, and create a new one.

### ISSUE THREAD

**Issue by wwjCMP** [ItzCrazyKns/Perplexica#179]
**Is your feature request related to a problem? Please describe.**

Retaining conversations is a prerequisite for in-depth research into the questions. From the software's UI perspective, this should be implemented. I would like to know the plans in this regard. After all, this is a basic function.

**Comment by ItzCrazyKns** [comment]
Same as https://github.com/ItzCrazyKns/Perplexica/issues/4
