### ISSUE TITLE
[FR] Specify the language for LLM generation used in search and final response through variables respectively.

### ISSUE THREAD

**Issue by wwjCMP** [ItzCrazyKns/Perplexica#181]
**Is your feature request related to a problem? Please describe.**

https://github.com/ItzCrazyKns/Perplexica/issues/72

Previously, we discussed this issue. The main concern is about damaging the built-in prompt, but in fact, we don't need to make any changes to the original prompt, just add some content base on it.

For a multi-step process, we can easily specify the language for LLM output at each step without breaking the original prompt, simply by adding a prompt at the end of each step: "Please answer in $variable."

By setting two variables, we can control the language of the materials we search for and the language used to answer the final question. Since LLMs have cross-lingual capabilities, we can control the output language with explicit instructions regardless of the language of the prompts and reference materials.

For example, if I search for general questions, I can set the search language to Chinese or other languages; the response language to Chinese or other languages. If I search for academic questions first, I can set the search language to English and the response language to Chinese or other languages.

By placing options for these two language settings on the dialogue interface and dynamically modifying the prompt with variables, users can easily control the language of the materials they want to use for question answering. Currently, the search language depends entirely on the language of the question, and sometimes it can only be English content. This is because even if other languages are used to ask questions, the content for retrieval is in English due to the English prompts in the first step.

**Comment by PeterDaveHello** [comment]
This feature is important!

**Comment by jeanchristophe13v** [comment]
I tried to modify the prompts in root file, adding "Respond in Chinese" at the end of every related prompt. But that seemed not working, output was always English by default regardless what I've changed.

![Image](https://github.com/user-attachments/assets/c82d541d-649b-4301-baf3-05109f9b6725)
