### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by henri-edh** [ItzCrazyKns/Perplexica#183]
After : 
npm i  ( in both UI and Root )
npm run build ( in UI )
./components/EmptyChat.tsx:15:22
Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
  Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.

  13 |   return (
  14 |     <div className="relative">
> 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
     |                      ^
  16 |
  17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
  18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">

![Screenshot 2024-06-10 124027](https://github.com/ItzCrazyKns/Perplexica/assets/34627791/8c36feca-b556-4acf-bbd4-c10cdc2992d0)

**Comment by goalkeepr** [comment]
I removed "size={17}" from Themeswitcher in EmptyChat.tsx and NavBar.tsx and it built successfully.

**Comment by dheerapat** [comment]
fix with #168
