### ISSUE TITLE
Error loading Ollama models: TypeError: fetch failed

### ISSUE THREAD

**Issue by hamelcubsfan** [ItzCrazyKns/Perplexica#19]
**Describe the bug**
docker terminal says "Error loading Ollama models: TypeError: fetch failed"

I have the proper information in the config.toml, or so I think:

[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"
CHAT_MODEL_PROVIDER = "ollama" # "openai" or "ollama"
CHAT_MODEL = "llama3:latest" # Name of the model to use

[API_KEYS]
OPENAI = "" # OpenAI API key - [redacted]

[API_ENDPOINTS]
SEARXNG = "http://localhost:32768" # SearxNG API URL
OLLAMA = "http://localhost:11434" # Ollama API URL

**Comment by ItzCrazyKns** [comment]
Hi, please change your Ollama URL to `http://host.docker.internal:11434` and re-build the images. It should fix the issue.

**Make sure the previous images and containers are deleted before you build new images**

**Comment by hamelcubsfan** [comment]
Fixed. Thank you

**Comment by denaha** [comment]
> Hi, please change your Ollama URL to `http://host.docker.internal:11434` and re-build the images. It should fix the issue.
> 
> **Make sure the previous images and containers are deleted before you build new images**

This fixed the issue, where the Config information was not loaded.
