### ISSUE TITLE
 Issue with Multiple Iterations and Disabled Enter Button After Uploading Document

### ISSUE THREAD

**Issue by SoumyaSubhrajit** [ItzCrazyKns/Perplexica#194]
**Describe the bug**
I am encountering an issue on the Perplexity website when I upload a document and ask a question. The platform generates an answer and continues to go through several iterations, producing the same pattern of answers multiple times. After these iterations, I am unable to send any further queries because the enter button in the search option becomes automatically disabled.

**To Reproduce**
1. Upload a document to the Perplexity website.
2. Ask a question related to the uploaded document.
3. Observe the system generating answers through multiple iterations.
4. Notice the same pattern of answers being generated multiple times.
5. Attempt to send another query after these iterations.
6 .Observe that the enter button in the search option is disabled and no further queries can be sent.

**Expected behavior**
The system should generate a concise and accurate answer without unnecessary repetitions and should allow further queries to be sent without disabling the enter button.

Browser: Chrome
Operating System: Windows 10

**Comment by ItzCrazyKns** [comment]
The document upload functionality is not yet completed, the button there is a placeholder so issues may persist
