### ISSUE TITLE
Failed to docker compoe up

### ISSUE THREAD

**Issue by braindotai** [ItzCrazyKns/Perplexica#196]
**Describe the bug**
Unable to docker compose up with fresh system setup

**To Reproduce**
I am following docker guide. Tried docker compose up -d and got following error
```
Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
```

**Expected behavior**
It should run without any error and webapp should get available on localhost:port

**Screenshots**
![image](https://github.com/ItzCrazyKns/Perplexica/assets/50226064/038450aa-26ac-4fa5-8056-72191b8698e6)

**Comment by kunaldeo** [comment]
+1

**Comment by braindotai** [comment]
@kunaldeo thanks. Got it solved by [this](https://github.com/ItzCrazyKns/Perplexica/issues/175#issuecomment-2161094257) comment.

**Comment by braindotai** [comment]
But I am unable to get running with local ollama. In my laptop ollama service is up at http://localhost:11434/ . As per the docs, I have set API URL for ollama to host.docker.internal:11434.... full config below
![image](https://github.com/ItzCrazyKns/Perplexica/assets/50226064/fe77b204-c889-479e-a172-3dfe41f71d82)

Unable to connect with above config. Error says unable to connect to ollama.
![image](https://github.com/ItzCrazyKns/Perplexica/assets/50226064/7bc728ca-ca9b-4ae3-93f0-7cab9235b36b)

**Comment by josharsh** [comment]
The issue with Yarn Install during docker-compose up
![Uploading image.png…]()

**Comment by wlarch** [comment]
I am encountering the same issue as [josharsh](https://github.com/josharsh) .

```
(...)
 => CACHED [perplexica-backend  8/10] RUN sed -i "s|SEARXNG = ".*"|SEARXNG = "http://sear  0.0s
 => ERROR [perplexica-backend  9/10] RUN yarn install                                     33.6s
------                                                                                          
 > [perplexica-backend  9/10] RUN yarn install:                                                 
0.330 yarn install v1.22.19                                                                     
0.366 [1/4] Resolving packages...                                                               
0.448 [2/4] Fetching packages...                                                                
26.99 [3/4] Linking dependencies...                                                             
26.99 warning " > ts-node@10.9.2" has unmet peer dependency "@types/node@*".
28.16 [4/4] Building fresh packages...
33.35 error /home/perplexica/node_modules/sharp: Command failed.
33.35 Exit code: 1
33.35 Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
33.35 Arguments: 
33.35 Directory: /home/perplexica/node_modules/sharp
33.35 Output:
33.35 sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-x64.tar.br
33.35 sharp: Installation error: Request timed out
```

**Comment by J-eremy** [comment]
![image](https://github.com/ItzCrazyKns/Perplexica/assets/934651/a6900d4e-d9a0-4f28-89af-827e6e0bf354)

exact same issue, trying fix above.

**Comment by asifrahaman13** [comment]
Hey currently there is a bug. You can fix this using the following code in the 

ui/components/theme/Switcher file.
```tsx
'use client';
import { useTheme } from 'next-themes';
import { SunIcon, MoonIcon, MonitorIcon } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { cn } from '@/lib/utils';
import { Select } from '../SettingsDialog';

type Theme = 'dark' | 'light' | 'system';

interface ThemeSwitcherProps {
  className?: string;
  size?: number; 
}

const ThemeSwitcher = ({ className, size }: ThemeSwitcherProps) => {
  const [mounted, setMounted] = useState(false);

  const { theme, setTheme } = useTheme();

  const isTheme = useCallback((t: Theme) => t === theme, [theme]);

  const handleThemeSwitch = (theme: Theme) => {
    setTheme(theme);
  };

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (isTheme('system')) {
      const preferDarkScheme = window.matchMedia(
        '(prefers-color-scheme: dark)',
      );

      const detectThemeChange = (event: MediaQueryListEvent) => {
        const theme: Theme = event.matches ? 'dark' : 'light';
        setTheme(theme);
      };

      preferDarkScheme.addEventListener('change', detectThemeChange);

      return () => {
        preferDarkScheme.removeEventListener('change', detectThemeChange);
      };
    }
  }, [isTheme, setTheme, theme]);

  // Avoid Hydration Mismatch
  if (!mounted) {
    return null;
  }

  return (
    <Select
      className={className}
      value={theme}
      onChange={(e) => handleThemeSwitch(e.target.value as Theme)}
      options={[
        { value: 'light', label: 'Light' },
        { value: 'dark', label: 'Dark' }
      ]}
      size = {size}
    />
  );
};

export default ThemeSwitcher;
```


if you rebuild again after this, it will work. I had the same issue and it worked after doing that.

**Comment by Nordln** [comment]
Point of note, the issue relating to a timeout following an attempt to download libvips-8.14.5 is a different issue to the issue noted in ui/components/theme/Switcher. The issue with Switcher file is addressed with the fix above (thanks!)

After addressing that first issue, I now also see the timeout error:
```
 > [ 9/10] RUN yarn install:                                                                                                                                                                                                     
0.146 yarn install v1.22.19                                                                                                                                                                                                      
0.172 [1/4] Resolving packages...                                                                                                                                                                                                
0.209 [2/4] Fetching packages...                                                                                                                                                                                                 
7.776 [3/4] Linking dependencies...                                                                                                                                                                                              
7.777 warning " > ts-node@10.9.2" has unmet peer dependency "@types/node@*".
8.817 [4/4] Building fresh packages...
13.98 error /home/perplexica/node_modules/sharp: Command failed.
13.98 Exit code: 1
13.98 Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
13.98 Arguments: 
13.98 Directory: /home/perplexica/node_modules/sharp
13.98 Output:
13.98 sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-arm64v8.tar.br
13.98 sharp: Installation error: Request timed out
13.98 sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
13.98 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
That quoted file is fully downloadable from the same machine, so it's not clear why it is timing out at install.

**Comment by Nordln** [comment]
The specified version of the 'share' node module is not installing, Adding the following to the app.dockerfile above yarn install gets the installer passed this point.
```
RUN yarn install sharp
RUN yarn install
```

**Comment by aceliuchanghong** [comment]
> @J-eremy @josharsh @braindotai @wlarch
> 
> Hey currently there is a bug. You can fix this using the following code in the
> 
> ui/components/theme/Switcher file.
> 
> ```tsx
> 'use client';
> import { useTheme } from 'next-themes';
> import { SunIcon, MoonIcon, MonitorIcon } from 'lucide-react';
> import { useCallback, useEffect, useState } from 'react';
> import { cn } from '@/lib/utils';
> import { Select } from '../SettingsDialog';
> 
> type Theme = 'dark' | 'light' | 'system';
> 
> interface ThemeSwitcherProps {
>   className?: string;
>   size?: number; 
> }
> 
> const ThemeSwitcher = ({ className, size }: ThemeSwitcherProps) => {
>   const [mounted, setMounted] = useState(false);
> 
>   const { theme, setTheme } = useTheme();
> 
>   const isTheme = useCallback((t: Theme) => t === theme, [theme]);
> 
>   const handleThemeSwitch = (theme: Theme) => {
>     setTheme(theme);
>   };
> 
>   useEffect(() => {
>     setMounted(true);
>   }, []);
> 
>   useEffect(() => {
>     if (isTheme('system')) {
>       const preferDarkScheme = window.matchMedia(
>         '(prefers-color-scheme: dark)',
>       );
> 
>       const detectThemeChange = (event: MediaQueryListEvent) => {
>         const theme: Theme = event.matches ? 'dark' : 'light';
>         setTheme(theme);
>       };
> 
>       preferDarkScheme.addEventListener('change', detectThemeChange);
> 
>       return () => {
>         preferDarkScheme.removeEventListener('change', detectThemeChange);
>       };
>     }
>   }, [isTheme, setTheme, theme]);
> 
>   // Avoid Hydration Mismatch
>   if (!mounted) {
>     return null;
>   }
> 
>   return (
>     <Select
>       className={className}
>       value={theme}
>       onChange={(e) => handleThemeSwitch(e.target.value as Theme)}
>       options={[
>         { value: 'light', label: 'Light' },
>         { value: 'dark', label: 'Dark' }
>       ]}
>       size = {size}
>     />
>   );
> };
> 
> export default ThemeSwitcher;
> ```
> 
> if you rebuild again after this, it will work. I had the same issue and it worked after doing that.

this works,thankyou
