### ISSUE TITLE
Yarn.lock issue I discussed earlier

### ISSUE THREAD

**Issue by a7t0fwa7** [ItzCrazyKns/Perplexica#2]
Hey here was the error message I had yesterday
![image](https://github.com/ItzCrazyKns/Perplexica/assets/43460290/2c61a5be-0791-4646-b8d9-0db6f19dfd93)

I managed to fix the issue by installing Yarn on my Debian system, hence why I created a pull request adding the instructions on how to do it for those who may have encountered a similar error.

Cheers

**Comment by ItzCrazyKns** [comment]
Hi, after a little bit of exploration I found that the package lock files were ignored by git and were not committed. This issue is fixed by https://github.com/ItzCrazyKns/Perplexica/commit/3859e3db03993838f135951b486dd1d3e214fe7f. Thanks!
