### ISSUE TITLE
Add JSON output

### ISSUE THREAD

**Issue by rick-github** [ItzCrazyKns/Perplexica#200]
**Is your feature request related to a problem? Please describe.**
Some search engines (eg searxng) have the ability to format the output in JSON format.  This makes it very useful for integration in to programmatic pipelines (eg, LLM agents).

**Describe the solution you'd like**
A query to Perplexica using the `/?q=%s` feature would take an extra argument, `format`, eg: `/?q=%s&format=json`.  This would run the perplexica query and instead of HTML, generate a JSON object:

```json
{
  "query": "stuff",
  "answer": "Hmm, sorry I couldn't find any relevant information on this topic with the provided context.",
  "references": [],
  "related": []
}
```

**Comment by johannoriel** [comment]
same #141

**Comment by ItzCrazyKns** [comment]
Same as https://github.com/ItzCrazyKns/Perplexica/issues/141

**Comment by quantumalchemy** [comment]
great !  But How does this work?
I tried the latest ver .. and
http://localhost:3000/?q=what+is+the+abramelin+ritual&format=json
just came back with the html  not json

**Comment by rick-github** [comment]
I think ItzCrazyKns means that it's a duplicate of #141.  I'm playing around with adding an api endpoint to `src/routes` and following the logic of `handleMessage` in `src/websocket/messageHandler.ts` but my typescript isn't great so it's not very successful so far.

**Comment by rick-github** [comment]
I think ItzCrazyKns means it's a duplicate of #141 and closed on that basis.  I'm playing around with adding an api endpoint to `src/routes` and following the logic of `handleMessage` in `src/websocket/messageHandler.ts` but my typescript is not great so it's not very successful so far.

**Comment by ksingh-scogo** [comment]
Would be great if someone post an example of how to use this
