### ISSUE TITLE
Add per-user support for history/settings

### ISSUE THREAD

**Issue by rick-github** [ItzCrazyKns/Perplexica#201]
**Is your feature request related to a problem? Please describe.**
This might be part of the History development, but just in case: in a multi-person household, it's useful for query history to be assigned to the person that ran the query. 

**Describe the solution you'd like**
The ability to create users/logins such that query history or settings can be saved on a per-user basis.  If no users are defined, then the history/settings are global (see Open WebUI [WEBUI_AUTH](https://docs.openwebui.com/getting-started/env-configuration#webui_auth))

**Comment by ItzCrazyKns** [comment]
Hi, would be better to make this a comment in this issue https://github.com/ItzCrazyKns/Perplexica/issues/4, rather than creating another one
