### ISSUE TITLE
While Running For first time, got this error 

### ISSUE THREAD

**Issue by 7990satyam200** [ItzCrazyKns/Perplexica#202]
11.04 Retrying 1/3...
16.51  ✓ Compiled successfully
16.51    Linting and checking validity of types ...
20.26 Failed to compile.
20.26
20.26 ./components/EmptyChat.tsx:15:22
20.26 Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
20.26   Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.
20.26
20.26   13 |   return (
20.26   14 |     <div className="relative">
20.26 > 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
20.26      |                      ^
20.26   16 |
20.26   17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
20.26   18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
20.29 error Command failed with exit code 1.
20.29 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
(base) orion

**Comment by mystogan99** [comment]
Follow these steps to fix:

- `cd ui/components/theme/`
- `nano Switcher.tsx`

Change the component declaration as follows:

```js
const ThemeSwitcher = ({ className }: { className?: string, size?: number })
```

This should fix the problem.

**Comment by rb81** [comment]
+1 @mystogan99's solution works for me!

**Comment by ItzCrazyKns** [comment]
Fixed in the latest release
