### ISSUE TITLE
Google Serp API support

### ISSUE THREAD

**Issue by JamesClarke7283** [ItzCrazyKns/Perplexica#207]
**Is your feature request related to a problem? Please describe.**
The search is not currently consistant to what you would get, if you used what perplexity uses, the Google Serp API.

**Describe the solution you'd like**
I would like the ability to specify a google Serp API key, and also the number of results the AI reads.

**Describe alternatives you've considered**
Or we could Make the search options for searxng, appear in the perplexica settings, so you can pick how it searches 

**Additional context**
N/A

**Comment by ItzCrazyKns** [comment]
Please see https://github.com/ItzCrazyKns/Perplexica/pull/29
