### ISSUE TITLE
Project is broken.

### ISSUE THREAD

**Issue by Trupal07** [ItzCrazyKns/Perplexica#208]
BUG-1 

after git clone your repository i followed your steps of docker after completing all the steps i used compose -d command to start the AI,
after it got started whenever i try to search it keeps on finding answer and when i click on library or discover it always show nothing just blank black page.

BUG-2
when i was trying to switch between library and discover, from home where search begins there was option of search image and video got disappear.
![Screenshot (102)](https://github.com/ItzCrazyKns/Perplexica/assets/62878351/35b04f12-c068-4065-b4d2-3166e2e0a81a)
![Screenshot (103)](https://github.com/ItzCrazyKns/Perplexica/assets/62878351/709e330a-d68b-441e-9e46-d0f242f0f314)
![Screenshot (104)](https://github.com/ItzCrazyKns/Perplexica/assets/62878351/4284645c-77dc-4152-93a0-6332b18ee7d0)
![Screenshot (105)](https://github.com/ItzCrazyKns/Perplexica/assets/62878351/e8e3b9af-9f5a-4b78-b562-2bd3b0b2f0c4)
![Screenshot (106)](https://github.com/ItzCrazyKns/Perplexica/assets/62878351/d686ff7f-316a-4cb9-a183-800207f04d0c)

**Comment by Trupal07** [comment]
![Screenshot (107)](https://github.com/ItzCrazyKns/Perplexica/assets/62878351/5399fa37-b68d-4503-8c95-86ababcb00e8)

**Comment by bharatrocks100** [comment]
I am also getting exact same issue. Not sure whether this project is managed anymore.

**Comment by ItzCrazyKns** [comment]
The library and discover features are under development so they will not work. Regarding your search issues provide me with your logs from the backend container

**Comment by CD1010** [comment]
@ItzCrazyKns Please avoid common ports like  3000 and 8080 when exposing.  Everybody and his brother uses those ports and more than one thing on docker env will cause conflicts.
