### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by Uddhav07** [ItzCrazyKns/Perplexica#209]
**Describe the bug**
try installin the product on windows

**Screenshots**
![image](https://github.com/ItzCrazyKns/Perplexica/assets/93899908/83160d6f-0426-45b4-af88-05fdc3972e65)

**Additional context**
` => ERROR [perplexica-frontend 5/5] RUN yarn build                                                                            225.6s
------
 > [perplexica-frontend 5/5] RUN yarn build:
7.028 yarn run v1.22.22
7.184 $ next build
11.84 Attention: Next.js now collects completely anonymous telemetry regarding usage.
11.84 This information is used to shape Next.js' roadmap and prioritize features.
11.84 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
11.84 https://nextjs.org/telemetry
11.84
12.30    ▲ Next.js 14.1.4
12.30
12.56    Creating an optimized production build ...
35.36 (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
35.36 (Use `node --trace-deprecation ...` to show where the warning was created)
132.7 Compiler server unexpectedly exited with code: null and signal: SIGTERM
148.9 (node:91) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
148.9 (Use `node --trace-warnings ...` to show where the warning was created)
150.5 (node:91) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
151.6 request to https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap failed, reason:
151.6
151.6 Retrying 1/3...
192.3  ✓ Compiled successfully
192.3    Linting and checking validity of types ...
221.7 Failed to compile.
221.7
221.7 ./components/EmptyChat.tsx:15:22
221.7 Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
221.7   Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.
221.7
221.7   13 |   return (
221.7   14 |     <div className="relative">
221.7 > 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
221.7      |                      ^
221.7   16 |
221.7   17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
221.7   18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
223.1 error Command failed with exit code 1.
223.1 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
`

**Comment by nelagla** [comment]
I have the same issue

**Comment by Uddhav07** [comment]
n

**Comment by nelagla** [comment]
Was this issue solved?
Could I get some help

**Comment by FemBoxbrawl** [comment]
> Was this issue solved? Could I get some help

same.

**Comment by FemBoxbrawl** [comment]
> Was this issue solved? Could I get some help

https://github.com/ItzCrazyKns/Perplexica/issues/187
