### ISSUE TITLE
Pass through searxng search modifiers

### ISSUE THREAD

**Issue by rick-github** [ItzCrazyKns/Perplexica#210]
**Is your feature request related to a problem? Please describe.**
Searxng has the [ability](https://docs.searxng.org/user/search-syntax.html) to limit searches to pre-defined categories and engines, even custom backends.  In some cases when using Perplexica, the user knows that the best results will come from one or more of these categories, so hinting to Perplexica which ones to use would be useful.

**Describe the solution you'd like**
In the search text box, use the same hints as searxng uses, eg `!reddit best phone` or `!google :de experience with remote work`.  Perplexica extracts them, runs the query through its internal rewriter, and then prepends the hints to the queries sent to searxng.

**Comment by rick-github** [comment]
There are some pre-defined agents that already send an `engines` spec, but being able to use arbitary modifiers allows using custom searxng backends (eg, opensearch corpus defined in searxng/settings.yml) without having to update perplexica.

**Comment by ItzCrazyKns** [comment]
We have focus modes set up to choose the best engines for different types of searches. This means we already use the best options to get you the results you need. I'm going to close this issue for now but we can always revisit it if needed.
