### ISSUE TITLE
Error when running the docker compose up -d the first time

### ISSUE THREAD

**Issue by kwiksys** [ItzCrazyKns/Perplexica#212]
1.064 Attention: Next.js now collects completely anonymous telemetry regarding usage.
1.065 This information is used to shape Next.js' roadmap and prioritize features.
1.065 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
1.065 https://nextjs.org/telemetry
1.065
1.138    ▲ Next.js 14.1.4
1.138
1.192    Creating an optimized production build ...
2.395 (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2.395 (Use `node --trace-deprecation ...` to show where the warning was created)
9.651 (node:139) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
9.651 (Use `node --trace-warnings ...` to show where the warning was created)
9.925 (node:139) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
14.75  ✓ Compiled successfully
14.75    Linting and checking validity of types ...
18.40 Failed to compile.
18.40
18.40 ./components/EmptyChat.tsx:15:22
18.40 Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
18.40   Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.
18.40
18.40   13 |   return (
18.40   14 |     <div className="relative">
18.40 > 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
18.40      |                      ^
18.40   16 |
18.40   17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
18.40   18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
18.42 error Command failed with exit code 1.
18.42 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by end3r-man** [comment]
same issue ``  => ERROR [perplexica-frontend 5/5] RUN yarn build                                                                                                       76.9s
------
 > [perplexica-frontend 5/5] RUN yarn build:
0.834 yarn run v1.22.22
0.879 $ next build
2.110 Attention: Next.js now collects completely anonymous telemetry regarding usage.
2.110 This information is used to shape Next.js' roadmap and prioritize features.
2.110 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2.110 https://nextjs.org/telemetry
2.110
2.359    ▲ Next.js 14.1.4
2.359
2.582    Creating an optimized production build ...
6.287 (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
6.287 (Use `node --trace-deprecation ...` to show where the warning was created)
33.57 (node:79) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
33.57 (Use `node --trace-warnings ...` to show where the warning was created)
34.59 (node:79) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
57.04  ✓ Compiled successfully
57.05    Linting and checking validity of types ...
76.26 Failed to compile.
76.26
76.30 ./components/EmptyChat.tsx:15:22
76.30 Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
76.30   Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.
76.30
76.30   13 |   return (
76.30   14 |     <div className="relative">
76.30 > 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
76.30      |                      ^
76.30   16 |
76.30   17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
76.30   18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
76.52 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
76.52 error Command failed with exit code 1.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1 ``

**Comment by bannert1337** [comment]
Got the same error today, after running `docker compose up -d`

**Comment by PeterDaveHello** [comment]
Relates #185?

**Comment by PeterDaveHello** [comment]
Using the [`v1.5.0`](https://github.com/ItzCrazyKns/Perplexica/releases/tag/v1.5.0) tag could help prevent this issue, though it's not the latest version.

**Comment by Ed-cred** [comment]
You could also edit the Switcher.tsx to include the size if you still want to stay on the latest release and get a successful build.
```typescript
const ThemeSwitcher = ({ className, size }: { className?: string; size?: number }) 
```
There are many duplicate issues for this, so you could either revert to v1.5.0 or make this quick change and be on your way

**Comment by bannert1337** [comment]
> You could also edit the Switcher.tsx to include the size if you still want to stay on the latest release and get a successful build.
> 
> ```ts
> const ThemeSwitcher = ({ className, size }: { className?: string; size?: number }) 
> ```
> 
> There are many duplicate issues for this, so you could either revert to v1.5.0 or make this quick change and be on your way

This worked

**Comment by ItzCrazyKns** [comment]
Fixed in the latest release
