### ISSUE TITLE
Add shortcut / for input

### ISSUE THREAD

**Issue by antistereov** [ItzCrazyKns/Perplexica#213]
**Is your feature request related to a problem? Please describe.**
No problem, but quality of life. When a response was generated, it would be really nice to just be able to hit "/" to select the text field and create a new prompt instead of moving down the cursor to the bottom and manually clicking the text field.

**Describe the solution you'd like**
When hitting "/" on the keyboard, the text field should be selected and you should be able to write a new response.

**Describe alternatives you've considered**
Moving down the cursor to the bottom and manually clicking the text field.

**Additional context**
YouTube, GitHub and other sites implemented this shortcut, so it seems to be a standard.

**Comment by ItzCrazyKns** [comment]
Nice idea!

**Comment by ItzCrazyKns** [comment]
Implemented in https://github.com/ItzCrazyKns/Perplexica/commit/9a96fd4788e5bfaa15f74ac5e42184184364c4c1
