### ISSUE TITLE
Render LaTex formulas

### ISSUE THREAD

**Issue by antistereov** [ItzCrazyKns/Perplexica#214]
**Is your feature request related to a problem? Please describe.**
When using Perplixica for research, it would be very nice to see LaTex formulas rendered correctly. This would be good to have for inline latex as well as equations.

**Describe the solution you'd like**
When the response includes LaTex notation, it should be rendered. [BetterGPT](https://github.com/ztjhz/BetterChatGPT) has a setting to toggle inline LaTex. This could be nice for this project as well.

**Describe alternatives you've considered**
Right now, I have to copy and paste the response to a markdown editor so the formulas are displayed correctly. This feature would be quality of life for me.

**Additional context**
As mentioned above, [BetterGPT](https://github.com/ztjhz/BetterChatGPT) implmented this already.

**Comment by ItzCrazyKns** [comment]
We use https://www.npmjs.com/package/markdown-to-jsx to convert markdown into JSX. As of now, it doesn't supports rendering of LaTex formulas directly so, we cannot implement it (for now), but we might consider it later in the time.

**Comment by MHellmund** [comment]
Please reconsider. A scientific search engine should be able to render math, using e.g., https://katex.org/ or 
https://www.mathjax.org/ . 
For markdown-to-jsx, see here: https://github.com/quantizor/markdown-to-jsx/issues/480#issuecomment-1872353128
