### ISSUE TITLE
Warnings on installation

### ISSUE THREAD

**Issue by devops-snap-shoot** [ItzCrazyKns/Perplexica#216]
**Describing the bug**

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

**To Reproduce**
on non-docker installation 
1. run `npm i` in  the `ui` directory 
2. See warnings

**Comment by ItzCrazyKns** [comment]
We're not using most of the packages directly, they're dependency of some dependency of Perplexica. I will update them and see if it works but it should normally not cause any issue

**Comment by devops-snap-shoot** [comment]
Many Thanks!!!
