### ISSUE TITLE
Erro at npm run build` in  the `ui` 

### ISSUE THREAD

**Issue by devops-snap-shoot** [ItzCrazyKns/Perplexica#217]
**Describe the bug**

**To Reproduce**

1. `npm run build` in  the `ui`  (without docker)
2. See error:
Linting and checking validity of types  ...Failed to compile.

./components/EmptyChat.tsx:15:22
Type error: Type '{ size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & { className?: string | undefined; }'.
  Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.

  13 |   return (
  14 |     <div className="relative">
> 15 |       <ThemeSwitcher size={17} className="absolute top-2 right-0 lg:hidden" />
     |                      ^
  16 |
  17 |       <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
  18 |         <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">

**Expected behavior**
// Update the props type to include `size`
type ThemeSwitcherProps = {
  className?: string;
  size?: number; // Add the size property here
};
After the sugested update the front end was bult!

**Comment by AIisaweapon** [comment]
Or juste delete the size attribute ^^

**Comment by AIisaweapon** [comment]
Or just delete the size attribute ^^

**Comment by ItzCrazyKns** [comment]
Fixed in #168
