### ISSUE TITLE
Doesn't work with another service/docker running on 8080

### ISSUE THREAD

**Issue by 5a9awneh** [ItzCrazyKns/Perplexica#219]
**Describe the bug**

I have `Open WebUI` running as docker on port `8080`, which conflicts with `searxng`'s port binding on the same port and causes an `Invalid connection` error.

Changing searxng's port bindings under `docker-compose.yaml` from `8080` to any other port doesn't work and renders `localhost:3000` & `localhost:4000` unreachable.

Could `8080` be hard-coded somewhere else?

**To Reproduce**

1. Have Open WebUI (or any other service/docker already running on `8080`)
2. Clone Perplexica
3. Change searxng port binding from `8080` to another in `docker-compose.yaml`
4. Install Perplexica per instructions `docker compose up -d`
5. System breaks.

**Expected behavior**
Should be able to change the binding port for searxng and system should function normally using the assigned port

**Additional context**
- System: Linux Mint
- Ollama (Local) is already working fine in both Terminal & Open WebUI (docker)

**Comment by ItzCrazyKns** [comment]
You need to add an environment variable in the docker-compose for SearXNG with your port. For more details see https://github.com/searxng/searxng-docker/issues/20
