### ISSUE TITLE
Not working on Fresh install -  tested on 2 different systems.

### ISSUE THREAD

**Issue by braindotai** [ItzCrazyKns/Perplexica#220]
**Describe the bug**
Not working on fresh installed, steps followed from README.md

**To Reproduce**

1. git clone
2. Chang ollama url to `http://host.docker.internal:11434` as mentioned in the readme. Its my local ollama, both ollama and perpliexica is on same laptop.
3. docker compose up .... starts throwing error
4. On entering on query on localhost:3000 does nothing.

**Expected behavior**
After docker compose up all should work fine, when entering a query it should ping my local ollama server and prepare and show the results.

**Additional context**
Here are full logs:
[perplexica-docker-compose-up.txt](https://github.com/user-attachments/files/15951895/perplexica-docker-compose-up.txt)

**Comment by ItzCrazyKns** [comment]
Seems like Perplexica is not being able to connect to Ollama. What OS are you using?

**Comment by braindotai** [comment]
> Seems like Perplexica is not being able to connect to Ollama. What OS are you using? 

I am using arch Linux. http://localhost:11434 is saying Ollama is running. I don't think os is the issue, I've downloaded other open source stuff like continue extension in vscode, that works just fine with my local ollama.

**Comment by ItzCrazyKns** [comment]
You need to follow the Ollama connection error guide in the readme below
the installation.

**Comment by braindotai** [comment]
I've tried not. here's what I did.

1. $ ip addr show # copied the inet value from wlan0`
2. Changed ollama to this `OLLAMA = "http://<my_machine_ip>:11434"`
3. `$ sudo ufw allow 11434/tcp`
4. Stopped Ollama and restarted it with `$ OLLAMA_HOST=0.0.0.0 ollama serve`

Still not working

```
perplexica-backend-1   | error: Error loading Ollama models: TypeError: fetch failed
perplexica-backend-1   | error: Error loading Ollama embeddings: TypeError: fetch failed
perplexica-backend-1   | error: undefined
perplexica-backend-1   | error: Error loading Ollama models: TypeError: fetch failed
perplexica-backend-1   | error: Error loading Ollama embeddings: TypeError: fetch failed
perplexica-backend-1   | error: undefined
```

**Comment by ItzCrazyKns** [comment]
Try sending a curl request to the same URL

**Comment by braindotai** [comment]
![Screenshot from 2024-06-25 15-47-53](https://github.com/ItzCrazyKns/Perplexica/assets/50226064/79927a21-d2db-455a-9481-88ae0851ef22)

All is good with the ollama url.

**Comment by braindotai** [comment]
Oh wait, I needed to change the settings and select ollama manually. Got it working now!

**Comment by adambeck7** [comment]
@braindotai I'm hitting the same issue but can't change the chat model provider.
