### ISSUE TITLE
Tree map Feature request

### ISSUE THREAD

**Issue by tiwentichat** [ItzCrazyKns/Perplexica#225]
**Is your feature request related to a problem? Please describe.**
Would you like to add the tree map feature to this wonderful project?

**Describe the solution you'd like**
1, every answer should has 3 subtitle (maybe 1,2,or 4), range from left to right
2, change the subtitles to  buttons
3, click the button, means user come up with ai a new question that focus on that button/subtitle
4, there is lines(maybe curves) connected from the former button/subtitle of last question to next 3 buttons
5, the "ask a followup" also change to buttons from left to right

This new UI, looks like a tree map,  would let the question and answers more connected and clear; also , more user-friendly,

Most users' actions would be click, click, and click.

**Additional context**
Maybe a little like the AI-generated-todo-list on a task.

**Comment by ItzCrazyKns** [comment]
Can you evaluate more or attach some photos of what you're trying to ask
