### ISSUE TITLE
npm run build error chat_models/ollama

### ISSUE THREAD

**Issue by Michaelxu2022** [ItzCrazyKns/Perplexica#226]
hi build error :

node version  v20.15.0 

npm run build

> perplexica-backend@1.7.0 build
> tsc

src/lib/providers.ts:2:28 - error TS2307: Cannot find module '@langchain/community/chat_models/ollama' or its corresponding type declarations.

2 import { ChatOllama } from '@langchain/community/chat_models/ollama';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/lib/providers.ts:3:34 - error TS2307: Cannot find module '@langchain/community/embeddings/ollama' or its corresponding type declarations.

3 import { OllamaEmbeddings } from '@langchain/community/embeddings/ollama';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/lib/providers.ts

**Comment by ItzCrazyKns** [comment]
> hi build error :
> 
> node version v20.15.0
> 
> npm run build
> 
> > perplexica-backend@1.7.0 build
> > tsc
> 
> src/lib/providers.ts:2:28 - error TS2307: Cannot find module '@langchain/community/chat_models/ollama' or its corresponding type declarations.
> 
> 2 import { ChatOllama } from '@langchain/community/chat_models/ollama'; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/lib/providers.ts:3:34 - error TS2307: Cannot find module '@langchain/community/embeddings/ollama' or its corresponding type declarations.
> 
> 3 import { OllamaEmbeddings } from '@langchain/community/embeddings/ollama'; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Found 2 errors in the same file, starting at: src/lib/providers.ts

I believe you are installing manually, I did built the project before releasing and it worked for me. Did you installed all the packages correctly?

**Comment by phineas-pta** [comment]
im having same error on win 11, using latest commit `c626844`

also i got this message after run `npm i`:

```
added 330 packages, and audited 331 packages in 4m

38 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

**Comment by phineas-pta** [comment]
i found the workaroud: `npm install @langchain/community`

but it's supposed to be automatically installed right ? 🤔

**Comment by ItzCrazyKns** [comment]
![image](https://github.com/ItzCrazyKns/Perplexica/assets/95534749/60ec417a-31f1-45a1-bd6b-e9d5e4aa552c)
I believed NPM doesn't reads the yarn-lock files but langchain has a dependency on @Langchain/community so it should automatically install it but in case, I'll add it into the package file. Cloning the latest code should fix your issue.
