### ISSUE TITLE
Direct search via URL (?q=<term>) seems broken

### ISSUE THREAD

**Issue by ProjectMoon** [ItzCrazyKns/Perplexica#235]
**Describe the bug**
Searching directly via a URL (e.g. `https://perplexica.example.com/?q=search term`) seems broken in the latest release. It loads the page with the term as the title, but no search seems to be performed, and no output is generated.

**To Reproduce**

1. Go to URL of Perplexica server with `?q=` appended to the query string.

**Expected behavior**
Results to load as normal.

**Comment by ItzCrazyKns** [comment]
I'll try to reproduce

**Comment by rick-github** [comment]
Also https://github.com/ItzCrazyKns/Perplexica/issues/199

**Comment by ProjectMoon** [comment]
Bit more info based on browser console:

1. The page loads, and the websocket connection is established.
2. This JSON gets sent up: `{"type":"message","message":{"chatId":"2882b84d8632c0e40a7e1083f130817728d807a4","content":"testing"},"focusMode":"webSearch","history":[["human","testing"]]}` (for `/?q=testing`).
3. But nothing ever comes back.
4. WebSocket connection eventually dies.

Default logging configuration of the Docker images doesn't show any messages printed out, so I am unsure of what's going on on the server.

**Comment by ItzCrazyKns** [comment]
This issue has been fixed in a recent update
