### ISSUE TITLE
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)

### ISSUE THREAD

**Issue by devops-snap-shoot** [ItzCrazyKns/Perplexica#236]
**Describe the bug**
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)
line 14 
EmptyChat.tsx

**To Reproduce**
Open the VS Code open the file
 <div className="relative">
      <div className="flex flex-col items-center justify-center min-h-screen max-w-screen-sm mx-auto p-2 space-y-8">
        <h2 className="text-black/70 dark:text-white/70 text-3xl font-medium -mt-8">
          Use Smart Assistant to ask anything.
        </h2>

**Comment by ItzCrazyKns** [comment]
Not a potential bug, won't cause any issues.
