### ISSUE TITLE
Docker compose fail at perplexica backend building stage at step yarn install

### ISSUE THREAD

**Issue by jiafu83** [ItzCrazyKns/Perplexica#238]
**Describe the bug**
I used the docker method try to build Perplexica, however everytime the build failed at backend building step 11 yarn install part, as showing below:
![image](https://github.com/ItzCrazyKns/Perplexica/assets/1566223/d8d3a517-4a4b-4dfc-9121-d84bf31595ba)

**To Reproduce**
1. Use conda to build a fresh new enviroment, with python=3.11
2. fresh clone Perplexica: git clone https://github.com/ItzCrazyKns/Perplexica.git
3. go to Perplexica folder, and run: docker compose up -d
4. See the similar error
![image](https://github.com/ItzCrazyKns/Perplexica/assets/1566223/341b8085-1ebf-4f3c-9141-4ee3467627bb)

**Additional context**
1. The system is ubuntu 22.04, with docker 27.0
2. Actually I have yarn installed locally, and "yarn add sharp" locally is no problem, but when builds this, it fails, so confusing

**Comment by akramer-zibra** [comment]
Hey @jiafu83 . The `master` branch is the latest development version and so may contain issues. Try `v1.7.0` from 4 days ago (https://github.com/ItzCrazyKns/Perplexica/releases/tag/v1.7.0). This version should build in the docker compose setup without issues.

**Comment by Ed-cred** [comment]
I don't see the relevance  of setting up a python environment, as this project uses Node. As for the sharp problem this is something specified in their documentation as being a problem regarding what the docker image and C compiler architecture that you use. For a quick fix, you can add the following line to your backend dockerfile.
```
RUN yarn add sharp --ignore-engines
```
This should solve the problem of sharp not knowing which type of compiler or architecture it is building for. For more information you can reference the sharp installation docs.

**Comment by ItzCrazyKns** [comment]
I'd recommend you to try the latest release, it should work as expected

**Comment by jiafu83** [comment]
Thanks all your guys for invaluable help. 
Unfortunately I found it's not the perplexica code issue, either 1.7.0 or the latest one is OK, it's the mainland China network issue...After I add 'proxy' args for backend part in docker-compose.yaml, the build is smooth. 
Now I face the same issue as https://github.com/ItzCrazyKns/Perplexica/issues/180

**Comment by hanjinxin** [comment]
@jiafu83  哈喽 这个代理是vpn还是适合中国宝宝的镜像源呢
