### ISSUE TITLE
Cannot access behind reverse proxy

### ISSUE THREAD

**Issue by overcuriousity** [ItzCrazyKns/Perplexica#241]
**Describe the bug**
I am unable to access the perplexica behind a nginx reverse proxy. The frontend loads, but not the backend (infinite loading). The browser produces the errors:

```
Blocked loading mixed active content “http://192.168.178.103:3001/api/models” 
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    NextJS 11
453-17320b85d95d59ad.js:1:28084
    ed NextJS
    AsyncFunctionThrow self-hosted:857
    NextJS 30
```

which is only the case if I access it via the domain name (which is locally resolved on my network) - if I access it via the IP directly, it works.

I tried to troubleshoot, it seems to have to do with CORS preventing mixed access to the endpoints.
Tried both the docker version as well as the nodeJS solution.

**Comment by overcuriousity** [comment]
Update:
I fixed it. In the env variables, configure
```
NEXT_PUBLIC_API_URL=https://<your_domain>
NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws 
```

and in the local nginx configuration, configure
```
server {
    listen 80;
    server_name <your_local_server_ip>;

    location / {
        proxy_pass http://<your_local_server_ip>:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /api {
        proxy_pass http://<your_local_server_ip>:3001/api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /ws {
        proxy_pass http://<your_local_server_ip>:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```
However, this could be made clear in the Documentation or streamlined in the application.
Configuring it was a pain.

Note that this works for my network, where a network-wide reverse proxy handles all SSL/TLS at the single point of entry.
The nginx config was also configured with the additional custom locations /ws and /api.

**Comment by overcuriousity** [comment]
reopened the issue in the hope the maintainer sees it. Keep up the great work of this exceptional project!

**Comment by ItzCrazyKns** [comment]
Hi, you only had to serve the backend of HTTPS. Yes, we can add it in the documentation but we cannot provide support for that (if someone faces an issue while doing so, they need to handle it themselves as if we start watching all these domain/networking errors then the real problems will be ignored). If you'd like, you can make a pull request to add this point in the [networking docs](https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md).

**Comment by overcuriousity** [comment]
Thats a good idea, I will do that.

**Comment by overcuriousity** [comment]
Could not reproduce, its still faulty and inconsitant. I think there should be a sophisticated solution configurable on the application layer. I tried to make a PR but I am not familiar enough with typescript and npm.

**Comment by getteq** [comment]
> Update: I fixed it. In the env variables, configure
> 
> ```
> NEXT_PUBLIC_API_URL=https://<your_domain>
> NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws 
> ```
> 
> and in the local nginx configuration, configure
> 
> ```
> server {
>     listen 80;
>     server_name <your_local_server_ip>;
> 
>     location / {
>         proxy_pass http://<your_local_server_ip>:3000;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
>     }
> 
>     location /api {
>         proxy_pass http://<your_local_server_ip>:3001/api;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
>     }
> 
>     location /ws {
>         proxy_pass http://<your_local_server_ip>:3001;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
>     }
> }
> ```
> 
> However, this could be made clear in the Documentation or streamlined in the application. Configuring it was a pain.
> 
> Note that this works for my network, where a network-wide reverse proxy handles all SSL/TLS at the single point of entry. The nginx config was also configured with the additional custom locations /ws and /api.

Today I tried this method and there is one tiny error, 
NEXT_PUBLIC_API_URL=https://<your_domain>/api
NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws 
is correct, not
NEXT_PUBLIC_API_URL=https://<your_domain>
NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws 
If you try to using this method use
NEXT_PUBLIC_API_URL=https://<your_domain>/api
NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws

**Comment by overcuriousity** [comment]
> > Update: I fixed it. In the env variables, configure
> > ```
> > NEXT_PUBLIC_API_URL=https://<your_domain>
> > NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and in the local nginx configuration, configure
> > ```
> > server {
> >     listen 80;
> >     server_name <your_local_server_ip>;
> > 
> >     location / {
> >         proxy_pass http://<your_local_server_ip>:3000;
> >         proxy_http_version 1.1;
> >         proxy_set_header Upgrade $http_upgrade;
> >         proxy_set_header Connection 'upgrade';
> >         proxy_set_header Host $host;
> >         proxy_cache_bypass $http_upgrade;
> >     }
> > 
> >     location /api {
> >         proxy_pass http://<your_local_server_ip>:3001/api;
> >         proxy_http_version 1.1;
> >         proxy_set_header Upgrade $http_upgrade;
> >         proxy_set_header Connection 'upgrade';
> >         proxy_set_header Host $host;
> >         proxy_cache_bypass $http_upgrade;
> >     }
> > 
> >     location /ws {
> >         proxy_pass http://<your_local_server_ip>:3001;
> >         proxy_http_version 1.1;
> >         proxy_set_header Upgrade $http_upgrade;
> >         proxy_set_header Connection 'upgrade';
> >         proxy_set_header Host $host;
> >         proxy_cache_bypass $http_upgrade;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, this could be made clear in the Documentation or streamlined in the application. Configuring it was a pain.
> > Note that this works for my network, where a network-wide reverse proxy handles all SSL/TLS at the single point of entry. The nginx config was also configured with the additional custom locations /ws and /api.
> 
> Today I tried this method and there is one tiny error, NEXT_PUBLIC_API_URL=https://<your_domain>/api NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws is correct, not NEXT_PUBLIC_API_URL=https://<your_domain> NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws If you try to using this method use NEXT_PUBLIC_API_URL=https://<your_domain>/api NEXT_PUBLIC_WS_URL=wss://<your_domain>/ws

Ah, thanks!
This is very helpful, as I struggled to reproduce in the meantime, but now I know why.

**Comment by satoshinotdead** [comment]
I can't get it working and tried a lot. Using a different domain on api, using the original subdomain of the app.

I was need to change the localhosts ports, if that can be a hardcoded issue or something else.

What can be wrong in order to use api, ws and front behind Nginx? Why is so hard to enable this way?

I have 30+ apps running without issues, with very similar architectures and really want to run Perplexica.

Thanks!

**Comment by Anaphylaxis** [comment]
The only thing that worked for me was removing the internal `perplexica-network` network and only having Traefik. The `app` only binds to the first interface it seems

**Comment by jagg2** [comment]
> The only thing that worked for me was removing the internal `perplexica-network` network and only having Traefik. The `app` only binds to the first interface it seems even with these changes and rebuilding the image

Thank you! Your comment lead to me sorting out way I was getting a gateway error.
Guess, it's order dependent. The traefik network has to be first. stack network second.
