### ISSUE TITLE
Mobile scaling

### ISSUE THREAD

**Issue by manjaroblack** [ItzCrazyKns/Perplexica#245]
**Describe the bug**
After entering a query and receiving the response, the web page is scaled (zoomed in?) incorrectly in portrait orientation. 

**To Reproduce**

1. Enter a query and search
2. The response is scaled wrong, see screenshot below

**Expected behavior**
After generating the response, the window should maintain correct scaling. 

**Screenshots**
![image](https://github.com/ItzCrazyKns/Perplexica/assets/42281273/f2eb5be8-899b-4e3d-a637-c6fa5e527837)

**Comment by ItzCrazyKns** [comment]
![localhost_3000_(iPhone SE)](https://github.com/ItzCrazyKns/Perplexica/assets/95534749/284f5515-a46d-4aa4-8aae-bb7c730043c3)

Not able to reproduce. Try refreshing the page that should fix the issue.
