### ISSUE TITLE
No way to add custom OpenAI endpoint?

### ISSUE THREAD

**Issue by Madvulcan** [ItzCrazyKns/Perplexica#250]
I am trying to use LM Studio as a server for Perplexica.

I looked at closed issues here [like this one](https://github.com/ItzCrazyKns/Perplexica/issues/117) and have seen that the instructions are to specify a custom OpenAI endpoint in the settings. However, in the settings, I do not see that option. This is with a fresh install.

![image](https://github.com/ItzCrazyKns/Perplexica/assets/40804776/e9bfd1bb-db6f-4a00-91dd-c664a757a66d)

![image](https://github.com/ItzCrazyKns/Perplexica/assets/40804776/1470e924-f15b-465c-a49f-50504cbcdef5)

As you can see from the screenshot, the option for a custom OpenAI endpoint seems to be missing. 

Was this option removed recently? I just installed Perplexica about an hour or so ago.

**Comment by ItzCrazyKns** [comment]
Hi, I changed how the providers were structured and forgot to add this provider. It should now be fixed by https://github.com/ItzCrazyKns/Perplexica/commit/3b4b8a8b0227cee590014f99e10aefd9e1176791, you just need to re-install and the patch will apply.

```sh
docker compose up -d --build
```

**Comment by Madvulcan** [comment]
![image](https://github.com/ItzCrazyKns/Perplexica/assets/40804776/9b675bfc-93a0-43d5-85d3-c63d180bd6de)

Updated; there is still no place to put in the OpenAI endpoint URL. And now 'Custom OpenAI' is the only option available from the dropdown; Ollama is now missing.
