### ISSUE TITLE
OpenAI Server settings not present and ollama option is missing

### ISSUE THREAD

**Issue by Madvulcan** [ItzCrazyKns/Perplexica#253]
![image](https://github.com/ItzCrazyKns/Perplexica/assets/40804776/9b675bfc-93a0-43d5-85d3-c63d180bd6de)

There is still no place to put in the OpenAI endpoint URL in settings. And now 'Custom OpenAI' is the only option available from the dropdown; Ollama is now missing.

_Originally posted by @Madvulcan in https://github.com/ItzCrazyKns/Perplexica/issues/250#issuecomment-2214431067_

**Comment by ItzCrazyKns** [comment]
Should be fixed by the latest commit, re-install Perplexica.

**Comment by omkamal** [comment]
I re-installed, and can't see the fix, still not fixed
