### ISSUE TITLE
settings: custom_openapi - Model name : undefined   -- Not saved when entered

### ISSUE THREAD

**Issue by quantumalchemy** [ItzCrazyKns/Perplexica#262]
**Describe the bug**
In settings: custom_openapi - Model name : undefined   -- Not saved when entered
everything else saved :
Custom OpenAI API Key - ok
Custom OpenAI Base URL - ok
Just --> Model name : undefined  - never saved

**To Reproduce**
click save button

**Comment by ItzCrazyKns** [comment]
> **Describe the bug** In settings: custom_openapi - Model name : undefined -- Not saved when entered everything else saved : Custom OpenAI API Key - ok Custom OpenAI Base URL - ok Just --> Model name : undefined - never saved
> 
> **To Reproduce** click save button

Did you ever add the model name into the model name field?

**Comment by quantumalchemy** [comment]
yeah obviously .. like 10 times ..saved always 'undefined ' I am going to reinstall (maybe a cache thing?) cant be the only one- thanks

**Comment by lichenke** [comment]
I also encountered the same situation

**Comment by Wongkitlong314** [comment]
same here. even remove the container and delete browser cache and cookie. the problem still exist.

**Comment by mcthesw** [comment]
same here. any solution?

**Comment by snowday365** [comment]
same here.

**Comment by ItzCrazyKns** [comment]
I'll try to reproduce.

**Comment by ItzCrazyKns** [comment]
Ok, turns out I forgot to handle the custom OpenAI provider separately while settings the model names that caused an issue. Additionally a hook in the select of the model provider also caused a similar issue. Both of them are no fixed.

## How to get the patch?

Re-clone Perplexica from Github and then run the following command:

```sh
docker compose up -d --build
```

Happy searching!
