### ISSUE TITLE
Sources listed as "How to rephrase questions"

### ISSUE THREAD

**Issue by onlyone-hyphen** [ItzCrazyKns/Perplexica#263]
Fresh install, docker, windows 11, nvidia rtx 4060 8Gb VRAM laptop, ollama llama3:latest 4bit
Copilot mode: Yes and No : Both give same behaviour

Search for "Attention is all you need"

Unexpected behaviour:
The sources are listed as "how to rephrase a question"
Clearly behind the scenes the model is trying to rephrase the question to get better answers
But these should not be listed as sources
Its getting is wires mixed up somehow

![image](https://github.com/user-attachments/assets/df6c7732-faf2-4181-8173-2f6d0c61d18b)

**Comment by rick-github** [comment]
This behaviour depends on the model.  Perplexica sends a query like "rephrase this question to maximize search results: {your prompt}" and the model responds with "The rephrased question is: {new question}" which is then used as the search query, so you get results about rephrasing questions.  As I recall, llama2/3 was particularly bad at this.  I think gemma2 and Qwen models are better in that they return just the rephrased question, but YMMV.

**Comment by ItzCrazyKns** [comment]
> This behaviour depends on the model. Perplexica sends a prompt like "rephrase this question to maximize search results: {your prompt}" and the model responds with "The rephrased question is: {new question}" which is then used as the search query, so you get results about rephrasing questions. As I recall, llama2/3 was particularly bad at this. I think gemma2 and Qwen models are better in that they return just the rephrased question, but YMMV.

I've tested it with various open source models (Llama3, Llama2, Gemma) and they seem to work fine, it might as well depend upon your query, I'd recommend you to rephrase your query (actually rephrase it) and try sending it to Perplexica again.
