### ISSUE TITLE
/Discover (404)

### ISSUE THREAD

**Issue by onlyone-hyphen** [ItzCrazyKns/Perplexica#264]
Fresh install, docker, windows 11

Clicking on the discover link, returns 404

![image](https://github.com/user-attachments/assets/36d8e2a6-2e2c-436e-93b4-ee4ce4f25d85)

**Comment by overcuriousity** [comment]
According to issue #208, The Discover Feature is not yet implemented and under Development.
I also don´t have it, and it is not yet present in the sourcecode.

**Comment by onlyone-hyphen** [comment]
> According to issue #208, The Discover Feature is not yet implemented and under Development. I also don´t have it, and it is not yet present in the sourcecode.

Okay, thank you
