### ISSUE TITLE
Error found incomptible module

### ISSUE THREAD

**Issue by WXCMYDEARMELAN** [ItzCrazyKns/Perplexica#270]
**use docker install Perplexica**

**Comment by WXCMYDEARMELAN** [comment]
![Snipaste_2024-07-15_15-20-47](https://github.com/user-attachments/assets/5da00869-b59c-4722-8af1-ca48bfe631fb)

**Comment by Zirgite** [comment]
Let's follow a detailed step-by-step approach that includes cleaning up Docker files and ensuring a fresh start for your Docker setup:

1. **Stop and Remove Docker Containers:**
   First, stop and remove any running Docker containers related to Perplexica.
   ```sh
   docker compose down
   ```

2. **Remove Docker Images and Volumes:**
   To ensure a clean setup, remove the existing Docker images and volumes.
   ```sh
   docker system prune -a --volumes
   ```

   This command will remove all unused containers, networks, images (both dangling and unreferenced), and optionally, volumes.


3. **Rebuild the Docker Image:**
   Rebuild the Docker image with the updated files.
   ```sh
   docker compose build
   ```

4. **Start the Docker Containers:**
   Start the Docker containers using the following command:
   ```sh
   docker compose up -d
   ```

6. **Verify the Update:**
   Access Perplexica at `http://localhost:3000` and check if the changes to the web writer agent are reflected.

**Comment by ItzCrazyKns** [comment]
> ![Snipaste_2024-07-15_15-20-47](https://private-user-images.githubusercontent.com/125426469/348627637-5da00869-b59c-4722-8af1-ca48bfe631fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTQ4NzksIm5iZiI6MTcyMTA1NDU3OSwicGF0aCI6Ii8xMjU0MjY0NjkvMzQ4NjI3NjM3LTVkYTAwODY5LWI1OWMtNDcyMi04YWYxLWNhNDhiZmU2MzFmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxNDQyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2EyYjQ1MDQzYWUwY2M4ZWQ1ZjQ0OTk3MjRhYzZjYmQ0MTVhMjhhY2NiY2UxMjc0MjdkYmJiNDkzM2YxNTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bNbYtVDVPjPnvyJ6h0nB0iISPp3-zeKx701P-QXOP5Y)

Try building the images again.

**Comment by Zirgite** [comment]
Maybe using as administrator windows powershell can also help. I also had occasions when docker did not work out on the first try.

**Comment by rqi14** [comment]
I built docker images with github actions. they work fine.
 
use my images https://github.com/rqi14/Perplexica-docker

**Comment by WXCMYDEARMELAN** [comment]
i used latest docker-compose ，but  its node version problemn ，just modify the node version
