### ISSUE TITLE
When entering the browser and spinning around, the sealxing in Docker keeps showing wikidata connection timeout

### ISSUE THREAD

**Issue by weizihao-ai** [ItzCrazyKns/Perplexica#274]
**Describe the bug**
docker searxng/searxng:  
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init
    jsonresponse = send_wikidata_query(query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query
    http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
    return request('get', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 97, in request
    raise httpx.TimeoutException('Timeout', request=None) from e
httpx.TimeoutException: Timeout
2024-07-19 06:34:01,225 ERROR:searx.engines.wikidata: Fail to initialize
Traceback (most recent call last):
  File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
    return future.result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init
    jsonresponse = send_wikidata_query(query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query
    http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
    return request('get', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 97, in request
    raise httpx.TimeoutException('Timeout', request=None) from e
httpx.TimeoutException: Timeout
**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/53d4e197-8b9c-4a40-aa5d-88bef9e36a69">
<img width="640" alt="image" src="https://github.com/user-attachments/assets/31838514-eacd-4e5b-ab91-9526c515cb5a">
<img width="656" alt="image" src="https://github.com/user-attachments/assets/8261084d-a2b0-4eab-bb0f-6b9e3ab37b6d">
<img width="862" alt="image" src="https://github.com/user-attachments/assets/b1596e68-f473-4f42-adec-987f7fd4ec30">

**Additional context**

**Comment by dgagf111** [comment]
I encountered similar issues when starting with docker-compose. hoping for a solution

**Comment by ItzCrazyKns** [comment]
> **Describe the bug** A clear and concise description of what the bug is. docker searxng/searxng: Traceback (most recent call last): File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize self.engine.init(get_engine_from_settings(self.engine_name)) File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init jsonresponse = send_wikidata_query(query) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/network/**init**.py", line 164, in get return request('get', url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/network/**init**.py", line 97, in request raise httpx.TimeoutException('Timeout', request=None) from e httpx.TimeoutException: Timeout 2024-07-19 06:34:01,225 ERROR:searx.engines.wikidata: Fail to initialize Traceback (most recent call last): File "/usr/local/searxng/searx/network/**init**.py", line 95, in request return future.result(timeout) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/concurrent/futures/_base.py", line 458, in result raise TimeoutError() TimeoutError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize self.engine.init(get_engine_from_settings(self.engine_name)) File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init jsonresponse = send_wikidata_query(query) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/network/**init**.py", line 164, in get return request('get', url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/network/**init**.py", line 97, in request raise httpx.TimeoutException('Timeout', request=None) from e httpx.TimeoutException: Timeout **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/176011432/350282978-53d4e197-8b9c-4a40-aa5d-88bef9e36a69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTkxOTgsIm5iZiI6MTcyMTM5ODg5OCwicGF0aCI6Ii8xNzYwMTE0MzIvMzUwMjgyOTc4LTUzZDRlMTk3LThiOWMtNGE0MC1hYTVkLTg4YmVmOWUzNmE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNDIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjBlMDcxYTBjZWQ5MjgxZGZkNmE0NzQzZDkxZWVjZDhjNGFlMjlhMmRhY2ZmOTM3MzkzODMyYmY2OGY5NGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cw7Nxjsh6WDYe4CbXxU9y7kdmDA0BkJZ_BUjzWRk0qY"> <img alt="image" width="640" src="https://private-user-images.githubusercontent.com/176011432/350283416-31838514-eacd-4e5b-ab91-9526c515cb5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTkxOTgsIm5iZiI6MTcyMTM5ODg5OCwicGF0aCI6Ii8xNzYwMTE0MzIvMzUwMjgzNDE2LTMxODM4NTE0LWVhY2QtNGU1Yi1hYjkxLTk1MjZjNTE1Y2I1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNDIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGVlOWY2M2M1Nzc3MzRmNmE5MGFmZjM0MzA1YTNiMTdjNjJjYzY5NjU1NmRlODI3NDZmNDhkN2ZmZTQwMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HihLoOA9S2LV0rvXZSCB7Ks622bnKpV9U7LAvR5Af_w"> <img alt="image" width="656" src="https://private-user-images.githubusercontent.com/176011432/350283439-8261084d-a2b0-4eab-bb0f-6b9e3ab37b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTkxOTgsIm5iZiI6MTcyMTM5ODg5OCwicGF0aCI6Ii8xNzYwMTE0MzIvMzUwMjgzNDM5LTgyNjEwODRkLWEyYjAtNGVhYi1iYjBmLTZiOWUzYWIzN2I2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNDIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmUzZjUwNWRmNjUwOWQ1MzUwYmMzZDdmZmZjMDg0YTM2NGViNWZhZGM1YjU0NmMzZGYzOWFmMzcwNjIzMzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aHhnwYcvcxN-gfeNZjF-8AqhL4eXEpFsCp99olQ8gPo"> <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/176011432/350283715-b1596e68-f473-4f42-adec-987f7fd4ec30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTkxOTgsIm5iZiI6MTcyMTM5ODg5OCwicGF0aCI6Ii8xNzYwMTE0MzIvMzUwMjgzNzE1LWIxNTk2ZTY4LWY0NzMtNGY0Mi1hZGVjLTk4N2Y3ZmQ0ZWMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNDIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmZiNzYxZjhlNWFjZTUxYzNiYTA1ZjVkMDhhMzllYmYxY2RkNDEyOTA5MjBkNzM1NmRmNjRhNTcwNzc1NTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NV8HsT8x0xY2rk1Hb7xyTPZZkYHfoDmUoG-YbJnyy18">
> 
> **Additional context** Add any other context about the problem here.

You didn't updated the ports correctly. You didn't updated the mapped port.

**Comment by LZBNCC** [comment]
> > **Describe the bug** A clear and concise description of what the bug is. docker searxng/searxng: Traceback (most recent call last): File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize self.engine.init(get_engine_from_settings(self.engine_name)) File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init jsonresponse = send_wikidata_query(query) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/network/**init**.py", line 164, in get return request('get', url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/network/**init**.py", line 97, in request raise httpx.TimeoutException('Timeout', request=None) from e httpx.TimeoutException: Timeout 2024-07-19 06:34:01,225 ERROR:searx.engines.wikidata: Fail to initialize Traceback (most recent call last): File "/usr/local/searxng/searx/network/**init**.py", line 95, in request return future.result(timeout) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/concurrent/futures/_base.py", line 458, in result raise TimeoutError() TimeoutError
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize self.engine.init(get_engine_from_settings(self.engine_name)) File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init jsonresponse = send_wikidata_query(query) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/network/**init**.py", line 164, in get return request('get', url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/searxng/searx/network/**init**.py", line 97, in request raise httpx.TimeoutException('Timeout', request=None) from e httpx.TimeoutException: Timeout **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Screenshots** If applicable, add screenshots to help explain your problem. <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/176011432/350282978-53d4e197-8b9c-4a40-aa5d-88bef9e36a69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTkxOTgsIm5iZiI6MTcyMTM5ODg5OCwicGF0aCI6Ii8xNzYwMTE0MzIvMzUwMjgyOTc4LTUzZDRlMTk3LThiOWMtNGE0MC1hYTVkLTg4YmVmOWUzNmE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNDIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjBlMDcxYTBjZWQ5MjgxZGZkNmE0NzQzZDkxZWVjZDhjNGFlMjlhMmRhY2ZmOTM3MzkzODMyYmY2OGY5NGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cw7Nxjsh6WDYe4CbXxU9y7kdmDA0BkJZ_BUjzWRk0qY"> <img alt="image" width="640" src="https://private-user-images.githubusercontent.com/176011432/350283416-31838514-eacd-4e5b-ab91-9526c515cb5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTkxOTgsIm5iZiI6MTcyMTM5ODg5OCwicGF0aCI6Ii8xNzYwMTE0MzIvMzUwMjgzNDE2LTMxODM4NTE0LWVhY2QtNGU1Yi1hYjkxLTk1MjZjNTE1Y2I1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNDIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGVlOWY2M2M1Nzc3MzRmNmE5MGFmZjM0MzA1YTNiMTdjNjJjYzY5NjU1NmRlODI3NDZmNDhkN2ZmZTQwMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HihLoOA9S2LV0rvXZSCB7Ks622bnKpV9U7LAvR5Af_w"> <img alt="image" width="656" src="https://private-user-images.githubusercontent.com/176011432/350283439-8261084d-a2b0-4eab-bb0f-6b9e3ab37b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTkxOTgsIm5iZiI6MTcyMTM5ODg5OCwicGF0aCI6Ii8xNzYwMTE0MzIvMzUwMjgzNDM5LTgyNjEwODRkLWEyYjAtNGVhYi1iYjBmLTZiOWUzYWIzN2I2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNDIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmUzZjUwNWRmNjUwOWQ1MzUwYmMzZDdmZmZjMDg0YTM2NGViNWZhZGM1YjU0NmMzZGYzOWFmMzcwNjIzMzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aHhnwYcvcxN-gfeNZjF-8AqhL4eXEpFsCp99olQ8gPo"> <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/176011432/350283715-b1596e68-f473-4f42-adec-987f7fd4ec30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTkxOTgsIm5iZiI6MTcyMTM5ODg5OCwicGF0aCI6Ii8xNzYwMTE0MzIvMzUwMjgzNzE1LWIxNTk2ZTY4LWY0NzMtNGY0Mi1hZGVjLTk4N2Y3ZmQ0ZWMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNDIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmZiNzYxZjhlNWFjZTUxYzNiYTA1ZjVkMDhhMzllYmYxY2RkNDEyOTA5MjBkNzM1NmRmNjRhNTcwNzc1NTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NV8HsT8x0xY2rk1Hb7xyTPZZkYHfoDmUoG-YbJnyy18">
> > **Additional context** Add any other context about the problem here.
> 
> You didn't updated the ports correctly. You didn't updated the mapped port.

I have the same issue, I want to know how and where to update the ports and the mapped port correctly. I may not have understood.
