### ISSUE TITLE
How to use GT-4o-mini as Chat Model?

### ISSUE THREAD

**Issue by Jiuzhouh** [ItzCrazyKns/Perplexica#275]
How to use GT-4o-mini as Chat Model? Also, when you will release the API end point of Perplexica?

**Comment by ItzCrazyKns** [comment]
Added in the latest release. API endpoint is under development, will be released in the future releases

**Comment by Jiuzhouh** [comment]
Thanks for your release. Why I still can't see the GPT-4o-mini option even after I pull the new code? 
What I did is:
1. Pull the new codes
2. run `docker compose up -d`

Anything need to change?

**Comment by ItzCrazyKns** [comment]
`docker compose up -d --build`
