### ISSUE TITLE
Provide an official Docker image

### ISSUE THREAD

**Issue by Banbury** [ItzCrazyKns/Perplexica#276]
**Is your feature request related to a problem? Please describe.**
I am sure, this is a nice project, but I am not going to build my own Docker image, just to try it. 

**Describe the solution you'd like**
Please provide an official Docker image on Docker Hub.

**Describe alternatives you've considered**
The alternative, is, that I'm not using Perplexica.

**Additional context**
https://docs.docker.com/docker-hub/quickstart/

**Comment by ItzCrazyKns** [comment]
https://github.com/ItzCrazyKns/Perplexica/pull/231#issuecomment-2199232067
