### ISSUE TITLE
How to Keep Docker Installation Up-to-Date

### ISSUE THREAD

**Issue by lubuwei001** [ItzCrazyKns/Perplexica#277]
After installing using Docker, how can the project be updated? 

Is it necessary to RE-clone the latest repository and then RE-run `$ docker compose up -d`?

**Comment by delfireinoso** [comment]
You can try a Docker Image installation 

https://github.com/ItzCrazyKns/Perplexica/discussions/271

**Comment by Stumie** [comment]
There's a markdown file, that describes how to update: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/UPDATING.md
