### ISSUE TITLE
Perpexica not fully loading for devices on the local network

### ISSUE THREAD

**Issue by Madvulcan** [ItzCrazyKns/Perplexica#278]
Perplexica is running fine on my desktop machine, but when I try to access it across the network from other devices, the interface will not fully load, and instead displays a spinning circle:

![image](https://github.com/user-attachments/assets/00b3fafe-6abf-4fe1-b7a3-4add15cf089a)

The instance of SearxNG loads fine on those same devices:

![image](https://github.com/user-attachments/assets/bac1a178-bdf4-4493-801a-4fb9b862651d)

I have tested with three laptops and my mobile phone, same result with all of them. Perplexica is accessible, it just won't fully load for some reason. I don't know why it would work differently across the local network versus accessed via localhost on the host machine, but then I'm not very well versed in networking.

Any ideas? Are others here able to use Perplexica across a local network?

**Comment by ItzCrazyKns** [comment]
https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md

**Comment by Bolex80** [comment]
Same issue here,
I even tried exposing it via Nginx Proxy manager and on my laptop or desktop it works perfectly well. Using local network using the 192.168.x.x works fine, as long as it is a regular "big" computer.  But on mobile devices, with various brands and various browsers (all of them actually) it simply wont work.
Its really weird.

**Comment by Bolex80** [comment]
I found my own solution, it is already described in this link:
https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md

It is important to remember that you need to rebuild the docker file. 
Pay attention to running the docker compose up command like this: docker compose up -d --build

Also, I saw this comment, that it is a good idea to also edit the network address here: 
https://github.com/ItzCrazyKns/Perplexica/blob/dfb532e4d3c293664f6d61cf6ff0e540377226fa/app.dockerfile

These changes worked for me. 
It is now accessible on LAN
