### ISSUE TITLE
Frontend cannot access model list from the backend

### ISSUE THREAD

**Issue by nguyentran0212** [ItzCrazyKns/Perplexica#283]
**Describe the bug**
Frontend shows "No chat models available" error. Upon inspections in the browser, I find that get request to `http://127.0.0.1:3001/api/model` has 403 error (see screenshots)

**To Reproduce**

1. Install Perplexica in docker according to the instruction in README. 
2. Open localhost:3000

**Expected behavior**
Perplexica is usable.

**Screenshots**

403 error from front-end:

<img width="1725" alt="Screenshot 2024-07-24 at 5 18 08 pm" src="https://github.com/user-attachments/assets/fc0ac692-0551-4299-a72c-1521d4fbf773">

Response from api/model at 127.0.0.1:3001 (Ollama model was found correctly)

<img width="1726" alt="Screenshot 2024-07-24 at 5 20 57 pm" src="https://github.com/user-attachments/assets/d6612bf2-7ac0-4089-b3fd-293e85864171">

**Additional context**

Running on MacOS.

**Comment by ItzCrazyKns** [comment]
What can you see at http://127.0.0.1:3001

**Comment by hanjinxin** [comment]
@ItzCrazyKns  我也遇到了相同的问题，

**Comment by hanjinxin** [comment]
@ItzCrazyKns  I also encountered the same problem
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/e78e27b2-b3d3-462f-bfa4-9146643065f6">
and  backend  logs, is it a problem with my proxy or the openai key

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/ab217185-a98f-41d4-9c82-db4fe0f0097c">

**Comment by nguyentran0212** [comment]
@ItzCrazyKns at 127.0.0.1:3001, I see `Cannot GET /`

**Comment by ItzCrazyKns** [comment]
> @ItzCrazyKns at 127.0.0.1:3001, I see `Cannot GET /`

http://127.0.0.1:3001/api/models

**Comment by ItzCrazyKns** [comment]
> @ItzCrazyKns I also encountered the same problem <img alt="image" width="1346" src="https://private-user-images.githubusercontent.com/84846539/351638578-e78e27b2-b3d3-462f-bfa4-9146643065f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Njk5NjMsIm5iZiI6MTcyMTg2OTY2MywicGF0aCI6Ii84NDg0NjUzOS8zNTE2Mzg1NzgtZTc4ZTI3YjItYjNkMy00NjJmLWJmYTQtOTE0NjY0MzA2NWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAxMDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YzYwNzQ5MmZhODY1YzExZTM4MWI4YzE5ODBmNGIwMGI0MmY1MmVhNzA5MjAxZjYyNDA4MDMxMTc1Y2Q3YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ICS71Z9n6p3zltEyJD9PVY9QernJ_dm9dNeFM-OjGds"> and backend logs, is it a problem with my proxy or the openai key
> 
> <img alt="image" width="1142" src="https://private-user-images.githubusercontent.com/84846539/351639876-ab217185-a98f-41d4-9c82-db4fe0f0097c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Njk5NjMsIm5iZiI6MTcyMTg2OTY2MywicGF0aCI6Ii84NDg0NjUzOS8zNTE2Mzk4NzYtYWIyMTcxODUtYTk4Zi00MWQ0LTljODItZGI0ZmUwZjAwOTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAxMDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwODczYWJhYjZmYzliOGQ2ZTU3MWVhZjg0NDkzMTc0ODY0YmI5OWZhZWMxNGY4MzAyY2RiNjJkNTg2OGY2ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aD4c0knLU2NcnqbpIo090MYCFPacAFcQ4BkoTOAORzM">

Are you using custom OpenAI or just normal OpenAI provider? The error is unrelated to Perplexica, seems with an issue with your configuration

**Comment by nguyentran0212** [comment]
> > @ItzCrazyKns at 127.0.0.1:3001, I see `Cannot GET /`
> 
> http://127.0.0.1:3001/api/models

<img width="1725" alt="Screenshot 2024-07-24 at 5 18 15 pm" src="https://github.com/user-attachments/assets/74d48c51-0cb9-4648-8414-d4251683dc58">

I use Ollama. The backend gets the correct model from my Ollama, but it seems that front-end cannot communicate with backend via 127.0.0.1. 

I tested with both safari and chrome. 

My device is MacBook Pro M1 running on MacOS 14.3.1.

Firewall is disabled on my MacBook.

**Comment by hanjinxin** [comment]
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/b7a90711-d662-4f1f-9c2e-d68deff674a6">

Boss, may I ask a question? Due to network restrictions on my server, I am unable to access SearxNG. I would like to perform front-end and back-end separation. I understand that we are divided into four parts: front-end and back-end, SearxNG, and model services. I understand that as long as SearxNG has a VPN network, it can be used normally. Now I have two environments. Mac can use perlexity to search normally, but my Linux is not working. The above is my configuration. My Olama saw that there was a call, but the backend logs @ItzCrazyKns 
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/3ad220be-1d1f-44c4-ab6e-0b41e68ac80f">

**Comment by hanjinxin** [comment]
前后端我已经成功了，但是在linux上的服务 还是不稳定，就输出过一次，剩下都是timeout

**Comment by ItzCrazyKns** [comment]
> > > @ItzCrazyKns at 127.0.0.1:3001, I see `Cannot GET /`
> > 
> > 
> > http://127.0.0.1:3001/api/models
> 
> <img alt="Screenshot 2024-07-24 at 5 18 15 pm" width="1725" src="https://private-user-images.githubusercontent.com/13358376/351939595-74d48c51-0cb9-4648-8414-d4251683dc58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTc1NDYsIm5iZiI6MTcyMTkxNzI0NiwicGF0aCI6Ii8xMzM1ODM3Ni8zNTE5Mzk1OTUtNzRkNDhjNTEtMGNiOS00NjQ4LTg0MTQtZDQyNTE2ODNkYzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE0MjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNTFhNTY5YjIxZmQxODQ0YzA2NWUwMDQwNzk0OWNmZGNiZDkwZmUwN2JkMDA2ZDEyMzM4NTdlYjQ3ZGZmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yU7NFclP4A2PQjlgi4utjqO1V6gYV4r0_l2YkUXEdX0">
> I use Ollama. The backend gets the correct model from my Ollama, but it seems that front-end cannot communicate with backend via 127.0.0.1.
> 
> I tested with both safari and chrome.
> 
> My device is MacBook Pro M1 running on MacOS 14.3.1.
> 
> Firewall is disabled on my MacBook.

That's strange can you try re-install Perplexica or provide me with the exact steps so I can try to reproduce?

**Comment by ItzCrazyKns** [comment]
> <img alt="image" width="1008" src="https://private-user-images.githubusercontent.com/84846539/352047192-b7a90711-d662-4f1f-9c2e-d68deff674a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTc1NDcsIm5iZiI6MTcyMTkxNzI0NywicGF0aCI6Ii84NDg0NjUzOS8zNTIwNDcxOTItYjdhOTA3MTEtZDY2Mi00ZjFmLTljMmUtZDY4ZGVmZjY3NGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE0MjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYjE4YTllZTBlYjhjZGMwZjFlNTZiYmE5ZjViOTYxMTcxZjlhMjY4NmFiZmJjMzJhYWZjNjEyMjBkY2FmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z9Uc2LAC-BcObli-iVRENS3m75jMhD3--B3cjwTXTjk">
> Boss, may I ask a question? Due to network restrictions on my server, I am unable to access SearxNG. I would like to perform front-end and back-end separation. I understand that we are divided into four parts: front-end and back-end, SearxNG, and model services. I understand that as long as SearxNG has a VPN network, it can be used normally. Now I have two environments. Mac can use perlexity to search normally, but my Linux is not working. The above is my configuration. My Olama saw that there was a call, but the backend logs @ItzCrazyKns <img alt="image" width="1179" src="https://private-user-images.githubusercontent.com/84846539/352049103-3ad220be-1d1f-44c4-ab6e-0b41e68ac80f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTc1NDcsIm5iZiI6MTcyMTkxNzI0NywicGF0aCI6Ii84NDg0NjUzOS8zNTIwNDkxMDMtM2FkMjIwYmUtMWQxZi00NGM0LWFiNmUtMGI0MWU2OGFjODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE0MjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MGZlMmUzNDE4Y2E5ZDEzMjA3NWM5MzU4YmMxZTM4N2ZjY2ExYWQ0MTFhY2RhNGM0NmQzYmUyYWIxYzQ0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CYDJaABf7WWzacpbYlalY2N_cr9ga0-g7ashmsxBMks">

Can you try sending doing a curl request to the same address that you're using for Ollama in the same computer as Perplexica.

```sh
curl <address>
```

**Comment by nguyentran0212** [comment]
@ItzCrazyKns Hi, sorry for the late response. I pulled the latest version from GitHub 5 minutes ago and run `docker compose up -d` again. This time it works. There were 4 new commits pulled, so I guess some of them did the trick.
