### ISSUE TITLE
no reason is shown when Rate limit are reached for model

### ISSUE THREAD

**Issue by calathus** [ItzCrazyKns/Perplexica#286]
**Describe the bug**
when we use perplaxica, it suddenly stop working.
When I checked the console of backend, it showed the reason is it reached the limit.
This kind of error is normal error, and it should be reported to user so that user can take appropriate action.

this is associated with Groq API.(but other provider may have similar issue.)

**To Reproduce**
Just keep using with llama-3.1-70b-versatile model, sonner or later, this error will appear,i.e. sudden failure.
then if we check the console of backend, there are error message.

**Expected behavior**
it should open modal window telling:
"Rate limit exceeded: The model has reached its maximum allowed requests for this organization. Please try again in approximately 28.5 seconds or consider increasing the rate limit. For more information on rate limits, please visit https://console.groq.com/docs/rate-limits."

**Screenshots**

**Additional context**
github/Perplexica/node_modules/openai/src/error.ts:94
      return new RateLimitError(status, error, message, headers);
             ^
RateLimitError: 429 Rate limit reached for model `llama-3.1-70b-versatile` in organization `org_01hwfxvcjjec7aedtphfrna6zz` on : Limit 131072, Used 130385, Requested 731. Please try again in 28.542992187s. Visit https://console.groq.com/docs/rate-limits for more information.
    at Function.generate (/home/calathus/github/Perplexica/node_modules/openai/src/error.ts:94:14)
    at OpenAI.makeStatusError (/home/calathus/github/Perplexica/node_modules/openai/src/core.ts:397:21)
    at OpenAI.makeRequest (/home/calathus/github/Perplexica/node_modules/openai/src/core.ts:460:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/calathus/github/Perplexica/node_modules/@langchain/openai/dist/chat_models.cjs:684:29
    at async RetryOperation._fn (/home/calathus/github/Perplexica/node_modules/p-retry/index.js:50:12) {
  status: 429,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8a972ddc6a7a69d4-PDX',
    connection: 'keep-alive',
    'content-length': '319',
    'content-type': 'application/json',
    date: 'Fri, 26 Jul 2024 20:35:57 GMT',
    'retry-after': '29',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=3ZEehUbKKWVmfQe.Og3G76nJ8bFrRMznKyEjasVnBEE-1722026157-1.0.1.1-PN2uTXfBuOT_xgaczlPAs8xL.rq78FkUYqNkbAbaNT1F9zkabdTNidzPoeGzcRn1C7j_EwrL2r.Rx7ppxdZQaA; path=/; expires=Fri, 26-Jul-24 21:05:57 GMT; domain=.groq.com; HttpOnly; Secure; SameSite=None',
    vary: 'Origin',
    via: '1.1 google',
    'x-ratelimit-limit-requests': '14400',
    'x-ratelimit-limit-tokens': '131072',
    'x-ratelimit-remaining-requests': '14400',
    'x-ratelimit-remaining-tokens': '131072',
    'x-ratelimit-reset-requests': '0s',
    'x-ratelimit-reset-tokens': '0s',
    'x-request-id': 'req_01j3rc3sepf6as48myc7cxqw16'
  },
  request_id: 'req_01j3rc3sepf6as48myc7cxqw16',
  error: {
    message: 'Rate limit reached for model `llama-3.1-70b-versatile` in organization `org_01hwfxvcjjec7aedtphfrna6zz` on : Limit 131072, Used 130385, Requested 731. Please try again in 28.542992187s. Visit https://console.groq.com/docs/rate-limits for more information.',
    type: '',
    code: 'rate_limit_exceeded'
  },
  code: 'rate_limit_exceeded',
  param: undefined,
  type: '',
  attemptNumber: 7,
  retriesLeft: 0
}

**Comment by ItzCrazyKns** [comment]
Now with the latest RC release the application will not crash
