### ISSUE TITLE
Prebuilt docker images?

### ISSUE THREAD

**Issue by rcarmo** [ItzCrazyKns/Perplexica#298]
**Is your feature request related to a problem? Please describe.**
I'm a bit tired of doing manual checkouts and updates, and the upgrade process is slow. 

**Describe the solution you'd like**
I'd much prefer to have official Docker images I could just get into Portainer. They could be hosted in ghcr.io and built automatically using GitHub actions.

**Describe alternatives you've considered**
Doing my own or using a third-party fork (all of which lag behind the main project)

**Comment by ItzCrazyKns** [comment]
Refer to https://github.com/ItzCrazyKns/Perplexica/pull/231

**Comment by rqi14** [comment]
Check my solution
https://github.com/rqi14/Perplexica-docker
https://github.com/rqi14/Perplexica-docker/tree/readme
