### ISSUE TITLE
using repocloud deploy I inserted my OPEN_API_KEY but I want to use GROQ and I can't figure out how

### ISSUE THREAD

**Issue by zenitogr** [ItzCrazyKns/Perplexica#299]
**Describe the bug**
deploying on repocloud asks for OPEN_API_KEY which I provided but I am not on billing
want to use GROQ but:
I set GROQ_API_KEY in settings
I set GROQ_API_KEY in env variables
but when I run a question I get error and perplexica stops working, I cannot access settings either
**To Reproduce**

1. Go to perplexica github page
2. Click on 'repocloud deploy'
3. put username password and OPEN_API_KEY
4. no openai billing so off course it doesnt work (seen it in logs)
5. put env variable GROQ_API_KEY again doesnt work
6. put custom openai_custom in settings and api key my groq api key and model a groq model
7. when asking a question again stops responding and I guess it uses OPEN_API_KEY instead of GROQ

**Expected behavior**
with GROQ_API_KEY set it should use groq

**Comment by ItzCrazyKns** [comment]
> **Describe the bug** deploying on repocloud asks for OPEN_API_KEY which I provided but I am not on billing want to use GROQ but: I set GROQ_API_KEY in settings I set GROQ_API_KEY in env variables but when I run a question I get error and perplexica stops working, I cannot access settings either **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to perplexica github page
> 2. Click on 'repocloud deploy'
> 3. put username password and OPEN_API_KEY
> 4. no openai billing so off course it doesnt work (seen it in logs)
> 5. put env variable GROQ_API_KEY again doesnt work
> 6. put custom openai_custom in settings and api key my groq api key and model a groq model
> 7. when asking a question again stops responding and I guess it uses OPEN_API_KEY instead of GROQ
> 
> **Expected behavior** with GROQ_API_KEY set it should use groq

The repocloud team maintains the project there (I guess) so I don't have access to how it works. You don't need to set any environment variables, you can put an openai api key in the starting and then open settings and add your groq key, remove the openai key and select groq from the provider.
