### ISSUE TITLE
Add Ollama support

### ISSUE THREAD

**Issue by arsaboo** [ItzCrazyKns/Perplexica#3]
Any timeline for Ollama support....thanks!

**Comment by ItzCrazyKns** [comment]
Hey, its on the todo list and will be added pretty soon.

**Comment by ItzCrazyKns** [comment]
I created another branch just for Ollama. You can try cloning and testing it out:

```sh
git clone -b feat/ollama-support https://github.com/ItzCrazyKns/Perplexica.git
```

**Comment by arsaboo** [comment]
@ItzCrazyKns Thanks for the addition. Ollama is working with this branch. 

One feature that would be useful (maybe for a subsequent PR) is to get the list of models from Ollama and use a dropdown to let users pick the model dynamically instead of configuring one model in the `.env`.

**Comment by ItzCrazyKns** [comment]
The settings page is in development and will be added pretty soon.

**Comment by ItzCrazyKns** [comment]
Hi @syddharth, please make sure Ollama is running on that port (11434) if not update the url in the `.env` file and rebuild the images. I am working on a config page so it will be done instantly and won't need images to be rebuilt in the future.

**Comment by ItzCrazyKns** [comment]
As I can see you are using Ollama from `127.0.0.1:11434` and the `127.0.0.1` IP is only accessible to that particular computer and won't be accessible inside Docker. Replace it to `http://localhost:11434` and it should work as expected

**Comment by ItzCrazyKns** [comment]
Please read my message carefully, Docker runs its container in an isolated environment and hence 127.0.0.1 for Docker would be something else. But the localhost URL I suggested would be the same

**Comment by ItzCrazyKns** [comment]
You need to delete the previous images and build new images. As stated above, a settings page is under development that would help to prevent building things multiple time just for chainging.

**Comment by ItzCrazyKns** [comment]
It should be `OLLAMA_URL=http://localhost:11434` instead of `OLLAMA_HOST`

**Comment by ItzCrazyKns** [comment]
Hey everyone, Perplexica now fully supports Ollama. You can read more in the readme file https://github.com/ItzCrazyKns/Perplexica. The settings page is nearly done and will be released pretty soon so changing configuration at runtime can be possible as well
