### ISSUE TITLE
Option to use OpenRouter Models

### ISSUE THREAD

**Issue by PierrunoYT** [ItzCrazyKns/Perplexica#300]
**Is your feature request related to a problem? Please describe.**
Option to use OpenRouter Models

**Describe the solution you'd like**
Option to use OpenRouter Models

**Describe alternatives you've considered**

**Additional context**

**Comment by ItzCrazyKns** [comment]
Open router supports OpenAI API format so you can use it via custom OpenAI provider.

**Comment by shaggy2626** [comment]
> How can I do this?

set the customer openAI base url to `https://openrouter.ai/api/v1`
