### ISSUE TITLE
OpenAI Base_url and Model Definition

### ISSUE THREAD

**Issue by warlockedward** [ItzCrazyKns/Perplexica#301]
**Is your feature request related to a problem? Please describe.**

When nothing but defining openai's base_url as well as model definitions makes me feel very frustrated because of the way I use openai to run the local big-usage VLLMs.

**Describe the solution you'd like**

I would like to additionally define openai_base_url and model_name, making it possible for me to self-select which model to use for the service

**Describe alternatives you've considered**

**Additional context**

**Comment by ItzCrazyKns** [comment]
Invalid context
