### ISSUE TITLE
Change promt system

### ISSUE THREAD

**Issue by nathan-skynet** [ItzCrazyKns/Perplexica#302]
I'm looking for a simple way to change Perplexica's default language, meaning I'd like to receive direct responses in French without having to rephrase the question. 
The simplest solution would be the ability to change the system prompt directly in the application settings.
 Is there a file where I can configure the prompt, or am I forced to modify it directly in llama.cpp ?

**Comment by nathan-skynet** [comment]
modify src/agent/webSearchAgent.ts and add "You reply only in french"

**Comment by ItzCrazyKns** [comment]
Same as https://github.com/ItzCrazyKns/Perplexica/issues/72
