### ISSUE TITLE
Discover page not found

### ISSUE THREAD

**Issue by AxelFooley** [ItzCrazyKns/Perplexica#304]
**Describe the bug**
Freshly installed, discover page results in a 404
**To Reproduce**

1. Install using docker
2. visit home page
3. click on discover page icon
4. enjoy the 404 error page

**Expected behavior**
Discover page works and it's showing up some content

**Screenshots**
N/A

**Additional context**
None

**Comment by Pixelycia** [comment]
yep, because it's not implemented, check Readme.md
