### ISSUE TITLE
Failed to connect to server a few seconds after any search

### ISSUE THREAD

**Issue by AxelFooley** [ItzCrazyKns/Perplexica#305]
**Describe the bug**
I am using docker compose to run Perplexica, search is working fine but after a few seconds upon every search the page refresh itself and shows "Failed to connect to the server. Please try again later."
No errors on browser console, no errors from the containers.

**To Reproduce**

1. Clone repo
2. set NEXT_PUBLIC_API_URL and NEXT_PUBLIC_WS_URL in docker-compose.yml
3. set api keys and in config.toml
4. run docker compose up
5. do any search and wait a few seconds

**Expected behavior**
The result of the search stays on screen

**Screenshots**
![image](https://github.com/user-attachments/assets/1f749d27-0c80-4681-b330-02cc68c4cc82)

**Additional context**
I am running Perplexica on my home server and it's being used by ma lan clients. So my NEXT_PUBLIC_API_URL, NEXT_PUBLIC_WS_URL are set to my internal domain.

**Comment by ItzCrazyKns** [comment]
Can you check the browser console and see if it closes the connection

**Comment by ItzCrazyKns** [comment]
Hi, I just pushed a commit that fixes this issue, please reclone the project from Github and rebuild images via

`docker compose up -d --build`

**Comment by antistereov** [comment]
I have the same problem with the latest version of the repository. The browser console shows the message: [DEBUG] closed.
There are no other logs in the browser console as well as in all docker containers.

*Additional context*
I'm also running Perplexica on my home server.

**Comment by papiche** [comment]
It also happens to me regularly.
Just wait in front of the prompt and after a while "Failed to connect to server" appears
![Capture d’écran du 2024-09-25 11-57-39](https://github.com/user-attachments/assets/a8f6814e-e2e1-4224-8e97-6b402871fe71)

In console, i can see a 404 when accessing ```https://perplexica.at.home/discover?_rsc=acgkz```

In Network, last request is a "protocol switch" 101
```
GET /?chatModel=llama3.1%3Alatest&chatModelProvider=ollama&embeddingModel=llama3.1%3Alatest&embeddingModelProvider=ollama HTTP/1.1
Host: perplexicapi.at.home
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br, zstd
Sec-WebSocket-Version: 13
Origin: https://perplexica.at.home
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: l7/fyMHT/H8/0UOi4P2++w==
DNT: 1
Connection: keep-alive, Upgrade
Cookie: rl_session=RudderEncrypt%3AU2FsdGVkX18t7%2FREcOWO4PvwpX5dATkMGtZgxbaRUhywwx6hilB5AUcKpjschuZcjQjiDtyhx9FHiAjGLlrmnREuStYEwFd67XBQoV%2Fj%2BfHUKHFB4S4bvjD5waYBdyNliNv4CdD1KKOOGDnV4h0Wrg%3D%3D; rl_anonymous_id=RudderEncrypt%3AU2FsdGVkX1%2Bo7zdetmFDmGks%2B8QHRPrUL1K8pjsznAVrmNLtL6APBFOx7dtgDZU%2B4WUXlTHFg3tB5koWdWntLg%3D%3D; rl_page_init_referrer=RudderEncrypt%3AU2FsdGVkX19AlkgDwJi6wDXlFUzSPwh8NgQ8xgxPmCLyxM84t40a%2FuKqukjcPyK6; rl_page_init_referring_domain=RudderEncrypt%3AU2FsdGVkX1%2FFeJkEUcSmC48SDEszq%2FmELgtN5pT92rigRloFmG%2BEvRbXCSmx3Rz9; ph_phc_4URIAm1uYfJO7j8kWSe0J8lc8IqnstRLS7Jx8NcakHo_posthog=%7B%22distinct_id%22%3A%22f85477d4364bf27e078eae4790bed442db07a0421c6557dd2883173d195810a0%23af4ec013-fe45-4cad-8f20-d5ed0525a7ed%22%2C%22%24sesid%22%3A%5B1726536524590%2C%220191fd73-55df-7044-9555-1fd813bc64bf%22%2C1726534079967%5D%2C%22%24epp%22%3Atrue%7D
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: same-site
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

In case it helps investigating the problem
