### ISSUE TITLE
Backend connection error

### ISSUE THREAD

**Issue by AxelFooley** [ItzCrazyKns/Perplexica#308]
**Describe the bug**
All of a sudden the backend stopped working, no changes made.
Error from backend container:

[`perplexica-backend-1   | error: Unhandled Rejection at: [object Promise], reason: Error: Connection error.']
**To Reproduce**
Not sure what to suggest here, since no changes have been made, i just ran a search and Perplexica wouldn't give me an answer (spinning icon on screen for several minutes).

**Expected behavior**
search works

**Screenshots**
![image](https://github.com/user-attachments/assets/a5bac43f-e6c7-4bf1-8772-370e2f5db2c3)

**Additional context**

**Comment by AxelFooley** [comment]
After attempting a reddit search, that worked, and then switching back to a regular All search, the issue disappeared. No more errors and the search is working again (for now).

**Comment by Encounter005** [comment]
Can you explain in detail how you solved this problem, i still get this error 
![image](https://github.com/user-attachments/assets/28d104d8-af63-4a51-863c-7b01ee90bb94)
