### ISSUE TITLE
Home page giving spinner but nothing else when using nginx reverse proxy

### ISSUE THREAD

**Issue by michaelcalvinwood** [ItzCrazyKns/Perplexica#318]
**Describe the bug**
The home page gives the spinner and nothing else when using nginx reverse proxy.

**To Reproduce**
I installed docker on Ubuntu 22.04
I install Perplexica using the docker method and added my openAI key to the toml file.
Here's my nginx reverse proxy settings.
`
server {
    listen 80;
    server_name perplexica.ragfix.ai;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name perplexica.ragfix.ai;

    ssl_certificate /etc/letsencrypt/live/perplexica.ragfix.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/perplexica.ragfix.ai/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`

**Expected behavior**
I expected to be able to use Perplexica via https://perplexica.ragfix.ai.
<img width="1525" alt="Screenshot 2024-08-16 at 1 10 16 PM" src="https://github.com/user-attachments/assets/f850fca4-81a5-4477-b12d-cc30241b387d">

**Screenshots**
Screenshot attached.

**Comment by bpawnzZ** [comment]
https://github.com/ItzCrazyKns/Perplexica/discussions/271


i confirm this works!

**Comment by Expro** [comment]
Overall, current architecture make it unhostable for external access - communication between services needs to be both publicly available and unencrypted.

**Comment by ItzCrazyKns** [comment]
Reclone the project from Github, I did some changes and follow the networking guide: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md
