### ISSUE TITLE
Publish images to public container registries

### ISSUE THREAD

**Issue by Expro** [ItzCrazyKns/Perplexica#320]
**Is your feature request related to a problem? Please describe.**
Currently, to use container image you need to build (compose) it every time.

**Describe the solution you'd like**
Build and publish images to public registries such as hub.docker.com.

**Comment by Froggy232** [comment]
Hello,
I would love to have public image too, as I use podman with podlet and it doesn't support building image yet.
Is there a possibility to see this in near future?
Thanks you!

**Comment by ItzCrazyKns** [comment]
Working on it.

**Comment by Froggy232** [comment]
Nice, it's very nice, thanks you a lot!
It was the only thing preventing me from using your service I think, I will wait for your news then.
Thanks again!

**Comment by Froggy232** [comment]
Hi again,
Have you any news on this problem?
I'm able to do you a few hundred euro worth of monero (or other crypto currencies) donation if you can solve it very soon, as it's the last step that keep me from using your service as I told.
I absolutely don't want to sound entitled, I would understand if you simply don't have the time. It's a shame though, because your work look incredible once coupled with ollama/localai.
Thanks you again,
Best regards

**Comment by tuxthepenguin84** [comment]
If you can only use public images you can build and publish your own images to Docker Hub, I think this temporarily solves your problem until official ones come out.

**Comment by Froggy232** [comment]
I don't know how to do it to be honnest, but I just found that there is a lot of unofficial images on docker.io already, so I will just use that.

**Comment by tuxthepenguin84** [comment]
```
git clone https://github.com/ItzCrazyKns/Perplexica.git
cd Perplexica
docker build -f app.dockerfile . -t tuxthepenguin/perplexica:latest --no-cache
docker login -u tuxthepenguin
docker push tuxthepenguin/perplexica:latest
```
https://hub.docker.com/repository/docker/tuxthepenguin/perplexica/general

I skipped the [configuration steps](https://github.com/ItzCrazyKns/Perplexica?tab=readme-ov-file#getting-started-with-docker-recommended) before docker build but this should give you an idea of what to do.

**Comment by rcarmo** [comment]
Any news on official ones? gcr.io would probably be best, since they can be built and published directly from GitHub CI.
