### ISSUE TITLE
Follow up question results in lengthy hallucinations

### ISSUE THREAD

**Issue by AxelFooley** [ItzCrazyKns/Perplexica#325]
**Describe the bug**
When using Perplexica the first question always produces an answer (will open a separate issue regarding the quality of those answers) very fast. However, when making follo up questions the search engine starts with producing a coherent answer and then after a couple of paragraph starts hallucinating producing lengthy responses with random words.

**To Reproduce**
Open Perplexica, make a question, in the same page follow up with a related question.

**Expected behavior**
All answers are coherent without hallucinations.

**Screenshots**
![search calliope lol__q=command+r%2B+llm](https://github.com/user-attachments/assets/541720c2-336a-4183-b0bc-2adf9a7ac271)

**Additional context**
There are no console errors in the browser.

**Comment by ItzCrazyKns** [comment]
Perplexica predicts whether the query is a question or just a writing task. In your case the query seemed like a question to the first agent that predicts whether it is a query or a question but the second one started hallucinating. Hallucinating is a very common AI behavior. So rephrase your query like a question and use a stronger LLM. Happy searching! 

Feel free to reopen this issue if this doesn't get solved by this
