### ISSUE TITLE
searchxng error: FileNotFoundError: [Errno 2] No such file or directory: /usr/local/searxng/searx/engines/gentoo.py'

### ISSUE THREAD

**Issue by stevenbaert** [ItzCrazyKns/Perplexica#327]
Hi,

I have install via following yaml file

---
services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searchxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://10.0.22.4:3001/api
        - NEXT_PUBLIC_WS_URL=ws://10.0.22.4:3001
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  
----

Backend docker container gives errors on searxng and searxng container  itself throws also error (below screenshots). Thanks for your help!

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/dae4cb0f-5741-4a93-b31c-2f9d4e7afcc9">

![image](https://github.com/user-attachments/assets/048ed26c-85a3-43a7-8fd0-84a8185b9268)

**Comment by ItzCrazyKns** [comment]
Replace this line `- SEARXNG_API_URL=http://searchxng:8080/` with `- SEARXNG_API_URL=http://searxng:8080/` and rebuild new images by `docker compose up -d --build`

**Comment by stevenbaert** [comment]
Thanks but did not work. Now there is another error:

![image](https://github.com/user-attachments/assets/993b77d7-bdff-48e7-9bec-3379a89a5a06)

**Comment by stevenbaert** [comment]
Great, works now! Though one final thing, the Discover, should that work too?

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/d101213b-0c39-46b8-b81d-1c8e221491a2">

**Comment by stevenbaert** [comment]
Note, the searxng still gives errors, not sure if it is related(?)

<img width="990" alt="image" src="https://github.com/user-attachments/assets/1f1db511-8a21-41c8-be38-dd1820af6d06">
