### ISSUE TITLE
Regarding modifying the OpenAI proxy url

### ISSUE THREAD

**Issue by surges567** [ItzCrazyKns/Perplexica#328]
Could you provide an option to modify the OpenAI proxy url, such as through the environment variables "OPENAI_PROXY_URL"

**Comment by ItzCrazyKns** [comment]
You can use the custom OpenAI provider from the settings and provide your proxy URL there.

**Comment by dillfrescott** [comment]
I would love to see the option to modify this via an env variable

**Comment by jrruethe** [comment]
I agree, I want to be able to set my openai base url, api key, and model as environment variables on the backend docker image, instead of needing to set them when I first load the page.
