### ISSUE TITLE
can't loading webui on localhost:3000

### ISSUE THREAD

**Issue by Anrufen** [ItzCrazyKns/Perplexica#33]
it's like this
![image](https://github.com/ItzCrazyKns/Perplexica/assets/38448868/a47a70e4-f8ec-4268-a285-964d3789f9c9)

- no change on docker.yaml
- my config.toml,only add openai api key
```
[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"
CHAT_MODEL_PROVIDER = "openai" # "openai" or "ollama"
CHAT_MODEL = "gpt-3.5-turbo" # Name of the model to use

[API_KEYS]
OPENAI = "sk-Sxxxx" # OpenAI API key - sk-1234567890abcdef1234567890abcdef

[API_ENDPOINTS]
SEARXNG = "http://localhost:32768" # SearxNG API URL
OLLAMA = "" # Ollama API URL - http://host.docker.internal:11434
```

- logs

```
docker logs perplexica-perplexica-frontend-1 --tail 100
yarn run v1.22.19
$ next start
   ▲ Next.js 14.1.4
   - Local:        http://localhost:3000

 ✓ Ready in 551ms
```
----------------------------------------------------
```
docker logs perplexica-searxng-1 --tail 100
SearXNG version 2024.4.30+c8d0b6529
Create /etc/searxng/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.23 (64bit) on [Tue Apr 30 15:26:49 2024] ***
compiled with version: 13.2.1 20231014 on 30 November 2023 14:34:33
os: Linux-5.15.60-1.el7.x86_64 #1 SMP Thu Aug 11 12:39:22 UTC 2022
nodename: e6616a6858ce
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1390 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
Python version: 3.11.9 (main, Apr 14 2024, 13:40:00) [GCC 13.2.1 20231014]
Python main interpreter initialized at 0x7f91e68d8718
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 362016 bytes (353 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 12, cores: 4)
spawned uWSGI worker 2 (pid: 13, cores: 4)
spawned 4 offload threads for uWSGI worker 1
spawned 4 offload threads for uWSGI worker 2
2024-04-30 15:26:51,334 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7f91e68d8718 pid: 12 (default app)
2024-04-30 15:26:51,352 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7f91e68d8718 pid: 13 (default app)
[root@GreenCloud Perplexica]# docker logs perplexica-perplexica-backend-1 --tail 100
yarn run v1.22.19
$ node dist/app.js
info: WebSocket server started on port 3001
(node:28) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: Server is running on port 3001
```
----------------------

```
docker logs perplexica-perplexica-backend-1 --tail 100
yarn run v1.22.19
$ node dist/app.js
info: WebSocket server started on port 3001
(node:28) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: Server is running on port 3001
```

**Comment by ItzCrazyKns** [comment]
Can you show the logs from the browser console.

**Comment by Anrufen** [comment]
> Can you show the logs from the browser console.

```
Request URL:
http://192.168.2.14:3000/library?_rsc=acgkz
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
192.168.2.14:3000
Referrer Policy:
strict-origin-when-cross-origin
```
![image](https://github.com/ItzCrazyKns/Perplexica/assets/38448868/d7d6bbce-0966-488f-b690-4b32592cd2a8)

**Comment by wwwDESIGN-basti** [comment]
same here. There is currently no way to get the app up and running

**Comment by ItzCrazyKns** [comment]
Hi, please provide the logs from the console of the browser and not the network tab. We also have a Discord server set-up where we can communicate in a much better way and help you solve your issues:- https://discord.gg/CfFWtVsn

**Comment by Github-CJX** [comment]
我也有一样的问题，无法使用websocket连接到3001
![image](https://github.com/ItzCrazyKns/Perplexica/assets/128556293/16e06b52-7b8e-4be7-b8f2-b9bdae76c4c1)

**Comment by Github-CJX** [comment]
I'm experiencing the same issue; unable to establish WebSocket connection to port 3001.
![image](https://github.com/ItzCrazyKns/Perplexica/assets/128556293/ebea685e-e55c-4021-b33c-47bdba40f41e)

**Comment by iberxilong** [comment]
I'm also the error about WebSocket connection

**Comment by Anrufen** [comment]
I think we should change the docker-compose.yml settings in perplexica-frontend

works for me

'''
127.0.0.1 to {your real ip},such as 192.168.1.1
'''

**Comment by seekme-ai** [comment]
> I'm experiencing the same issue; unable to establish WebSocket connection to port 3001. ![image](https://private-user-images.githubusercontent.com/128556293/327114556-ebea685e-e55c-4021-b33c-47bdba40f41e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzQ5NTQsIm5iZiI6MTcxNDU3NDY1NCwicGF0aCI6Ii8xMjg1NTYyOTMvMzI3MTE0NTU2LWViZWE2ODVlLWU1NWMtNDAyMS1iMzNjLTQ3YmRiYTQwZjQxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxNDQ0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTJmNzZjOGFjZjRmOGZjYjdlN2YwYzM3NWRlZDczZmM3YTMxZDM2OTQ3YjIzYjYzMGNiMzM4YWI1YTY3N2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qb-Fk1AJ478mGjdTMAyHc3UUFU-p2muJ3xc0hvmFSe0)

same.

**Comment by leonardsellem** [comment]
exacte same

**Comment by ItzCrazyKns** [comment]
If anyone tries to access Perplexica via their private IP, it won't work because the WS and API URL as set for local usage. We only provide support regarding installing Perplexica, If you wish to expose it to your network you must have the knowledge to do it, we cannot help you with that.

**Comment by Winson-030** [comment]
<img width="510" alt="Snipaste_2024-05-04_14-05-02" src="https://github.com/ItzCrazyKns/Perplexica/assets/100707097/2b1289d3-7c01-499e-bca7-ea3fad0456b6">

Set public ip like this if use a vm
