### ISSUE TITLE
Error After deployment, every time when I open a search. I see this error message." when using Repocloud.io

### ISSUE THREAD

**Issue by catninelife** [ItzCrazyKns/Perplexica#334]
I tried many time. After deployment on Repocloud, every time when I open a search. I see this error message. After deployment, every time when I open a search. I see this error message.

**Comment by catninelife** [comment]
I am using openai - gpt-3.5

**Comment by RazeBerry** [comment]
What is the error message?

**Comment by catninelife** [comment]
> What is the error message? Did you set up OPENAI API KEY?

Yes openai api key has been set. Error "Fialed to connect to the server"

**Comment by ItzCrazyKns** [comment]
Hi, I just pushed a commit that fixes this issue, please wait for Repocloud to update the project on their website and the redeploy the app there

**Comment by catninelife** [comment]
unfortunately, same error "Failed to connect to the server. Please try again later."
