### ISSUE TITLE
Doesn't support context, every time you ask a question it's a new session

### ISSUE THREAD

**Issue by catninelife** [ItzCrazyKns/Perplexica#339]
**Is your feature request related to a problem? Please describe.**
Without support for context, the value of this tool is much diminished

**Describe the solution you'd like**
Support context within one chat session.

**Comment by AxelFooley** [comment]
It doesn't seem to me that context is not supported
![image](https://github.com/user-attachments/assets/83727c39-20af-4b20-8216-e73f5b6c6605)
