### ISSUE TITLE
Provide pre-build container image on one of public registries

### ISSUE THREAD

**Issue by Expro** [ItzCrazyKns/Perplexica#34]
It would be nice if you could provide pre-build container image on one of public registries, such as hub.docker.com. Docker-compose doesn't really mach Kubernetes workflow.

**Comment by ItzCrazyKns** [comment]
We need some config updates that have to be done manually by the user. If we copy the config there, it wouldn't give them much control over the application. I'll look into other ways of handling it and re-open the issue when we really need it. Thank you!

**Comment by Expro** [comment]
Environmental variables are commonly used for configuration purposes in container's world.

**Comment by alirezanet** [comment]
I agree with this. I'm uncertain as to why the issue was closed; it's a great idea. Had it remained open, I might have contributed a pull request for the configurations. 🤷‍♂️

**Comment by NikMAX2077** [comment]
+1

**Comment by ItzCrazyKns** [comment]
Prebuilt images are used by default, please follow the installation steps
