### ISSUE TITLE
Can't type / character anywhere in UI

### ISSUE THREAD

**Issue by Bratzmeister** [ItzCrazyKns/Perplexica#344]
**Describe the bug**

**To Reproduce**
1. go to any input field in the webui (search, settings, ...)
2. try to type /
3. be surprised nothing happens
4. copy string including / from other source
5. ctrl+v
6. it works...
7. create issue on github

**Expected behavior**
that I don't need to copy+paste the / character from elsewhere and can just type it

**Additional context**
obviously it's working everywhere else. I tried multiple keymaps (English US, English US intl., German, Norwegian) and always / is not typed. I'm using latest firefox browser

**Comment by antistereov** [comment]
This issue is probably related to issue #213 and commit https://github.com/ItzCrazyKns/Perplexica/commit/9a96fd4788e5bfaa15f74ac5e42184184364c4c1 

A possible solution could be to only focus the textbox if it is not yet selected.

**Comment by ItzCrazyKns** [comment]
Fixed by https://github.com/ItzCrazyKns/Perplexica/commit/c4f52adb456d16ddc957edeafa82de27c3a9f953
