### ISSUE TITLE
Docker version is broken

### ISSUE THREAD

**Issue by LZBNCC** [ItzCrazyKns/Perplexica#345]
**Describe the bug**
Cannot search, the page keeps spinning and the console returns httpx.TimeoutException: Timeout

**To Reproduce**
just start the project

**Expected behavior**
I can search normally.

**Screenshots**
![image](https://github.com/user-attachments/assets/61b4701d-f1d3-400e-a084-737f88745807)
![image](https://github.com/user-attachments/assets/3b34b252-3304-4d94-af70-7d48050afbcd)
![image](https://github.com/user-attachments/assets/a7c020f3-1cc6-48cd-a1dc-9dc3963c4a41)

**Additional context**

**Comment by ItzCrazyKns** [comment]
The SearXNG logs aren't a problem, please use English sometimes the format doesn't get recognized in other languages. If the issue doesn't gets resolved feel free to re-open it
