### ISSUE TITLE
Dependency error?

### ISSUE THREAD

**Issue by xiaopa233** [ItzCrazyKns/Perplexica#354]
**Describe the bug**
 > [perplexica-backend 11/12] RUN yarn install:
0.537 yarn install v1.22.22
0.580 [1/4] Resolving packages...
0.682 [2/4] Fetching packages...
24.05 [3/4] Linking dependencies...
24.06 warning "@langchain/anthropic > zod-to-json-schema@3.23.1" has incorrect peer dependency "zod@^3.23.3".
24.06 warning " > ts-node@10.9.2" has unmet peer dependency "@types/node@*".
33.39 [4/4] Building fresh packages...
126.5 error /home/perplexica/node_modules/sharp: Command failed.
126.5 Exit code: 1
126.5 Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
126.5 Arguments:
126.5 Directory: /home/perplexica/node_modules/sharp
126.5 Output:
126.5 sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-x64.tar.br
126.5 sharp: Installation error: aborted
126.5 sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
126.5 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1

**To Reproduce**

run `docker compose up -d`

**Comment by b3nis** [comment]
I have the exact same issue. 

Very excited to try out the project!

**Comment by ItzCrazyKns** [comment]
Please re-clone Perplexica from Github and run the installation steps again. The issue should be fixed.

**Comment by xiaopa233** [comment]
> Please re-clone Perplexica from Github and run the installation steps again. The issue should be fixed.

Still the same

**Comment by TrivCodez** [comment]
Still same mate.

**Comment by CharlesHAO77** [comment]
Still same mate. please help @ItzCrazyKns

**Comment by 0won** [comment]
Solved the backend,docker issue by replacing

> RUN yarn ...

with 

> RUN set -ex;
>        yarn install --frozen-lockfile --network-timeout 6000000;
>        yarn cache clean;
>        yarn run build

Still working on the app.docker (frontend) problem.
Tried [this recommendation](https://github.com/ItzCrazyKns/Perplexica/issues/163#issuecomment-2150570952), which did not appear to work.
Moving on to try [this solution](https://github.com/vercel/next.js/discussions/60147#discussioncomment-7998134), will update with results.
