### ISSUE TITLE
Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/gentoo.py'

### ISSUE THREAD

**Issue by stevenbaert** [ItzCrazyKns/Perplexica#358]
**Describe the bug**
Error in nginx container, Perplexica is full container installation. 

**To Reproduce**
Going to Discover option in Perplexica, then it shows not found. 

**Expected behavior**
Opening discover 

**Screenshots**
![image.png](https://github.com/user-attachments/assets/f8dfe33c-1dc1-4d31-92e0-4d4a59a3dd5f)

**Comment by ItzCrazyKns** [comment]
Discover feature is under development and SearXNG's errors won't cause any issues
