### ISSUE TITLE
Unable to view images api/images error.

### ISSUE THREAD

**Issue by armayde** [ItzCrazyKns/Perplexica#359]
**Describe the bug**
Clicking on images will http://127.0.0.1:3001/api/images show 500 error in browser console 

**To Reproduce**

1. Go to 'any search result'
2. Click on 'images on the right hand side'
3. Page opens will say theres an error and view browser console logs

**Expected behavior**
I assume to see the images on the search results.

**Screenshots**
![image](https://github.com/user-attachments/assets/66aa4fb9-813f-45a8-beb8-0097292fe8ef)
**Additional context**

Running on Docker, windows ubuntu, using Openrouter llm. Able to use all the features of just searching just fine. Happens with both copilot toggled on or off.

**Comment by ItzCrazyKns** [comment]
What are the logs in the docker container

**Comment by armayde** [comment]
Nothing out of the ordinary. When I click images button we dont see visible changes to logs.
