### ISSUE TITLE
ERROR [perplexica-frontend 5/5] RUN yarn build

### ISSUE THREAD

**Issue by coderyiyang** [ItzCrazyKns/Perplexica#364]
=> ERROR [perplexica-frontend 5/5] RUN yarn build                                                                                      12.1s
------
 > [perplexica-frontend 5/5] RUN yarn build:
1.067 yarn run v1.22.22
1.093 $ next build
1.749 Attention: Next.js now collects completely anonymous telemetry regarding usage.
1.749 This information is used to shape Next.js' roadmap and prioritize features.
1.749 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
1.750 https://nextjs.org/telemetry
1.750
1.884    ▲ Next.js 14.1.4
1.884
2.001    Creating an optimized production build ...
3.701 (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
3.701 (Use `node --trace-deprecation ...` to show where the warning was created)
4.011 request to https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap failed, reason:
4.011
4.011 Retrying 1/3...
4.364 request to https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap failed, reason:
4.364
4.364 Retrying 2/3...
4.821 request to https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap failed, reason:
4.821
4.821 Retrying 3/3...
5.478 FetchError: request to https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap failed, reason:
5.478     at ClientRequest.<anonymous> (/home/perplexica/node_modules/next/dist/compiled/node-fetch/index.js:1:66160)
5.478     at ClientRequest.emit (node:events:520:28)
5.478     at emitErrorEvent (node:_http_client:103:11)
5.478     at TLSSocket.socketErrorListener (node:_http_client:506:5)
5.478     at TLSSocket.emit (node:events:520:28)
5.478     at emitErrorNT (node:internal/streams/destroy:170:8)
5.478     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
5.478     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
5.478   type: 'system',
5.478   errno: 'ETIMEDOUT',
5.478   code: 'ETIMEDOUT'
5.478 }
11.30 Failed to compile.
11.30
11.30 app/layout.tsx
11.30 `next/font` error:
11.30 Failed to fetch `Montserrat` from Google Fonts.
11.30
11.31
11.31 > Build failed because of webpack errors
11.32 error Command failed with exit code 1.
11.32 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

Envy: WIN10 edu

Tried #168 #183 #185 methods, but still failed to install.
![image](https://github.com/user-attachments/assets/751d2c0c-b503-4bce-9405-dc8f0d53b3ed)

**Comment by pupstime5** [comment]
got the same error on ubuntu 22.04 Docker version 27.2.1, build 9e34c9b

**Comment by coderyiyang** [comment]
> got the same error on ubuntu 22.04 Docker version 27.2.1, build 9e34c9b

import type { Metadata } from 'next';
//import { Montserrat } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Sidebar from '@/components/Sidebar';
import { Toaster } from 'sonner';
import ThemeProvider from '@/components/theme/Provider';

const montserrat = cn ({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['Arial', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Perplexica - Chat with the internet',
  description:
    'Perplexica is an AI powered chatbot that is connected to the internet.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en" suppressHydrationWarning>
      <body className={cn('h-full', "Arial")}>
        <ThemeProvider>
          <Sidebar>{children}</Sidebar>
          <Toaster
            toastOptions={{
              unstyled: true,
              classNames: {
                toast:
                  'bg-light-primary dark:bg-dark-secondary dark:text-white/70 text-black-70 rounded-lg p-4 flex flex-row items-center space-x-2',
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}

rewriting \Perplexica-master\ui\app\layout.tsx as above code helps get through this bug. good luck!

**Comment by pupstime5** [comment]
> > got the same error on ubuntu 22.04 Docker version 27.2.1, build 9e34c9b
> 
> import type { Metadata } from 'next'; //import { Montserrat } from 'next/font/google'; import './globals.css'; import { cn } from '@/lib/utils'; import Sidebar from '@/components/Sidebar'; import { Toaster } from 'sonner'; import ThemeProvider from '@/components/theme/Provider';
> 
> const montserrat = cn ({ weight: ['300', '400', '500', '700'], subsets: ['latin'], display: 'swap', fallback: ['Arial', 'sans-serif'], });
> 
> export const metadata: Metadata = { title: 'Perplexica - Chat with the internet', description: 'Perplexica is an AI powered chatbot that is connected to the internet.', };
> 
> export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) { return ( <body className={cn('h-full', "Arial")}> {children} <Toaster toastOptions={{ unstyled: true, classNames: { toast: 'bg-light-primary dark:bg-dark-secondary dark:text-white/70 text-black-70 rounded-lg p-4 flex flex-row items-center space-x-2', }, }} /> ); }
> 
> rewriting \Perplexica-master\ui\app\layout.tsx as above code helps get through this bug. good luck!

your suggestion works, thank you
