### ISSUE TITLE
punycode` module deprecated

### ISSUE THREAD

**Issue by devops-snap-shoot** [ItzCrazyKns/Perplexica#370]
**Describe the bug**
DeprecationWarning: The `punycode` module is deprecated.

**To Reproduce**
$ docker compose build

(node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alter
 => => # native instead.

**Comment by devops-snap-shoot** [comment]
Nor critical but flag a warning when trying to build Dockerfile!

**Comment by ItzCrazyKns** [comment]
We're not directly dependent upon Punycode so it should not cause any issues.

**Comment by devops-snap-shoot** [comment]
Súper 👍  and great news !!!Sent from my iPhoneOn Sep 23, 2024, at 8:13 AM, ItzCrazyKns ***@***.***> wrote:﻿
Closed #370 as completed.
