### ISSUE TITLE
Python requests post api 

### ISSUE THREAD

**Issue by ajikmr** [ItzCrazyKns/Perplexica#376]
Hello.

I am trying to call the backend using python requests. Few api endpoints work, but requests.post for search is giving error. Any tips?

import requests

body = { "chatModel": { "provider": "ollama", "model": "qwen2.5:1.5b" }, "embeddingModel": { "provider": "ollama",  "model": "nomic-embed-text:latest" },  "focusMode": "webSearch", "query": "What is Perplexica", "history": [ ["human", "Hi, how are you?"],  ["assistant", "I am doing well, how can I help you today?"] ]}

headers = { "Content-Type": "application/json" } 

r = requests.post(
    url="http://localhost:3001/api/search",
    json=body,
    headers=headers
) 

error: Response 400
error: Unhandled Rejection at: [object Promise], reason: AxiosError: Request failed with status code 400

While some other api endpoints are working fine, such as

models = requests.get("http://localhost:3001/api/models")
models.json()

or 

response = requests.options("http://localhost:3001/api/search")
print(response.ok)

**Comment by ItzCrazyKns** [comment]
Its not an issue related to Perplexica its rather an issue with the model size, these small models don't follow the prompt correctly and start outputting random things, links etc. So try using a different bigger model, feel free to reopen the issue if you face the issue again.
