### ISSUE TITLE
Leverage multiple search engines simultaneously

### ISSUE THREAD

**Issue by choskeli** [ItzCrazyKns/Perplexica#377]
**Is your feature request related to a problem? Please describe.**
Sometimes using a traditional Google search or a chatbot interface without internet is preferable. 

**Describe the solution you'd like**
I'd like a tab that can be toggled between that shows the underlying SearX results rather than the chat bot results. Additionally a chat tab where it is just like a normal chat interface would be helpful in case you don't want to search the web because you want maximum context window for chat history. I think the offline chat tab should keep a separate context history because where it tends to be more useful is for software devs who are problem solving.

**Describe alternatives you've considered**
Chrome plugins but it's not as clean and none of them are that great nor do they allow simultaneously searching both engines.

**Additional context**
I'm hoping the goal isn't just to clone perplexity but to be an all in one search solution that handles the current 3 major types of search: traditional search engines, offline chatbot, online chatbot.

**Comment by ItzCrazyKns** [comment]
> **Is your feature request related to a problem? Please describe.** Sometimes using a traditional Google search or a chatbot interface without internet is preferable.
> 
> **Describe the solution you'd like** I'd like a tab that can be toggled between that shows the underlying SearX results rather than the chat bot results. Additionally a chat tab where it is just like a normal chat interface would be helpful in case you don't want to search the web because you want maximum context window for chat history. I think the offline chat tab should keep a separate context history because where it tends to be more useful is for software devs who are problem solving.
> 
> **Describe alternatives you've considered** Chrome plugins but it's not as clean and none of them are that great nor do they allow simultaneously searching both engines.
> 
> **Additional context** I'm hoping the goal isn't just to clone perplexity but to be an all in one search solution that handles the current 3 major types of search: traditional search engines, offline chatbot, online chatbot.

You can see all the search results in the sources tab, offline chatbot can be used by selecting writing mode in the focus modes from the UI and online chatbot works as it is.

**Comment by choskeli** [comment]
Yes but the sources tab doesn't have text to show u what is in that source like a traditional search engine does, so it's unclear which to click.

**Comment by ItzCrazyKns** [comment]
Well this is built to replace the traditional search engines.

**Comment by choskeli** [comment]
> Well this is built to replace the traditional search engines.

I've found sometimes I still need a traditional search engine if the question requires more research than Perplexica can handle or if I'm just looking to answer a single specific question quickly. I've found that I have 4 types of problems (3 of which I'm hoping Perplexica can solve):

1. Most coding problems are solved within IDE using integrated tools and LLM APIs.
2. Some problems require the latest research in which case I'd like Perplexica to fill up the entire context window with research about that problem.
3. Some problems require most of the context window to remain about the problem itself (these are similar to 1 but being solved outside of IDE for whatever reason e.g. out of API tokens, don't have integrated tools, etc.). It shouldn't search the internet at all unless I specifically ask it to or if I give it a link and ask it to read it.
4. Some problems still require me to do manual work where I search for specific details (this is where I want a traditional search engine - or perhaps an aggregator like SearX could be even better). As a side note, it'd also be good to be able to control which search engines SearX is using. For example [exa.ai](url) is looking pretty promising.

**Comment by choskeli** [comment]
> Well this is built to replace the traditional search engines.

I also wanted to add an example. If you search perplexica for open AI RSS feed it gives you the old feed which is a dead link, but if you do a little manual searching you can find a link to the new feed in the answer here: https://community.openai.com/t/openai-website-rss-feed-inquiry/733747

**Comment by choskeli** [comment]
@ItzCrazyKns sorry to go on with this but if you look at [felo.ai](https://felo.ai) (perplexity competitor) it does what I'm talking about. The sources are on the right with text so you can can get some context just like a normal search engine.
![Screenshot from 2024-10-01 10-01-01](https://github.com/user-attachments/assets/a807f980-c2f1-4d5c-937c-62cbfef499c9)
