### ISSUE TITLE
Custom_openai is the only chat model provider

### ISSUE THREAD

**Issue by thaotnguyen** [ItzCrazyKns/Perplexica#380]
**Describe the bug**
I cannot choose another `Chat model provider` than `Custom_openai`. This is giving me an error upon loading `localhost:3000`, which makes me unable to use Perplexica.

**To Reproduce**
Install Perplexica by git cloning the repo, edit `sample.config.toml` into `config.toml`, and then run `sudo docker compose up -d`.

**Expected behavior**

**Screenshots**
<img width="1440" alt="Screenshot 2024-09-29 at 9 21 59 PM" src="https://github.com/user-attachments/assets/3da808de-605b-4956-b702-9e7e8717f9de">

<img width="1432" alt="Screenshot 2024-09-29 at 9 21 46 PM" src="https://github.com/user-attachments/assets/e453851f-00b1-4af7-abf7-c61c356d3145">

**Additional context**
I'm using Ubuntu. Going to `localhost:11434` gives me `Ollama is running`, so I'm using `localhost:11434` as my `Ollama API URL`. Going to `localhost:32768` gives me SearXNG's homepage. I'm using Ollama as a service using `systemctl`.

My `config.toml`:

```
[API_KEYS]
OPENAI = ""
GROQ = ""
ANTHROPIC = ""

[API_ENDPOINTS]
OLLAMA = "http://localhost:11434"
SEARXNG = "http://localhost:32768"

[GENERAL]
PORT = 3001
SIMILARITY_MEASURE = "cosine"
```

**Comment by ItzCrazyKns** [comment]
https://github.com/ItzCrazyKns/Perplexica?tab=readme-ov-file#ollama-connection-errors

**Comment by thaotnguyen** [comment]
I followed that guide and added `Environment="OLLAMA_HOST=0.0.0.0"` and ran `systemctl restart ollama` already, but I'm still seeing the same problem. I also tried using `hostname -I` to get my IP address, which I then used for `http://<private_ip_of_host>:11434`, but it's still not working.
