### ISSUE TITLE
 http://localhost:3000/discover 404 (Not Found)   

### ISSUE THREAD

**Issue by Mudasir345** [ItzCrazyKns/Perplexica#384]
GET http://localhost:3000/discover 404 (Not Found)

page-8f4deed53d699169.js:1 
 GET http://localhost:3000/undefined/chats 404 (Not Found)
VM359:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
468-d258c233d566281b.js:1 
 GET http://localhost:3000/undefined/models 404 (Not Found)
VM362:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
fc.js:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
    at d (fc.js:1:71368)
2
fc.js:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
    at d (fc.js:1:71368)
﻿
<img width="958" alt="perp issues" src="https://github.com/user-attachments/assets/c0475b37-c63e-4cd9-a3ac-29d67883e060">

**Comment by ItzCrazyKns** [comment]
The discover page is under development so it will indeed return 404
