### ISSUE TITLE
Token usage in API

### ISSUE THREAD

**Issue by Melodeiro** [ItzCrazyKns/Perplexica#398]
Would be very grateful if you add token usage information in API responses to get hint on request costs

**Comment by ItzCrazyKns** [comment]
We have multiple different providers and its not very easy to implement pricing for all of them, Perplexica is intended to be used with local providers like Ollama, vLLM, Llama.cpp which only use your compute power.

**Comment by Melodeiro** [comment]
I mislead you with the word "cost" i meant just a token count of course.

**Comment by Melodeiro** [comment]
@ItzCrazyKns could you please reopen if my clarification changed your mind? I just meant sending token usage that you are getting from langchain https://js.langchain.com/v0.1/docs/modules/model_io/chat/token_usage_tracking/

**Comment by Melodeiro** [comment]
Thats sad because this project is useful with online models as well
