### ISSUE TITLE
Compilation error when building from source

### ISSUE THREAD

**Issue by happysalada** [ItzCrazyKns/Perplexica#407]
**Describe the bug**
When trying to build from source off the latest release I get

 builder for '/nix/store/qa8xjxh4wch85kyc52i4p2a5liavl37l-perplexica-
backend-1.9.0.drv' failed with exit code 2;
       last 25 log lines:
       > 198     handleStream(stream, emitter);
       >                      ~~~~~~
       >
       > src/agents/writingAssistant.ts:79:18 - error TS2345: Argument of t
ype 'AsyncGenerator<StreamEvent, any, unknown>' is not assignable to parame
ter of type 'IterableReadableStream<StreamEvent>'.
       >
       > 79     handleStream(stream, emitter);
       >                     ~~~~~~
       >
       > src/agents/youtubeSearchAgent.ts:248:18 - error TS2345: Argument o
       >
       > 248     handleStream(stream, emitter);
       >                      ~~~~~~
       >
       >
       > Found 6 errors in 6 files.
       >
       > Errors  Files
       >      1  src/agents/academicSearchAgent.ts:251
       >      1  src/agents/redditSearchAgent.ts:247
       >      1  src/agents/webSearchAgent.ts:431
       >      1  src/agents/wolframAlphaSearchAgent.ts:198
       >      1  src/agents/writingAssistant.ts:79
       >      1  src/agents/youtubeSearchAgent.ts:248

**To Reproduce**
I'm using exactly the lock file released with 1.9.0

**Additional context**
I'm not sure if it's a ts compiler version that wasn't updated in the yarn.lock file in the 1.9.0 release. 1.9.0-rc1 was working fine.

**Comment by ItzCrazyKns** [comment]
I am not able to reproduce the issue, can you try cloning the repo and building the images again?

**Comment by happysalada** [comment]
Thank you for trying.
I was packaging this for nixos, it always builds from source.
No worries im going to close this for now and will give it another go on the next release tag, thank you !
