### ISSUE TITLE
No Gear icon when running Perplexica UI on Android

### ISSUE THREAD

**Issue by eliranwong** [ItzCrazyKns/Perplexica#408]
**Describe the bug**

I managed to install docker and running Perplexica on Android, but the Perplexica web UI on android web browsers show no Gear icon for changing embedding settings.  There is also no URL I can make a change.  I can specify embedding model when I use API, but it would be very nice to have the gear icon on Android browsers or a url navigating to the setting page.

**To Reproduce**

1. Follow the following notes to install docker and Perplexica on Android
https://github.com/eliranwong/toolmate/blob/main/package/toolmate/docs/Docker%20Setup%20on%20Android%20Termux.md

2. Open http://localhost:3000 with chrome, edge and Firefox browers

**Expected behavior**
 it would be very nice to have the gear icon or a url navigating to the setting page.

**Screenshots**

Chrome

![Screenshot_20241016-163345](https://github.com/user-attachments/assets/8de966fe-a826-4088-8dc4-c683ace02db1)

Firefox

![Screenshot_20241016-163337](https://github.com/user-attachments/assets/6dc2b2f3-14e7-416d-8609-e683b9e64a76)

Edge

![Screenshot_20241016-163328](https://github.com/user-attachments/assets/0d31331f-164b-4641-b204-d1031bb2c107)

**Additional context**

**Comment by ItzCrazyKns** [comment]
Similar issue: https://github.com/ItzCrazyKns/Perplexica/issues/162
