### ISSUE TITLE
Make NEXT_PUBLIC_API_URL and NEXT_PUBLIC_WS_URL Configurable at Runtime via Environment Variables - Standard Docker

### ISSUE THREAD

**Issue by RodrigoHolztrattner** [ItzCrazyKns/Perplexica#409]
**Is your feature request related to a problem? Please describe.**
Currently, `NEXT_PUBLIC_API_URL` and `NEXT_PUBLIC_WS_URL` are only modifiable before the frontend is built, making it difficult to use with standard Docker, as it defaults to address 127.0.0.1 (what is expected if using docker compose, but doesn't work well for environments that doesn't use or cannot support it).

**Describe the solution you'd like**

Frontend could read those addresses optionally from a config file during runtime (if such config file exists, otherwise use default values), or they could be treated as environment variables (the ones passed on docker run) not dynamically baked into the frontend.

**Describe alternatives you've considered**

I temporarily solved this issue by appending the command below to the docker run command, totally not an elegant solution and the `yarn build` is only reflected the next time the container is started (could not add `yarn start` as it complains about port 3000 already in use).

`&& docker exec <container_id> sh -c "echo 'NEXT_PUBLIC_API_URL=<backend_address>/api' > .env.local" && docker exec <container_id> sh -c "echo 'NEXT_PUBLIC_WS_URL=ws://<backend_address>' >> .env.local" && docker exec <container_id> sh -c "yarn build"`

**Additional context**

Why not use Docker Compose, you might ask? I am using Unraid, and it does not natively support Docker Compose. While there are plugins that add Compose functionality (which I used until recently), they break the auto-update functionality and cannot be integrated into the Community Apps, which would be a valuable addition to Unraid.

Thanks for providing the prebuilt images, though!

**Comment by ItzCrazyKns** [comment]
Hi, I've talked about it in this issue as well https://github.com/ItzCrazyKns/Perplexica/issues/403 please take a look at it over there.
