### ISSUE TITLE
Divisive example used on Perplexica landing page

### ISSUE THREAD

**Issue by MinhHaDuong** [ItzCrazyKns/Perplexica#410]
**Describe the bug**
Using Elon Musk and Tesla as examples is divisive without necessity.

**To Reproduce**

1. Go to [https://github.com/ItzCrazyKns/Perplexica]
2. Scroll down to the image and video
3. See contents about Elon Musk and Tesla

**Expected behavior**
I expect to see the name and image of someone those values make me like the project.

**Additional context**
Musk is one of the richest white men in the world, very engaged politically. Hailing to such a divisive figure is not coherent with the public good mindset of an open source project.

**Comment by Dorifor** [comment]
You're asking AI brain deads not to agree with a fascist ? :)

**Comment by Dorifor** [comment]
Even more so with recent events.

**Comment by MinhHaDuong** [comment]
Glad you agree. Unfortunately 3 thumbs up / 9 thumbs down.
