### ISSUE TITLE
Trouble Connecting MySQL to SearxNG Image After Modifications

### ISSUE THREAD

**Issue by 120L020910fanshuo** [ItzCrazyKns/Perplexica#415]
I have installed Perplexica using Docker. Now I hope to add a MySQL database to the search source of the SearxNG search tool. How should I operate on the SearxNG image? At present, according to SearxNG's technical documentation, I have added the Python connection library, modified settings.yml, and regenerated the image. However, I still cannot connect to MySQL. Now how should I modify SearxNG?

**Comment by ItzCrazyKns** [comment]
Hi, this is unrelated to Perplexica so I'd have to close this issue. We don't provide support here for custom implementations.
