### ISSUE TITLE
Settings on Mobile and default models on ollama

### ISSUE THREAD

**Issue by superversivesf** [ItzCrazyKns/Perplexica#416]
I have multiple ollama models installed. Currently it defaults to picking the first one which is a large model that doesn't fit in my gpu and so is slow. But there are a bunch of models I have that do fit. 

I cam select them from the settings page but on the mobile view I cannot get to a settings button anywhere. 

Would.it be possible to add it or perhaps better, specify default ollam search and embedding models so it doesn't default to whatever is first in the list?

**Comment by ItzCrazyKns** [comment]
Hi, there's already an issue for this so I will close this one, you can follow up here: https://github.com/ItzCrazyKns/Perplexica/issues/162
