### ISSUE TITLE
Perlexica is permanently stuck on "Answer"

### ISSUE THREAD

**Issue by remon-nashid** [ItzCrazyKns/Perplexica#418]
Perlexica is permanently stuck on "Answer" loader. As simple as that. Out of tens of attempts it might have worked only two times.
- Using a tiny `llama3.2:1b-instruct-q6_K` model.
- `ollama ps` shows that the model gets loaded, but in 4 minutes it gets unloaded without returning an answer.
- The internal SearXNG instance works fine when queried directly on port 4000.
- Using the Perplexica docker image. Updated and rebuilt via `docker-compose up --build` just yesterday (Oct 18th).
- GPU is ample, and the same question when passed to OpenWebUI, using the search functionality, gets answered in seconds.
- Browser console only shows `[DEBUG] opened` and `[DEBUG] ready`.
- Docker logs of backend shows `error: Unhandled Rejection at: [object Promise], reason: AxiosError: Request failed with status code 400`.
- Docker logs of frontend has no errors.

**Screenshots**
![Screenshot From 2024-10-19 07-29-59](https://github.com/user-attachments/assets/818d723c-9132-48c5-ac80-172d03b4a0ef)

**Comment by remon-nashid** [comment]
Well it might be model dependent. Tried `gemma2:2b-instruct-q6_K` and that seems to work fine :/ .

**Comment by ItzCrazyKns** [comment]
Its not an issue with Perplexica, its rather an issue with the model you're using. 1B model is so small that it doesn't understands the prompt and starts outputting random things. Please use a larger model.

**Comment by hugokoopmans** [comment]
issue still there, also with bigger models. Some feedback telling the enduser the model they are using is not handling the input adequately could be helpful
