### ISSUE TITLE
"Failed to connect to the server. Please try again later."

### ISSUE THREAD

**Issue by coderyiyang** [ItzCrazyKns/Perplexica#419]
**Describe the bug**
When I followed Perplexica's instructions to complete the installation within Docker and set the Ollama API URL to http://host.docker.internal:11434 on the setup page, then saved and returned to the main page, it showed "Failed to connect to the server. Please try again later." As shown in the screenshot below. 

I have also tried changing http://host.docker.internal:11434 to http://192.168.x.x:11434, but the problem persists. 
I have tried other similar solutions from the issue page, but the problem still exists.

About a month ago in the previous version, this problem did not exist.

env: windows 10 ver22H2
sub env: Docker version 27.2.0, build 3ab4256
ver of perplexica: v1.9.1

**Expected behavior**
debug and explain why this happened.
step-by-step is expected.

**Screenshots**
![image](https://github.com/user-attachments/assets/aed51ea1-af34-44c1-a39a-ac5fde42128c)
![image](https://github.com/user-attachments/assets/fe5b58af-8417-49b9-9bd6-537e6b966f01)

**Additional context**

**Comment by ItzCrazyKns** [comment]
Is Ollama accessible at http://localhost:11434?

**Comment by coderyiyang** [comment]
Yes, ollama works just fine, and I tried&nbsp;http://localhost:11434&nbsp;too, but failed.
----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："ItzCrazyKns ***@***.***&gt;;
发送时间：2024年10月20日(星期天) 晚上10:37
收件人："ItzCrazyKns/Perplexica" ***@***.***&gt;;
抄送："coderyiyang ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [ItzCrazyKns/Perplexica] "Failed to connect to the server. Please try again later." (Issue #419)
-----------------------------------

 

 
Is Ollama accessible at http://localhost:11434?

**Comment by ItzCrazyKns** [comment]
Use the `http://host.docker.internal:11434` URL and select Ollama in the chat model provider select. If you don't see it there, I need the logs from the backend.

**Comment by coderyiyang** [comment]
> Use the `http://host.docker.internal:11434` URL and select Ollama in the chat model provider select. If you don't see it there, I need the logs from the backend.

When I use `http://host.docker.internal:11434` as the URL, there is no option other than ‘Custom_openai’ in the Chat model Provider list. see sreenshot:
![image](https://github.com/user-attachments/assets/3fa93668-3e0d-48c0-bf1d-b44b498ef294)

I‘m not sure if 'the logs from the backend' means those logs generated by Docker, if so, here are the files I retrieved from it:
[electron-2024-10-21-20.log](https://github.com/user-attachments/files/17460853/electron-2024-10-21-20.log)
[monitor.log](https://github.com/user-attachments/files/17460857/monitor.log)
[com.docker.backend.exe.log](https://github.com/user-attachments/files/17460862/com.docker.backend.exe.log)

If you mean similar log files generated by Perplexica, tell me where are they. I tried to browse its structure but find no .log files.
Thanks a lot.

**Comment by goughjo02** [comment]
did you press the blue button after you updated the config?

**Comment by coderyiyang** [comment]
> did you press the blue button after you updated the config?

ya, sure, or there would have no log file to generate.

**Comment by goughjo02** [comment]
i had the same bug as you but i got it to stop. could you try to disable the cache in your network tab of your browser maybe? it is a shot in the dark but just see what happens

**Comment by coderyiyang** [comment]
> i had the same bug as you but i got it to stop. could you try to disable the cache in your network tab of your browser maybe? it is a shot in the dark but just see what happens

Thanks for the tip, I'll give it a shot later!

**Comment by coderyiyang** [comment]
> i had the same bug as you but i got it to stop. could you try to disable the cache in your network tab of your browser maybe? it is a shot in the dark but just see what happens

Nope! doesn't work for me, but thank you all the same~

**Comment by ItzCrazyKns** [comment]
Is Ollama even running and is it accessible at http://localhost:11434

**Comment by coderyiyang** [comment]
> Is Ollama even running and is it accessible at http://localhost:11434

ya, ollama runs just normal at http://localhost:11434
some other issues report this bug as a container caused confusing, say there is a difference between docker's localhost and pc's localhost (if i get it right). do not know if this is the case.

**Comment by ItzCrazyKns** [comment]
Does it work if you use `http://host.docker.internal:11434` as your Ollama URL. Make sure to press the blue save button and then re open the settings menu after the refresh.

**Comment by coderyiyang** [comment]
> Does it work if you use `http://host.docker.internal:11434` as your Ollama URL. Make sure to press the blue save button and then re open the settings menu after the refresh.

both http://host.docker.internal:11434 and http://localhost:11434/ failed even after my pressing the blue save button.

**Comment by ItzCrazyKns** [comment]
Not sure what's causing the issue here, can you join our Discord server here: https://discord.gg/sDUJmVNF so I can help you better. Otherwise share me the logs here.

**Comment by coderyiyang** [comment]
> Not sure what's causing the issue here, can you join our Discord server here: https://discord.gg/sDUJmVNF so I can help you better. Otherwise share me the logs here.

where are the log files? will join it later.

**Comment by coderyiyang** [comment]
> Not sure what's causing the issue here, can you join our Discord server here: https://discord.gg/sDUJmVNF so I can help you better. Otherwise share me the logs here.

don't know how to register this discord. it keeps telling me that my email address is occupied, but it isn't.

**Comment by stawils** [comment]
Hi,
I have the same problem since latest update of  ollama version is 0.3.14, which running as a service in my local ubuntu 24.

The option for ollama is not there and it can not fectch it.
Preplexica is running in a container and not matter if i use both URL for ollama.


here is the log 

`> perplexica-backend@1.9.1 db:push
> drizzle-kit push sqlite

drizzle-kit: v0.22.7
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file '/home/perplexica/drizzle.config.ts'
[⣷] Pulling schema from database...
[✓] Pulling schema from database...

[i] No changes detected
info: WebSocket server started on port 3001
info: Server is running on port 3001
error: Error loading Ollama models: TypeError: fetch failed
error: Error loading Ollama embeddings model: TypeError: fetch failed
error: Error loading Ollama models: TypeError: fetch failed
error: Error loading Ollama embeddings model: TypeError: fetch failed`

**Comment by GOOD-N-LCM** [comment]
well~   i used https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md

**Comment by Tim02104** [comment]
Same issue here. Ollama is running, but Perplexica does not connect. I run another docker with openwebui and that has no problems with Ollama. 

One thing i do not understand - but i have 0 Linux knowlage -: Everytime I change something in the settings, in the config.toml file the port goes from 3000 to 3_001 as you see in the picture. Maybe that is normal. 

![Bildschirmfoto vom 2024-11-04 21-26-16](https://github.com/user-attachments/assets/d3d723c9-9885-44af-8e5d-3be9ed592f57)

![Bildschirmfoto vom 2024-11-04 21-26-36](https://github.com/user-attachments/assets/41f26090-067c-49a4-8e5f-d78f3ac34718)

![Bildschirmfoto vom 2024-11-04 21-27-06](https://github.com/user-attachments/assets/b0f53748-2d84-4d10-b047-85623c7ca3cb)

![Bildschirmfoto vom 2024-11-04 21-27-44](https://github.com/user-attachments/assets/6220d855-efcb-4458-ab4b-3f69c1b5ba9c)

**Comment by ItzCrazyKns** [comment]
Don't worry about the the port just follow the guide here: https://github.com/ItzCrazyKns/Perplexica?tab=readme-ov-file#ollama-connection-errors

**Comment by coderyiyang** [comment]
After multiple attempts, the ports were functioning normally, but Perplexica still failed to operate properly. The entire environment, including Docker, was therefore uninstalled and reinstallation of Ollama, OpenWebUI, and Perplexica was performed. This finally achieved a successful connection with the local model, and it is now operating normally. Anyway, thanks. Perplexica is a brilliant project!!

**Comment by ItzCrazyKns** [comment]
Happy searching!
