### ISSUE TITLE
Searches only in predefined domains

### ISSUE THREAD

**Issue by dobry21** [ItzCrazyKns/Perplexica#425]
I want to customize Perplexica to search in a specific field - such as law or medicine. Can I limit the search engine to only search for specific web pages and not the entire Internet? What I mean is that this option should be predefined in the system and the user should not have to specify it in the prompt.

**Comment by ItzCrazyKns** [comment]
Currently that is out of scope for the project, at least for now. You can search links by providing it in the query and ask to provide info on the topic you want to search. Additionally, you can see the list of engines in SearXNG to check if the website you want to search is present there if so, you can modify the engines in the code to make it search that specific website/field.
