### ISSUE TITLE
Unable to connect to ollama

### ISSUE THREAD

**Issue by dongcheng-lv** [ItzCrazyKns/Perplexica#427]
Unable to connect to ollama, After configuring the local service address to be saved, the GENERAL port in the configuration file automatically becomes 3-001 instead of the default 3001, the following is a screenshot of the equivalent configuration

![01](https://github.com/user-attachments/assets/e81fb1af-fd0e-4bdb-b8f3-5669e05ffcdf)
![02](https://github.com/user-attachments/assets/f68108ae-00b3-496e-8097-35da75b780a1)
![03](https://github.com/user-attachments/assets/f25cf603-7acf-4c0e-be6d-850b28ac8899)

**Comment by ItzCrazyKns** [comment]
That isn't an issue, TOML adds those to make it easier to read. Regarding Ollama follow this guide: https://github.com/ItzCrazyKns/Perplexica?tab=readme-ov-file#ollama-connection-errors
