### ISSUE TITLE
Custom base url for open Ai in config.toml

### ISSUE THREAD

**Issue by Virtualchronos** [ItzCrazyKns/Perplexica#428]
Since you can provide open ai custom url only in browser, that also means that you must re specify it in each browser you use perplexica from.

Unfortunately that also means that it is impossible to use perplexica from a phone since the config button doesn't exist on phone if like me you use custom openAi provider...

Can you implement custom openAi provider url in config.toml please, it would Greatly help

**Comment by ItzCrazyKns** [comment]
Please refer to https://github.com/ItzCrazyKns/Perplexica/issues/162
