### ISSUE TITLE
Image and video search disappear 🫥

### ISSUE THREAD

**Issue by Virtualchronos** [ItzCrazyKns/Perplexica#429]
I'm using perplexica with custom OpenAi api. I also tried with official open Ai api and it's the same.

When you do any search, video search and imagine search doesn't show anything. If you try to click on them, they simply glitch and then immediately vanished...

Didn't try with ollama since I couldn't connect it sorry 😔

**Comment by ItzCrazyKns** [comment]
What are the logs from the browser console?

**Comment by Virtualchronos** [comment]
453-036faabed6db8bf3.js:1 
        
        
       POST https://perplexica.XXX.XXX.com/api/images 500 (Internal Server Error)
onClick @ 453-036faabed6db8bf3.js:1
aS @ fd9d1056-7f47edce5fc91f7c.js:1
aN @ fd9d1056-7f47edce5fc91f7c.js:1
(anonymous) @ fd9d1056-7f47edce5fc91f7c.js:1
sw @ fd9d1056-7f47edce5fc91f7c.js:1
sS @ fd9d1056-7f47edce5fc91f7c.js:1
(anonymous) @ fd9d1056-7f47edce5fc91f7c.js:1
oK @ fd9d1056-7f47edce5fc91f7c.js:1
iL @ fd9d1056-7f47edce5fc91f7c.js:1
sN @ fd9d1056-7f47edce5fc91f7c.js:1
uE @ fd9d1056-7f47edce5fc91f7c.js:1
uS @ fd9d1056-7f47edce5fc91f7c.js:1
453-036faabed6db8bf3.js:1 
        
        
       POST https://perplexica.XXX.XXX.com/api/videos 500 (Internal Server Error)

**Comment by ItzCrazyKns** [comment]
And the logs from the backend?

**Comment by Virtualchronos** [comment]
config : 

[API_KEYS]
OPENAI = ""
GROQ = ""
ANTHROPIC = ""

[API_ENDPOINTS]
OLLAMA = ""
SEARXNG = "http://localhost:32768"

[GENERAL]
PORT = 3001
SIMILARITY_MEASURE = "cosine"



docker compose : 


services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://perplexica.XXXX.com/api
        - NEXT_PUBLIC_WS_URL=wss://perplexica.XXXX.com/ws
    image: itzcrazykns1337/perplexica-frontend:main
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:






I'm running it behind nginx proxu manager on alpine linux docker container but i tried on another machines with external local ip and no nginx proxy manager, the result is the same

**Comment by ItzCrazyKns** [comment]
Weird, Try going to `http://api_urk/api/models` and see if you're able to access it

**Comment by Virtualchronos** [comment]
is it a local url or an url anybody could use ? because I only got "this website is unreachable error"

**Comment by ItzCrazyKns** [comment]
> is it a local url or an url anybody could use ? because I only got "this website is unreachable error"
> 
> i first thaught that it was a personnal error but i also rented an OVH server to try perplexica on it and the problem is the same so i doubt it's my internet config or adguard who's messing with it

It should be `https://perplexica.xxxx.com/api` the URL you pass in the docker compose file.

**Comment by Virtualchronos** [comment]
{"status":"ok"}

**Comment by ItzCrazyKns** [comment]
Weird, which provider are you using?

**Comment by Virtualchronos** [comment]
you mean my internet provider ? 

SFR in france (but i also tried with bouygues aslo french provider and same result)

**Comment by ItzCrazyKns** [comment]
Chat model provider

**Comment by Virtualchronos** [comment]
oh ! ok ^^

Jan.ai in server mode with llama3.1-8b-instruct as AI model

**Comment by ItzCrazyKns** [comment]
You are on Discord I believe? Let us move on there. Its hard to have a conversation over here.

**Comment by Virtualchronos** [comment]
yup ! I'm comming
