### ISSUE TITLE
can not docker install

### ISSUE THREAD

**Issue by taozhiyuai** [ItzCrazyKns/Perplexica#43]
taozhiyu@603e5f4a42f1 Perplexica % docker compose up -d
[+] Building 376.5s (2/2) FINISHED                                    docker:desktop-linux
 => [searxng internal] load build definition from searxng.dockerfile                  0.0s
 => => transferring dockerfile: 155B                                                  0.0s
 => ERROR [searxng internal] load metadata for docker.io/searxng/searxng:latest     376.4s
------
 > [searxng internal] load metadata for docker.io/searxng/searxng:latest:
------
failed to solve: searxng/searxng: failed commit on ref "unknown-sha256:4b900712a1e6e62fb669f8b69fd132014029dce5d383a3a4ecfad59f18596197": "unknown-sha256:4b900712a1e6e62fb669f8b69fd132014029dce5d383a3a4ecfad59f18596197" failed size validation: 8149 != 7826: failed precondition

**Comment by ItzCrazyKns** [comment]
Hi, it looks like the problem is with Docker not being able to pull the metadata file and not with Perplexica. Please check your network settings. You can also look up Docker's documentation or search Google for more help.
