### ISSUE TITLE
Network mode is not properly working

### ISSUE THREAD

**Issue by derritter88** [ItzCrazyKns/Perplexica#436]
**Describe the bug**
I use Docker compose and modified the lines to run it on a network level:

```
        - NEXT_PUBLIC_API_URL=https://domain.local/api
        - NEXT_PUBLIC_WS_URL=wss://domain.local/wss
 ```

I am using an Apache httpd server as a proxy.

Anytime I try to open the page it's loading but it also tries to load models from local host: `http://127.0.0.1:3001/api/models`
Which won't work

**To Reproduce**

1. Git clone
2. Edit docker compose yml
3. `docker compose up -d`

**Expected behavior**
Everything should run through proxy server.

**Comment by vojkovic** [comment]
Had the same issue, I edited this file https://github.com/ItzCrazyKns/Perplexica/blob/dfb532e4d3c293664f6d61cf6ff0e540377226fa/app.dockerfile

and then built the images from the Dockerfile and it worked fine.

**Comment by derritter88** [comment]
Yeah when building it the error won't appear.
I just thought I mention it as the current way to run Perplexica is "just" pulling the image and run it - previously it was to build it and then run it.

**Comment by ItzCrazyKns** [comment]
I've mentioned that you need to use the exact command listed in the networking guide, it rebuilds images locally to use the new address. Please refer to the networking guide: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md

**Comment by derritter88** [comment]
Right - maybe it would make sense to mention the network link at the general installation readme?

**Comment by ItzCrazyKns** [comment]
It is there https://github.com/ItzCrazyKns/Perplexica?tab=readme-ov-file#expose-perplexica-to-network

**Comment by derritter88** [comment]
Yeah but I'd position it right after the Docker installation guidelines - before the manual installation guidlines

**Comment by ItzCrazyKns** [comment]
> Strangly i did follow network guide, but it is working intermittendly. somtimes it will request right ip address, sometimes it will try to read
> 
> ```
>     GET http://127.0.0.1:3001/api/models net::ERR_CONNECTION_REFUSED
> ```
> 
> This is without any changes to docker etc, just not consistently

After updating the IP in the compose file did you run `docker compose up -d --build` with the `--build` flag?
