### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by futurewin** [ItzCrazyKns/Perplexica#44]
**Describe the bug**
  start 
  can connet to ollama
  can connet to llama3:latest
  send the first msg say "hi" to modal, the modal can work fine.
  but send the second msg "hi,again" to modal, backend crashed.

error info:
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:676:13)
    at searchSearxng (Perplexica/dist/lib/searxng.js:11:17)
    at RunnableLambda.func (Perplexica/dist/agents/webSearchAgent.js:82:59)
    at Perplexica/node_modules/@langchain/core/dist/runnables/base.cjs:1385:44
    at MockAsyncLocalStorage.run (Perplexica/node_modules/@langchain/core/dist/singletons/index.cjs:10:9)
    at output (Perplexica/node_modules/@langchain/core/dist/runnables/base.cjs:1383:78)
    at new Promise (<anonymous>)
    at RunnableLambda._transform (Perplexica/node_modules/@langchain/core/dist/runnables/base.cjs:1382:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  input: 'undefined/search?format=json',
  code: 'ERR_INVALID_URL'

and i found after crashing, the gpu is still working  for a while 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot from 2024-05-01 20-57-31](https://github.com/ItzCrazyKns/Perplexica/assets/47633902/e6f8eef0-8df9-4b31-ab97-2f97072ac74d)
![Screenshot from 2024-05-01 20-49-54](https://github.com/ItzCrazyKns/Perplexica/assets/47633902/f76d6e69-2551-410a-b612-cbde51b88315)

**Additional context**

**Comment by futurewin** [comment]
and I found when I  used writing mode , it will not crashed.

but if i use all mode  ,it crashed

or i use writing mode, then click the search images buttons , it crashed.

and  i am using vpn to open internet , is it the reason?

**Comment by ItzCrazyKns** [comment]
Either the VPN is causing issues or you didn't defined the SearxNG API URL in the config file

**Comment by futurewin** [comment]
i used Non-Docker Installation to install Perplexica , i don't know how to fix this problem. and i used docker to install it again, then have another problem

yarn run v1.22.19
$ node dist/app.js
info: WebSocket server started on port 3001
(node:28) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.
(Use node --trace-deprecation ... to show where the warning was created)
info: Server is running on port 3001

**Comment by ItzCrazyKns** [comment]
That is not a problem ;-; its an issue from Yarn, I cannot help you with that. Additionally you won't need help for it, Perplexica would run completely fine and unaffected.
