### ISSUE TITLE
使用sudo docker compase up -d 报错

### ISSUE THREAD

**Issue by GOOD-N-LCM** [ItzCrazyKns/Perplexica#441]
**Describe the bug**
[+] Running 3/3
 ! perplexica-backend Warning  context canceled                                                                                                                   15.5s 
 ✘ searxng Error               Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout e...               15.5s 
 ! perplexica-frontend Warning context canceled                                                                                                                   15.5s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**To Reproduce**
sudo docker compose up -d

1. Go to 'docker compose up -d'
2. See error

**Expected behavior**

**Screenshots**
![企业微信截图_17302653032195](https://github.com/user-attachments/assets/06e7d4c6-03fe-4f6a-a904-381f43e50e73)

**Additional context**

**Comment by ItzCrazyKns** [comment]
Its a network issue and is unrelated to the project, contact Docker support.
