### ISSUE TITLE
searXGN  and  peroplexica   deploy

### ISSUE THREAD

**Issue by GOOD-N-LCM** [ItzCrazyKns/Perplexica#447]
**Is your feature request related to a problem? Please describe.**
searXGN and perplexica are deployed on two Ubuntu machines and communicate with each other

**Describe the solution you'd like**
I want to run the searXGN image on a ubuntu server, and run perplexica-backend and perplexica-frontend on another server, and enable them to access the communication

**Describe alternatives you've considered**
Make searXGN open to public network access

**Additional context**

**Comment by ItzCrazyKns** [comment]
You need to follow the networking guide and update URLs respectively. I cannot help you with that since its outside my support area.
