### ISSUE TITLE
http://localhost:3000/ just keep loading

### ISSUE THREAD

**Issue by sodiqidowu** [ItzCrazyKns/Perplexica#455]
**Describe the bug**
. http://localhost:3000/ keeps rolling

I followed the documentation to the last point but unfortunately, the page just keeps loading. Can anyone help, please? 

See screenshot
![Screenshot - 2024-11-07T200940 380](https://github.com/user-attachments/assets/50f3e6af-30c7-487b-9776-b9230c140591)

Thank you

**Comment by ItzCrazyKns** [comment]
What are the logs from the backend & browser console?

**Comment by sodiqidowu** [comment]
[log files.txt](https://github.com/user-attachments/files/17682499/log.files.txt)

I have attached the log files here. 
<img width="413" alt="Screenshot_3" src="https://github.com/user-attachments/assets/57dde560-7572-4dab-a588-cbdc91f24800">

**Comment by ItzCrazyKns** [comment]
You messed up the config.toml file, please re-clone the sample.config.toml file from the repository and replace the contents in the config.toml file with it. Then reconfigure the config. This should fix your issue, if you face any more problems feel free to reopen this issue.

**Comment by nanhoes** [comment]
same issue
