### ISSUE TITLE
httpx.TimeoutException in searxng module

### ISSUE THREAD

**Issue by flotenva** [ItzCrazyKns/Perplexica#46]
**Describe the bug**
I am receiving a `ERROR:searx.engines.wikidata: Fail to initialize` error when initialising the searxng module. I have attached a screenshot of the logs from the searxng docker container.

**Screenshots**
![image](https://github.com/ItzCrazyKns/Perplexica/assets/65992793/d6fe24a2-198a-42aa-98aa-52fd8bfd9859)

**Comment by ItzCrazyKns** [comment]
Please don't open any issues regarding SearxNG. SearxNG is working fine, it logs those messages because some engines might give timed out. **You don't need to worry about it**
