### ISSUE TITLE
NEXT_PUBLIC_API_URL not used when using pre-built Docker images

### ISSUE THREAD

**Issue by meb427** [ItzCrazyKns/Perplexica#460]
**Describe the bug**
Using pre-built images for docker-front env variable can't be overriden.
itzcrazykns1337/perplexica-frontend:main

**To Reproduce**

Docker compose setup:

perplexica-frontend:
    image: itzcrazykns1337/perplexica-frontend:main
    container_name: perplexica-frontend
    environment:
      - NEXT_PUBLIC_API_URL=https://perplexica-back.MYDOMAIN/api
      - NEXT_PUBLIC_WS_URL=wss://perplexica-back.MYDOMAIN
    depends_on:
      - perplexica-backend
    volumes:
      - ./perplexica-config.toml:/home/perplexica/config.toml      
    ports:
      - 3980:3000
    restart: unless-stopped

Chrome console
GET http://127.0.0.1:3001/api/models net::ERR_CONNECTION_REFUSED

Checking in container I See the env correctly set

/home/perplexica # env
NODE_VERSION=23.1.0
HOSTNAME=ebf749acf153
YARN_VERSION=1.22.22
SHLVL=1
HOME=/root
TERM=xterm-256color
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NEXT_PUBLIC_WS_URL=wss://perplexica-back.MYDOMAIN
LANG=C.UTF-8
NEXT_PUBLIC_API_URL=https://perplexica-back.MYDOMAIN/api
LC_ALL=C.UTF-8
PWD=/home/perplexica
/home/perplexica #

**Expected behavior**
ENV used if added in docker-compose.

**Screenshots**
N/A

**Additional context**
Ability to setup perplexica in remote servers and not rely on 127.0.0.1:3001 that seem hard coded or can't be overriden in pre-build images: itzcrazykns1337/perplexica-frontend:main

**Comment by Deathproof76** [comment]
Can confirm.
When I build the frontend image with a local ip instead of 127.0.0.1:3001 (for example):

```
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.0.208:3001/api
        - NEXT_PUBLIC_WS_URL=ws://192.168.0.208:3001
```
        
I'm able to use perplexica from another device in my lan. If I only change the env while using the prebuilt image or build with 127.0.0.1:3001 as arg, it throws the same error as op.

**Comment by alexandrekm** [comment]
I can confirm that the same issue happens to me.

**Comment by timoa** [comment]
I worked on rewriting the Docker images (reducing their size by -65% and securing them) and also fixed the issue with the ENV vars so that they can be used without rebuilding the Docker images.

It uses the `.env` file outside the Docker image. The `.env` is loaded now by Docker compose instead of the Docker build time.

The PR is here: https://github.com/ItzCrazyKns/Perplexica/pull/465.

I did this PR because I'm working on the Helm Chart to deploy Perplexica on Kubernetes, and I had this issue with the official Docker images.

**Comment by ItzCrazyKns** [comment]
Please refer to: https://github.com/ItzCrazyKns/Perplexica/issues/388

**Comment by realies** [comment]
@ItzCrazyKns reopen the issue because pre-build Docker images can't be used with anything other than 127.0.0.1.

**Comment by ItzCrazyKns** [comment]
> [@ItzCrazyKns](https://github.com/ItzCrazyKns) reopen the issue because pre-build Docker images can't be used with anything other than 127.0.0.1.

NextJS hardcodes the public env variables into the Javascript bundle, there's no way to change that other than rebuilding
