### ISSUE TITLE
Question: docker hub images

### ISSUE THREAD

**Issue by phirestalker** [ItzCrazyKns/Perplexica#469]
I found perplexica on docker hub. I want to know if it is you, since it is using a name very similar to the one here in github. If it is yours, can we use it instead of pulling from this repository?

Here is the images I found.
https://hub.docker.com/r/itzcrazykns1337/perplexica-frontend
https://hub.docker.com/r/itzcrazykns1337/perplexica-backend

**Comment by ItzCrazyKns** [comment]
Yes, I am indeed that person and the repository by default will pull those images. Happy searching!

**Comment by phirestalker** [comment]
HA! I see that now, the build directives threw me off. They would only be used if I specifically ran a build command.
