### ISSUE TITLE
Sources always point to example.com

### ISSUE THREAD

**Issue by chandrakanthm** [ItzCrazyKns/Perplexica#470]
**Describe the bug**
The search query always returns sources as example.com like in the  screenshot :
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/79c07f8a-9011-4d27-9d9d-551b9e6e5189">

**To Reproduce**
git clone https://github.com/ItzCrazyKns/Perplexica
docker compose top -d 
use groq api keys 
and then go to localhost:3000 , search with query.

**Expected behavior**

it should give the exact references that are used in the response.

**Screenshots**
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/79c07f8a-9011-4d27-9d9d-551b9e6e5189">

**Additional context**

**Comment by chandrakanthm** [comment]
couple of months ago this used to work as expected , I am not sure what has changed . I could not updated instructions  in the readme

**Comment by chandrakanthm** [comment]
it is working as expected with models with lager parameters , is this an expected behavior?

**Comment by ItzCrazyKns** [comment]
Yeah, smaller models tend to not understand the prompt correctly, for the same reason I've removed Llama 3.2 1B from the providers list in Groq and soon tend to remove the 3B version. They are small enough to misunderstand the prompt and start outputting random stuff.
