### ISSUE TITLE
I'm getting an error while building frontend

### ISSUE THREAD

**Issue by amour86** [ItzCrazyKns/Perplexica#473]
0.864 yarn run v1.22.22
0.926 $ next build
2.165 Attention: Next.js now collects completely anonymous telemetry regarding usage.
2.166 This information is used to shape Next.js' roadmap and prioritize features.
2.166 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2.166 https://nextjs.org/telemetry
2.166
2.364 ▲ Next.js 14.1.4
2.364
2.493 Creating an optimized production build ...
6.130 (node:41) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.
6.130 (Use node --trace-deprecation ... to show where the warning was created)
18.58 Failed to compile.
18.58
18.58 ./node_modules/@headlessui/react/dist/components/popover/popover.js + 9 modules
18.58 Unexpected end of JSON input
18.58
18.97
18.97 > Build failed because of webpack errors
19.02 error Command failed with exit code 1.
19.02 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ItzCrazyKns** [comment]
Looking into it, trying to replicate.

**Comment by ItzCrazyKns** [comment]
Shall be fixed now.

**Comment by amour86** [comment]
What should I do now to apply your fix, sorry for this question

**Comment by ItzCrazyKns** [comment]
Delete the existing version of Perplexica you've cloned and follow the installation docs again.

**Comment by amour86** [comment]
May I know what was the reason behind this error, just for learning purposes

**Comment by ItzCrazyKns** [comment]
> May I know what was the reason behind this error, just for learning purposes

We were using the `node:alpine` image with no version specified. The NodeJS Docker team regularly push updates for the images (and versions as well). Since there was no version specified, it would always run the latest version of NodeJS. There may be incompatibilities in how dependencies are resolved or executed. So, I've fixed it to a specific NodeJS version in which the yarn lock file was created.

**Comment by amour86** [comment]
Issue fixed :)
