### ISSUE TITLE
Add openai api format support?

### ISSUE THREAD

**Issue by redreamality** [ItzCrazyKns/Perplexica#475]
**Is your feature request related to a problem? Please describe.**
I have a local model which served use Xinference. it is openai-compatible.   However ollama is often not.

**Describe the solution you'd like**
Add openai-compatible api support:
Customizing OPENAI_BASE_URL, OPENAI_KEY

**Comment by ItzCrazyKns** [comment]
Use the custom OpenAI provider from the settings menu.

**Comment by ParaplegicRacehorse** [comment]
Having to do this EVERY time I visit it in my browsers that automatically delete site-settings/permissions/cookies/etc is a PITA.

Please expose this in the config files.

My local LLM (running [Kobold-cpp](https://github.com/LostRuins/koboldcpp)) exposes an openai compatible api in addition to its much more capable and full-featured own api. I'm not asking for special kcpp api support; just the ability to point the OPENAI_BASE_URL at it in the config files so myself and my family don't need to know to change the setting every single time we load the Perplexity webui.

**Comment by TomLucidor** [comment]
@ItzCrazyKns please add a config file parameter instead of relying on the UX, there are other people giving the same issues

**Comment by ItzCrazyKns** [comment]
Custom OpenAI API can be used from the settings file now
