### ISSUE TITLE
Groq options unavailable

### ISSUE THREAD

**Issue by hamelcubsfan** [ItzCrazyKns/Perplexica#48]
Updated the config with Groq API Key, but UI not reflecting, nor showing a place to change to Groq, insert key, etc.
<img width="694" alt="1" src="https://github.com/ItzCrazyKns/Perplexica/assets/26424807/e4e60ed3-13a0-4c44-a1bf-533b63ffc19a">

**Comment by ItzCrazyKns** [comment]
Seems like you are running an old version of Perplexica. Please update to the latest version

**Comment by hamelcubsfan** [comment]
I was am running 1.1, but the --build command didn't stick.
TY
