### ISSUE TITLE
Wish there were better instructions for installing Ollama with Rocm support for Perplexica

### ISSUE THREAD

**Issue by amd1890** [ItzCrazyKns/Perplexica#488]
**Is your feature request related to a problem? Please describe.**
I can get perplexica to work, but it is so incredibly slow. I know I can use GPT4ALL with Vulkan drivers and get 10 tokens per second, which isn't that bad. Perplexica is running at 1/10th of the speed, which means it's probably using ollama in CPU mode.

**Describe the solution you'd like**
I have probably spent over 20 hours trying to figure out how to get Perplexica to work with AMD Rocm drivers and my Ryzen GPU. I really wish there were a standardized solution for AMD users who have a Ryzen chipset or other non-standard GPU AMD chipset so that it could just work in Docker. I'm not a developer, but can sudo bash ./something.sh with the best of them.

**Describe alternatives you've considered**
I tried installing local Rocm ollama programs in docker, I tried updating drivers, I tried so many things. I kept running into errors. I've asked other people on github too. I really like Perplexity.ai but am concerned about how much data it could be collecting about me and would really like to have perlexica as a local solution.

**Additional context**
For non-developers who like github and have Rocm, would be great if there were a "best solution" to this problem. If I were smarter and more experienced, I could likely figure out something on my own, but haven't been able to do it.

**Comment by amd1890** [comment]
I have figured out now how to get ollama not in docker running using the amd ryzen gpu, but I still don't know how to run it in docker so that it uses the gpu or even if that's necessary.

I was able to run ollama in a docker without the GPU and get perplexica to work. This is really hard! :'-(

**Comment by ItzCrazyKns** [comment]
Not something I can help you with.
