### ISSUE TITLE
error: Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by moshilangzi** [ItzCrazyKns/Perplexica#490]
**Describe the bug**

post request：
curl -X POST http://localhost:3001/api/search \
  -H "Content-Type: application/json" \
  -d '{
    "chatModel": {
      "provider": "ollama",
      "model": "mbenhamd/qwen2.5-7b-instruct-cline-128k-q8_0:latest"
    },
    "embeddingModel": {
      "provider": "ollama",
      "model": "bge-m3:latest"
    },
    "optimizationMode": "speed",
    "focusMode": "webSearch",
    "query": "hello",
    "history": []
  }'

error: Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'map')

**Comment by ItzCrazyKns** [comment]
Fixed by https://github.com/ItzCrazyKns/Perplexica/commit/ecad0655779e75699223d0a7ff7e0775491e6345, please follow the [update guide](https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/UPDATING.md).
