### ISSUE TITLE
No settings on Mobile

### ISSUE THREAD

**Issue by itsmebcc** [ItzCrazyKns/Perplexica#499]
Cannot access settings on mobile device. Android phone specifically.

**Comment by ItzCrazyKns** [comment]
Cannot reproduce, please update Perplexica to the latest version

**Comment by delfireinoso** [comment]
On iPhone is working after the latest releases.

**Comment by theronypony** [comment]
I'm having the same issue - after update the settings gear icon briefly appeared on mobile, but now it's missing again. My config.toml is below. I am trying to use it with ollama.

`[API_KEYS]
OPENAI = "xxxxxx"

[API_ENDPOINTS]
OLLAMA = "http://host.docker.internal:11434"
SEARXNG = "http://searxng:8080"

[GENERAL]
PORT = 3001
SIMILARITY_MEASURE = "cosine"`

**Comment by ItzCrazyKns** [comment]
> I'm having the same issue - after update the settings gear icon briefly appeared on mobile, but now it's missing again. My config.toml is below. I am trying to use it with ollama.
> 
> Confirmed I'm using the latest version on docker. Have removed images and rebuilt.
> 
> ```
> [API_KEYS]
> OPENAI = "xxxxxx"
> 
> [API_ENDPOINTS]
> OLLAMA = "http://host.docker.internal:11434"
> SEARXNG = "http://searxng:8080"
> 
> [GENERAL]
> PORT = 3001
> SIMILARITY_MEASURE = "cosine"
> ```

Your config file is old, please update it to the latest changes. Check the sample.config.toml file and rename it as config.toml then configure it. Are you on the latest version?
