### ISSUE TITLE
API Calls to Perplexica Hang Without Response When Using Docker Setup  

### ISSUE THREAD

**Issue by sreehariv-code** [ItzCrazyKns/Perplexica#503]
I recently started using Perplexica with the Docker configuration as outlined in the documentation. However, when triggering API calls via the API testing platform (APIdog), the platform continuously loads without providing any response.  

Here are the details of my setup:  

- **OS**: Ubuntu 22.04  
- **RAM**: 16 GB  
- **CPU**: Intel i5 13th Gen (1335U) 12-core  
- **GPU**: None  

Perplexica is running within a Docker instance, and the UI is accessible at `localhost:3000`, as expected. I am using the **Ollama model** with the following configuration:  

- **Chat Model**: `llama3:latest`  
- **Embedding Model**: `nomic-embeded-text:latest`  

Has anyone encountered this issue or knows a solution? Any help would be appreciated!

**Comment by ItzCrazyKns** [comment]
What is your request body?

**Comment by sreehariv-code** [comment]
There isn't any response being generated
![Screenshot from 2024-12-04 15-38-15](https://github.com/user-attachments/assets/148d6f5f-29e6-4204-8cf5-8688ea7ebc45)

I hope this would help. If any other data related to this issue is needed, feel free to ask

**Comment by ItzCrazyKns** [comment]
What are the logs?

**Comment by sreehariv-code** [comment]
Did you mean the docker logs ?

**Comment by sreehariv-code** [comment]
I have restarted the docker backend service and these are the recent logs

```bash
yarn run v1.22.22
$ npm run db:push && node dist/app.js

> perplexica-backend@1.10.0-rc1 db:push
> drizzle-kit push sqlite

drizzle-kit: v0.22.7
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file '/home/perplexica/drizzle.config.ts'
[⣷] Pulling schema from database...
[✓] Pulling schema from database...

[i] No changes detected
info: WebSocket server started on port 3001
info: Server is running on port 3001
error: Error at generating documents from links: Invalid URL
error: Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'map')


```

**Comment by sreehariv-code** [comment]
> What are the logs?
```
yarn run v1.22.22
$ npm run db:push && node dist/app.js

> perplexica-backend@1.10.0-rc1 db:push
> drizzle-kit push sqlite

drizzle-kit: v0.22.7
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file '/home/perplexica/drizzle.config.ts'
[⣷] Pulling schema from database...
[✓] Pulling schema from database...

[i] No changes detected
info: WebSocket server started on port 3001
info: Server is running on port 3001
error: Error at generating documents from links: Invalid URL
error: Unhandled Rejection at: [object Promise], reason: TypeError: Cannot read properties of undefined (reading 'map')
```

**Comment by ItzCrazyKns** [comment]
Can you follow the update guide and update Perplexica to the latest version, I published a fix for this issue a while ago. How to update: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/UPDATING.md

**Comment by sreehariv-code** [comment]
Hi @ItzCrazyKns , The issue still persists in my machine. Still I am not being able to access the API services. Theses are the current logs that I have obtained after rebuilding the docker image

````bash
sudo docker logs 23ae11348065
yarn run v1.22.22
$ npm run db:push && node dist/app.js

> perplexica-backend@1.10.0-rc2 db:push
> drizzle-kit push sqlite

drizzle-kit: v0.22.7
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file '/home/perplexica/drizzle.config.ts'
[⣷] Pulling schema from database...
[✓] Pulling schema from database...

[i] No changes detected
info: WebSocket server started on port 3001
info: Server is running on port 3001
error: Error at generating documents from links: Invalid URL
yarn run v1.22.22
$ npm run db:push && node dist/app.js

> perplexica-backend@1.10.0-rc2 db:push
> drizzle-kit push sqlite

drizzle-kit: v0.22.7
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file '/home/perplexica/drizzle.config.ts'
[⣷] Pulling schema from database...
[✓] Pulling schema from database...

[i] No changes detected
info: WebSocket server started on port 3001
info: Server is running on port 3001
error: Error at generating documents from links: Invalid URL
```

There is no response obtaining in the API testing applications (APIdog). Are there any solution to this issue or is it being occurred from my end due to any wrong configuration that I have provided ?

**Comment by ItzCrazyKns** [comment]
> Hi @ItzCrazyKns , The issue still persists in my machine. Still I am not being able to access the API services. Theses are the current logs that I have obtained after rebuilding the docker image
> 
> ```shell
> sudo docker logs 23ae11348065
> yarn run v1.22.22
> $ npm run db:push && node dist/app.js
> 
> > perplexica-backend@1.10.0-rc2 db:push
> > drizzle-kit push sqlite
> 
> drizzle-kit: v0.22.7
> drizzle-orm: v0.31.2
> 
> No config path provided, using default path
> Reading config file '/home/perplexica/drizzle.config.ts'
> [⣷] Pulling schema from database...
> [✓] Pulling schema from database...
> 
> [i] No changes detected
> info: WebSocket server started on port 3001
> info: Server is running on port 3001
> error: Error at generating documents from links: Invalid URL
> yarn run v1.22.22
> $ npm run db:push && node dist/app.js
> 
> > perplexica-backend@1.10.0-rc2 db:push
> > drizzle-kit push sqlite
> 
> drizzle-kit: v0.22.7
> drizzle-orm: v0.31.2
> 
> No config path provided, using default path
> Reading config file '/home/perplexica/drizzle.config.ts'
> [⣷] Pulling schema from database...
> [✓] Pulling schema from database...
> 
> [i] No changes detected
> info: WebSocket server started on port 3001
> info: Server is running on port 3001
> error: Error at generating documents from links: Invalid URL
> ```
> 
> There is no response obtaining in the API testing applications (APIdog). Are there any solution to this issue or is it being occurred from my end due to any wrong configuration that I have provided ? 
> ```

What LLM are you using?

**Comment by sreehariv-code** [comment]
I am currently using **llama3:latest** model in **Ollama** on my **local machine**
