### ISSUE TITLE
After successfully running the Docker container, I keep getting errors when trying to call the service through the API.

### ISSUE THREAD

**Issue by NeuromancerAQ** [ItzCrazyKns/Perplexica#509]
After running Docker normally, I can access the service through the frontend at localhost:3000, but I get errors when trying to use the API on the backend.

![image](https://github.com/user-attachments/assets/b246f9ef-a5db-4470-95a0-0a4427e9563f)

Here is my config:
![image](https://github.com/user-attachments/assets/1f85e184-62ae-407d-98cb-b7dfb1fca664)

**Comment by ItzCrazyKns** [comment]
Not able to replicate, can you provide more details?

**Comment by ItzCrazyKns** [comment]
Also try following the update guide to update Perplexica to the latest version and see if that helps as I pushed a fix to this issue a while ago: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/UPDATING.md

**Comment by NeuromancerAQ** [comment]
> Also try following the update guide to update Perplexica to the latest version and see if that helps as I pushed a fix to this issue a while ago: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/UPDATING.md


It worked! It might be due to some configuration changes I made. Thank you very much, and have a nice day!
