### ISSUE TITLE
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by futurewin** [ItzCrazyKns/Perplexica#51]
**Describe the bug**
use Docker to install backend ,but after run "docker run perplexica-perplexica-backend" ,show this message "

yarn run v1.22.19
$ node dist/app.js
info: WebSocket server started on port 3001
(node:28) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: Server is running on port 3001

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by futurewin** [comment]
can't connect to ollama ,can't choose modals

**Comment by futurewin** [comment]
system: UBUNTU 24.04

config.toml :

[GENERAL]
CHAT_MODEL_PROVIDER = "ollama"
CHAT_MODEL = "llama3:latest"
PORT = 3001
SIMILARITY_MEASURE = "cosine"

[API_KEYS]
OPENAI = ""
GROQ = ""

[API_ENDPOINTS]
SEARXNG = "http://localhost:32768"
OLLAMA = "http://host.docker.internal:11434"

**Comment by ItzCrazyKns** [comment]
Its an issue from yarn, please don't open issues regarding warnings
