### ISSUE TITLE
Using Perplexica as Web Search RAG Source for Local LLM

### ISSUE THREAD

**Issue by bright-arparwut** [ItzCrazyKns/Perplexica#510]
# Using Perplexica as Web Search RAG Source for Local LLM

## Context
I'm working on a RAG system that currently uses a local vector database (Qdrant). I recently discovered Perplexica, an open-source alternative to Perplexity that works with Ollama models, and I'm interested in using it as a web search RAG source instead of relying solely on a local vector database.

## Current Architecture
- Backend: Python with LangChain
- LLM: Ollama
- Vector Database: Qdrant
- RAG System: Custom implementation with HyDE

## Technical Challenge
While Perplexica looks promising, it appears to be primarily UI-based. I need to:
1. Programmatically send queries to Perplexica
2. Collect and process the search results
3. Integrate these results as context for my local LLM

## Questions
1. **API Access**: Is there a way to interact with Perplexica programmatically, possibly through an API or command-line interface? (Yes I saw the API doc, but it's really confusing for me)

2. **Alternative Approaches**: If direct API access isn't available, what would be the recommended approach for:
   - Sending queries programmatically
   - Capturing search results

## Looking For
1. Technical guidance on the best approach
2. Experience from anyone who has done similar integrations
3. Insights into potential challenges and pitfalls
4. Best practices for this type of integration

Thank you in advance for any insights or suggestions!

**Comment by ItzCrazyKns** [comment]
This documentation has everything you need to know to interact with Perplexica programatically. All you need to do is just send a post requestto an endpoint with some parameters and Perplexica would return you an answer.

Docs: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/API/SEARCH.md

**Comment by bright-arparwut** [comment]
Thanks for your support
เมื่อ พ. 11 ธ.ค. 2567 เวลา 12:28 ItzCrazyKns ***@***.***>
เขียนว่า:
