### ISSUE TITLE
Perplexica access via domain connected by cloudflared tunnel results in spinning wheel.

### ISSUE THREAD

**Issue by MikeNatC** [ItzCrazyKns/Perplexica#511]
**Describe the bug**
I have a local instance of Perplexica running on Docker Desktop on a Windows 11 local machine. I have a cloudflared tunnel set up connecting to the Perplexica docker container. When I access Perplexica via the domain, everything loads except the search bar which shows a spinning wheel. 

**To Reproduce**

1. Follow networking guide to set up such that Perplexica runs on devices on the network. Test and confirm that Perplexica works on the local machine's network. 
2. Create a cloudflared tunnel to the Perplexica instance running in a docker container. 
3. Set the tunnel to connect via domain address. 
4. Access the domain. 
5. See spinning wheel at the place where the search bar should appear. 

**Expected behavior**
The Perplexica search bar should load. 

**Screenshots**
The spinning wheel: 

![image](https://github.com/user-attachments/assets/8aced44b-fb63-4537-8ff5-17d9a1af2ab9)

**Additional context**
It would be helpful if we can allow remote access to the local instance of Perplexica via Cloudflared and to secure it via Nginx and procure an SSL certificate for the website.

**Comment by ItzCrazyKns** [comment]
Follow the networking guide, this is not something I can help you with. Other people are able to use it over SSL via NGINX.

**Comment by MikeNatC** [comment]
Thanks for the comments @ItzCrazyKns and @amour86 

I did follow the guide [here](https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md). 

I managed to get it working for devices connected to the local network but not through the Cloudflare tunnel, this is before setting up NGINX and the SSL certificate.

**Comment by amour86** [comment]
share the values you set for the below
NEXT_PUBLIC_WS_URL
NEXT_PUBLIC_API_URL
SEARXNG_API_URL

**Comment by MikeNatC** [comment]
@amour86 
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      args:
        - NEXT_PUBLIC_API_URL=http://10.71.1.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://10.71.1.1:3001

**Comment by amour86** [comment]
@MikeNatC 
As expected

Searxng url is HTTP and the websocket is not a secured websocket WSS

You should see in your browser’s developer options console an error related to mixed content error

Because you are using. Https with HTTP

I assume you are using https through cliudflare tunnel

**Comment by MikeNatC** [comment]
I see. 

So in other words, I need to finish setting up NGINX and obtain an SSL certificate before this will work? Sorry for all these questions - I've basically no experience with these things and I learnt about cloudflare with NGINX and SSL by following a guide on LibreChat and was hoping to replicate that here.
