### ISSUE TITLE
OpenWebUI and Perplexica on same machine

### ISSUE THREAD

**Issue by IMJONEZZ** [ItzCrazyKns/Perplexica#522]
**Describe the bug**
After following the networking advice and making sure that the ports do not conflict, I can access searxng on port 4000, but port 3002 (backend server) just gives "Cannot GET /" and 3001 (frontend) gives "Connection Reset" and "Unable to connect" I will include the config.toml and docker-compose.yaml and docker compose logs -f.

**To Reproduce**
git clone perplexica
cp sample.config.toml config.toml

nano config.toml ->
    PORT = 3002 # changed from 3001 because of the conflict on port 3000
    OLLAMA = "http://<ip-address>:11434" # Based on networking.md

nano docker-compose.yaml ->
    perplexica-backend:
        environment:
            - SEARXNG_API_URL=http://<ip-address>:8080 # Changed to expose searxng to other services
        ports:
            - 3002:3002 # changed in accordance with the backend port
    perplexica-frontend:
        args:
            - NEXT_PUBLIC_API_URL=http://<ip-address>:3002/api # Changed to expose on local network
            - NEXT_PUBLIC_WS_URL=http://<ip-address>:3002 # Changed to expose on local network
        ports:
            - 3001:3001 # changed to be on 3000 so as not to conflict with OpenWebui

docker compose up -d --build

visit http://localhost:3001 -> Connection Reset
visit http://localhost:3002 -> 
visit http://localhost:4000 -> Functions Normally (great)

**Expected behavior**
I expected to see the front end on port 3001, especially after changing the port. I also expected docker compose logs -f to not show the front end trying to run on localhost:3000.

**Screenshots**
![Screenshot 2024-12-14 232857](https://github.com/user-attachments/assets/bbb8a46f-1833-48d1-9d0b-3ae930d8bcb1)
![Screenshot from 2024-12-14 23-31-41](https://github.com/user-attachments/assets/613750c4-7227-4af8-8e63-9bf95676f367)

**Additional context**
Nothing, just that I'm very motivated to get this solved since I really like the idea of this service!

**Comment by ItzCrazyKns** [comment]
> **Describe the bug** After following the networking advice and making sure that the ports do not conflict, I can access searxng on port 4000, but port 3002 (backend server) just gives "Cannot GET /" and 3001 (frontend) gives "Connection Reset" and "Unable to connect" I will include the config.toml and docker-compose.yaml and docker compose logs -f.
> 
> **To Reproduce** git clone perplexica cp sample.config.toml config.toml
> 
> nano config.toml -> PORT = 3002 # changed from 3001 because of the conflict on port 3000 OLLAMA = "http://:11434" # Based on networking.md
> 
> nano docker-compose.yaml -> perplexica-backend: environment: - SEARXNG_API_URL=http://:8080 # Changed to expose searxng to other services ports: - 3002:3002 # changed in accordance with the backend port perplexica-frontend: args: - NEXT_PUBLIC_API_URL=http://:3002/api # Changed to expose on local network - NEXT_PUBLIC_WS_URL=http://:3002 # Changed to expose on local network ports: - 3001:3001 # changed to be on 3000 so as not to conflict with OpenWebui
> 
> docker compose up -d --build
> 
> visit http://localhost:3001 -> Connection Reset visit http://localhost:3002 -> visit http://localhost:4000 -> Functions Normally (great)
> 
> **Expected behavior** I expected to see the front end on port 3001, especially after changing the port. I also expected docker compose logs -f to not show the front end trying to run on localhost:3000.
> 
> **Screenshots** ![Screenshot 2024-12-14 232857](https://private-user-images.githubusercontent.com/46764336/395835960-bbb8a46f-1833-48d1-9d0b-3ae930d8bcb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDU1NjksIm5iZiI6MTczNDI0NTI2OSwicGF0aCI6Ii80Njc2NDMzNi8zOTU4MzU5NjAtYmJiOGE0NmYtMTgzMy00OGQxLTlkMGItM2FlOTMwZDhiY2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDA2NDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxOTA5NGRjNDk4NjAwZjhmNWZhYjI1N2NhZGY2NWYxNTIxZTQ5ODFjYjgyZmYxYWNkNWEyZWJiMzJjY2NlYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A6m8TkLB0jFjDSz9YRo2Vs6tUGtzs7XTOaNYzj-AVqU) ![Screenshot from 2024-12-14 23-31-41](https://private-user-images.githubusercontent.com/46764336/395836188-613750c4-7227-4af8-8e63-9bf95676f367.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDU1NjksIm5iZiI6MTczNDI0NTI2OSwicGF0aCI6Ii80Njc2NDMzNi8zOTU4MzYxODgtNjEzNzUwYzQtNzIyNy00YWY4LThlNjMtOWJmOTU2NzZmMzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDA2NDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNzAzNWU0YTFiNDI3NmQxOGIxOTM1ZThmOWM2MTRhNWNiMGY4OTZjNzY3NTdhZjhhYmFjMzAyYzJmNjk1NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ztgzOeHKy98spUzaqtHeRqOC8_mExmru_BSzdCDrDY)
> 
> **Additional context** Nothing, just that I'm very motivated to get this solved since I really like the idea of this service!

You're not supposed to change the internal port for the container, change `3001:3001` to `3001:3000` and run the compose file.
