### ISSUE TITLE
Perplexica still uses llama 3.1 on groq, when it's getting retired

### ISSUE THREAD

**Issue by KhazAkar** [ItzCrazyKns/Perplexica#525]
**Describe the bug**
Currently, perplexica is showing 'llama 3.1 70b' as model on groq, when it's being sunset according to deprecations page here: https://console.groq.com/docs/deprecations

**To Reproduce**

1. Go to 'Settings'
2. Setup groq as cloud API provider
3. Click on 'Chat model'
4. See llama 3.1

**Expected behavior**
See llama 3.3. instead

**Screenshots**
![image](https://github.com/user-attachments/assets/8dfc80f3-647f-44d2-91b4-8fefc2f22bbd)

**Comment by ItzCrazyKns** [comment]
Fixed by https://github.com/ItzCrazyKns/Perplexica/pull/523
