### ISSUE TITLE
Use Kagi search as search provider? 

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [ItzCrazyKns/Perplexica#528]
**Is your feature request related to a problem? Please describe.**
Instead of using SearxNG using Kagi would be a good alternative. Kagi is a privacy respecting search engine.

**Describe the solution you'd like**
Ability to use Kagi as a search provider and add the Kagi API key. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ItzCrazyKns** [comment]
For now I want to keep most parts of the project as open as possible, SearXNG is open source but the engines it uses isn't but it sends the queries in an anonymous format so its nearly impossible to track them. I might consider adding support for other search engines later.
