### ISSUE TITLE
v1.1.0 error: Error loading groq models

### ISSUE THREAD

**Issue by doudouxiaocai** [ItzCrazyKns/Perplexica#53]
**Describe the bug**

**To Reproduce**
use docker,groq key
1. Go to '(http://localhost:3000/)'
2. Click on 'setting'
![报错](https://github.com/ItzCrazyKns/Perplexica/assets/4180956/a9b64099-8d53-4c45-8027-7e43afa67c1e)

**Comment by ItzCrazyKns** [comment]
You need to add OpenAI API key as well to use Groq models because we make use of OpenAI embeddings. I am working on adding support for local embedding models. After updating the config rebuild the images (make sure the previous ones are deleted)
