### ISSUE TITLE
Support other search engines like Google/DuckDuckGo

### ISSUE THREAD

**Issue by cocktailpeanut** [ItzCrazyKns/Perplexica#58]
**Is your feature request related to a problem? Please describe.**

Currently Perplexica only supports SearxNG as the base search engine, but it's the biggest hurdle in getting started. Just quickly reading through the code it looks like the core value of the project is the way it orchestrates LLMs with a search engine API (SearxNG), and supporting other search engine APIs like Duckduckgo or Google shouldn't be that much work, while making it 10x easier to get started with Perplexica, especially when trying to run this on a local computer (instead of trying to run this as some service)

**Describe the solution you'd like**

Support other search engine APIs

**Describe alternatives you've considered**

No alternative

**Comment by ItzCrazyKns** [comment]
I don't think SearXNG is a hurdle in getting started. The Docker compose files provided are very easy to set-up and can be done in just 1 command. SearXNG itself gathers information from Google, Bing, DuckDuckGo, Brave and a lot of other search engines. The main reason to use SearXNG is to ensure privacy. Additionally SearXNG helps in providing other search engines that are useful for the focus modes.

**Comment by Explosion-Scratch** [comment]
@ItzCrazyKns Can we reopen this? I would find this feature useful, even if it's not selected by default. I'm happy with SearXNG as the default if you value privacy, but being able to use a custom search engine would be highly beneficial
