### ISSUE TITLE
ollama 0.1.26 provide "bert" and "nomic-bert" embeddings，it's very quick, can add these embeddings to the groq or ollama service provider?

### ISSUE THREAD

**Issue by perlinson** [ItzCrazyKns/Perplexica#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ItzCrazyKns** [comment]
Yes, you can just select the embedding model you want to use. You just need to make sure that you have the model pulled from the Ollama library and Perplexica would display it

**Comment by edisonzf2020** [comment]
Still can't select the embedding model by docker
version 1.3.2
