### ISSUE TITLE
Still can't select the embedding model by docker

### ISSUE THREAD

**Issue by edisonzf2020** [ItzCrazyKns/Perplexica#65]
Still can't select the embedding model by docker
version 1.3.2

_Originally posted by @edisonzf2020 in https://github.com/ItzCrazyKns/Perplexica/issues/63#issuecomment-2094833397_

**Comment by mikes-bowden** [comment]
Be sure to clear your DevTools > Application > Local Storage -- Right-click and delete all of them. Then hard refresh. 

Mac: cmd + shft + R
Windows: ctrl + shft + R

**Comment by ItzCrazyKns** [comment]
Hi, the version 1.3.3 will fix your issue. If you face the error again feel free to re-open this issue.

**Comment by mehdi-belkhayat** [comment]
Hi, on my linux with v1.8.1, everything is fine except Embedding Model which is still blocked on 'invalid provider', how can i do to overcome the problem please

**Comment by ItzCrazyKns** [comment]
> Be sure to clear your DevTools > Application > Local Storage -- Right-click and delete all of them. Then hard refresh.
> 
> Mac: cmd + shft + R Windows: ctrl + shft + R
^^

**Comment by mehdi-belkhayat** [comment]
Thanks ! so much
