### ISSUE TITLE
Chat on OpenAI and embedding on Ollama

### ISSUE THREAD

**Issue by wwjCMP** [ItzCrazyKns/Perplexica#70]
This is completely feasible, but it cannot be implemented in the settings at present.

**Comment by ItzCrazyKns** [comment]
It is completely possible, you just need to change the embedding model provider to Ollama and chat model to OpenAI

**Comment by NeverOccurs** [comment]
> It is completely possible, you just need to change the embedding model provider to Ollama and chat model to OpenAI

is it possible to use custom openai embedding?
