### ISSUE TITLE
How can I change the port for perplexica-frontend and perplexica-backend?

### ISSUE THREAD

**Issue by wwjCMP** [ItzCrazyKns/Perplexica#71]
I want to change their ports to 3010 and 3011 respectively, how should I do it? I have made changes to the corresponding parts of the docker-compose.yaml and config.toml files, but the web page still cannot be opened correctly.

**Comment by wwjCMP** [comment]
[GENERAL]
PORT = 3011 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

**Comment by wwjCMP** [comment]
services:
  searxng:
    build:
      context: .
      dockerfile: searxng.dockerfile
    expose:
      - 4000
    ports:
      - 4000:8080
    networks:
      - perplexica-network

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    expose:
      - 3011
    ports:
      - 3011:3011
    networks:
      - perplexica-network

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3011/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3011
    depends_on:
      - perplexica-backend
    expose:
      - 3010
    ports:
      - 3010:3010
    networks:
      - perplexica-network

networks:
  perplexica-network:

**Comment by ItzCrazyKns** [comment]
You need to rebuild the images, making sure the previous ones are deleted

**Comment by wwjCMP** [comment]
![image](https://github.com/ItzCrazyKns/Perplexica/assets/32979859/b7fba2a1-31b6-4363-8530-dc10eeb8aa76)

**Comment by ItzCrazyKns** [comment]
> ![image](https://private-user-images.githubusercontent.com/32979859/328072380-b7fba2a1-31b6-4363-8530-dc10eeb8aa76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5Njc0OTYsIm5iZiI6MTcxNDk2NzE5NiwicGF0aCI6Ii8zMjk3OTg1OS8zMjgwNzIzODAtYjdmYmEyYTEtMzFiNi00MzYzLTg1MzAtZGMxMGVlYjhhYTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAzNDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmODczMDA5ODgyYjA4NjE2MDRiMmY0OWE1YmQ0NjE2YmFlYmUzZWJkZmJmNzg0YzdjY2RmZDgwMDFjYmM5YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMJNBIwRo7kTacRJjKDxtRAuc80hveeevDd_6vKRqgE)

Don't edit the internal port, make it 3010:3000

**Comment by wwjCMP** [comment]
> > ![image](https://private-user-images.githubusercontent.com/32979859/328072380-b7fba2a1-31b6-4363-8530-dc10eeb8aa76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5Njc0OTYsIm5iZiI6MTcxNDk2NzE5NiwicGF0aCI6Ii8zMjk3OTg1OS8zMjgwNzIzODAtYjdmYmEyYTEtMzFiNi00MzYzLTg1MzAtZGMxMGVlYjhhYTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAzNDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmODczMDA5ODgyYjA4NjE2MDRiMmY0OWE1YmQ0NjE2YmFlYmUzZWJkZmJmNzg0YzdjY2RmZDgwMDFjYmM5YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMJNBIwRo7kTacRJjKDxtRAuc80hveeevDd_6vKRqgE)
> 
> Don't edit the internal port, make it 3010:3000

![image](https://github.com/ItzCrazyKns/Perplexica/assets/32979859/6b98bd87-b4a0-431f-8b26-502330b0995a)
![image](https://github.com/ItzCrazyKns/Perplexica/assets/32979859/3946dc97-5082-4bfe-a9c4-e9490b3279ef)


After the modification, I can load the chat model, but I cannot load the embedding model.

**Comment by ItzCrazyKns** [comment]
Open up the application tab (from the developer menu) and delete everything from the localStorage. The issue will be resolved
