### ISSUE TITLE
Do not show model

### ISSUE THREAD

**Issue by liujvnes** [ItzCrazyKns/Perplexica#75]
I installed ollama locally but did not use Docker to install Perplexica. The local model is not displayed. I am a computer novice. Please help me! what should I do?

![image](https://github.com/ItzCrazyKns/Perplexica/assets/25132014/0e57bfa4-33cb-4447-bbeb-5438376c745f)

**Comment by ItzCrazyKns** [comment]
What are the logs from the console and the backend container?

**Comment by liujvnes** [comment]
> 控制台和后端容器中的日志是什么？您能进行搜索吗？
I can search, but I don't know in which file

**Comment by ItzCrazyKns** [comment]
> > 控制台和后端容器中的日志是什么？您能进行搜索吗？
> > I can search, but I don't know in which file

If you're able to search then refresh your page and wait till the loading finishes, then try opening the settings

**Comment by liujvnes** [comment]
> > > 控制台和后端容器中的日志是什么？您能进行搜索吗？ 我可以搜索，但我不知道在哪个文件中
> 
> 如果您能够搜索，请刷新页面并等待加载完成，然后尝试打开设置。

Searching in Perplexica has been waiting, but I don't know how to change it to use it!
![image](https://github.com/ItzCrazyKns/Perplexica/assets/25132014/90010221-a3db-476b-9852-79006a6ac8d0)

**Comment by ItzCrazyKns** [comment]
> > > > 控制台和后端容器中的日志是什么？您能进行搜索吗？ 我可以搜索，但我不知道在哪个文件中
> > 
> > 
> > 如果您能够搜索，请刷新页面并等待加载完成，然后尝试打开设置。
> 
> Searching in Perplexica has been waiting, but I don't know how to change it to use it! ![image](https://private-user-images.githubusercontent.com/25132014/328124045-90010221-a3db-476b-9852-79006a6ac8d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODUzNzEsIm5iZiI6MTcxNDk4NTA3MSwicGF0aCI6Ii8yNTEzMjAxNC8zMjgxMjQwNDUtOTAwMTAyMjEtYTNkYi00NzZiLTk4NTItNzkwMDZhNmFjOGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA4NDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZTA2YmQ5YTQ3NTJhYTBiOWRjYmUwZTI3ODg3ZDBlMGQ0MDAxNDIyODFiYWM5MDIxNGE0YjJhN2IwZDNiNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Thw7nwL1AlNW0Fd3tJRS23w-SMvznPkj0SIiAb4hGNY)

Can you show the logs from the backend container of docker?

**Comment by liujvnes** [comment]
> > > > > 控制台和后端容器中的日志是什么？您能进行搜索吗？ 我可以搜索，但我不知道在哪个文件中
> > > 
> > > 
> > > 如果您能够搜索，请刷新页面并等待加载完成，然后尝试打开设置。
> > 
> > 
> > 在 Perplexica 中搜索一直在等待，但我不知道如何更改它以使用它！![image](https://private-user-images.githubusercontent.com/25132014/328124045-90010221-a3db-476b-9852-79006a6ac8d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODUzNzEsIm5iZiI6MTcxNDk4NTA3MSwicGF0aCI6Ii8yNTEzMjAxNC8zMjgxMjQwNDUtOTAwMTAyMjEtYTNkYi00NzZiLTk4NTItNzkwMDZhNmFjOGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA4NDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZTA2YmQ5YTQ3NTJhYTBiOWRjYmUwZTI3ODg3ZDBlMGQ0MDAxNDIyODFiYWM5MDIxNGE0YjJhN2IwZDNiNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Thw7nwL1AlNW0Fd3tJRS23w-SMvznPkj0SIiAb4hGNY)
> 
> 你能显示来自docker后端容器的日志吗？

I don't have docker installed

**Comment by ItzCrazyKns** [comment]
So show the logs from the terminal where you're running Perplexica from

**Comment by liujvnes** [comment]
[app.log](https://github.com/ItzCrazyKns/Perplexica/files/15218604/app.log)

Is it this file?

**Comment by ItzCrazyKns** [comment]
Can you try refreshing your page and sending something in english

**Comment by liujvnes** [comment]
> 你能尝试刷新你的页面并用英语发送一些东西吗？

Messages can be sent in English, but the result is pending

**Comment by ItzCrazyKns** [comment]
> > 你能尝试刷新你的页面并用英语发送一些东西吗？
> 
> Messages can be sent in English, but the result is pending

Can you open up the application tab in the developers menu and show what values are there

**Comment by liujvnes** [comment]
![image](https://github.com/ItzCrazyKns/Perplexica/assets/25132014/7c35588c-268b-4252-a21f-55ff7f7b46fe)
![image](https://github.com/ItzCrazyKns/Perplexica/assets/25132014/870b705f-8e61-4f22-b022-67e65982146e)

**Comment by ItzCrazyKns** [comment]
> ![image](https://private-user-images.githubusercontent.com/25132014/328130381-7c35588c-268b-4252-a21f-55ff7f7b46fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODcxNTEsIm5iZiI6MTcxNDk4Njg1MSwicGF0aCI6Ii8yNTEzMjAxNC8zMjgxMzAzODEtN2MzNTU4OGMtMjY4Yi00MjUyLWEyMWYtNTVmZjdmN2I0NmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA5MTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZWUwNmMxMDI1NGFiMThiMjNiMjczMzExYzM0OTU3Mzk3NjJjZGJhMjlmOWQ1MDA4MDhkZGZiM2U4ZjJmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhHamO7JMp1yQTl5rPJX4Cb8KE29JLQPrCOA5GyQXFQ) ![image](https://private-user-images.githubusercontent.com/25132014/328130654-870b705f-8e61-4f22-b022-67e65982146e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODcxNTEsIm5iZiI6MTcxNDk4Njg1MSwicGF0aCI6Ii8yNTEzMjAxNC8zMjgxMzA2NTQtODcwYjcwNWYtOGU2MS00ZjIyLWIwMjItNjdlNjU5ODIxNDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA5MTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NTZmZGQ3MDY1Y2JkZjYyMzg1OTg5ZThkYTA1OWI5ZWUwYWQ2ZTA0MzdhNjQwZjY1ZDVmNTEyYjIxNWU0MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4i4flr_yjHBCPLGG_W_w_jEv6z6Uds3m8DkHQdr57zo)

Have you pulled any models from Ollama? Show what are your values in the localStorage

**Comment by liujvnes** [comment]
Can you teach me where I can set the localStorage value? I don't know where to set it!

**Comment by ItzCrazyKns** [comment]
> Can you teach me where I can set the localStorage value? I don't know where to set it!

Hi, unfortunately I cannot spoon-feed you. You can google up how you can see the localStorage values and it would guide you better than me. Have you pulled any model from Ollama?

**Comment by liujvnes** [comment]
There are models in Ollama

**Comment by liujvnes** [comment]
![image](https://github.com/ItzCrazyKns/Perplexica/assets/25132014/24185345-30e0-4be6-b345-d6c3a7d67ee6)
![image](https://github.com/ItzCrazyKns/Perplexica/assets/25132014/966e02f1-a7c2-45b8-b4ed-877e9634d5d8)
![image](https://github.com/ItzCrazyKns/Perplexica/assets/25132014/ef798f2a-cb6c-4277-849d-603967f5da18)

**Comment by Donzhu2020** [comment]
I may have the same issue. 
![image](https://github.com/ItzCrazyKns/Perplexica/assets/79619870/0a2c618d-6268-47a7-8a62-3830d22774e9)
![image](https://github.com/ItzCrazyKns/Perplexica/assets/79619870/0dbb6ef0-49d1-4ba7-a974-05aa774d6613)

**Comment by ItzCrazyKns** [comment]
> I may have the same issue., not able to select chat model provider and embedding model provider ![image](https://private-user-images.githubusercontent.com/79619870/328195707-0a2c618d-6268-47a7-8a62-3830d22774e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDM1ODAsIm5iZiI6MTcxNTAwMzI4MCwicGF0aCI6Ii83OTYxOTg3MC8zMjgxOTU3MDctMGEyYzYxOGQtNjI2OC00N2E3LThhNjItMzgzMGQyMjc3NGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEzNDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MWUzNGVhMWM3NjNmZGIxOGZhMjQ4ZTNkNWJmYmVhNDdlNmM4MzQyMmRhZDgxMmUzNWMwOGM4MTgzYTdlZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d87LEMb3KCBO3QUFoz7kRhzP1IFJDLEOi7euKfIpJLE) ![image](https://private-user-images.githubusercontent.com/79619870/328195801-0dbb6ef0-49d1-4ba7-a974-05aa774d6613.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDM1ODAsIm5iZiI6MTcxNTAwMzI4MCwicGF0aCI6Ii83OTYxOTg3MC8zMjgxOTU4MDEtMGRiYjZlZjAtNDlkMS00YmE3LWE5NzQtMDVhYTc3NGQ2NjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEzNDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MzFmZGUwNjc3ZjBkZWE3MDEwOTRiZGUxOTI1YmM5OGUyMjU3NGQ0YzhhMzdkNTIzMDZjMGE0ZGExZjEwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XQTfahB664bjDBjPbMS9aLLxpGzekqMQNrp53gOXPGI)

Seems like a connection error if running it on Docker. Follow the steps listed here to get it fixed https://github.com/ItzCrazyKns/Perplexica?tab=readme-ov-file#ollama-connection-errors

**Comment by ItzCrazyKns** [comment]
@liujvnes can you join our Discord server: https://discord.gg/ckxqs7Je. We can communicate in a better way there and help you resolve your issues.

**Comment by ItzCrazyKns** [comment]
Hi @liujvnes, I released a new version of Perplexica that has a fix for it. You just need to re-clone Perplexica from Github and follow the installation instructions the issue will be resolved. If you face the error again feel free to re-open the issue
