### ISSUE TITLE
Make this Perplexica repo deployable on Vercel

### ISSUE THREAD

**Issue by arunkumarakvr** [ItzCrazyKns/Perplexica#8]
**Feature Request: Enable Deployment on Vercel**

**Is your feature request related to a problem? Please describe.**
Currently, the repository can't be deployed directly on Vercel, which limits its accessibility and ease of deployment for users who prefer using Vercel's platform. 

**Describe the solution you'd like**
I'd like to see support added to the repository so that it can be easily deployed on Vercel. This would involve updating the project's configuration files and dependencies to ensure compatibility with Vercel's deployment environment.

**Describe alternatives you've considered**
One alternative could be deploying the repository on other platforms that support the current configuration. However, adding support for Vercel would offer users more deployment options and flexibility.

**Additional context**
Providing the option to deploy on Vercel would enhance the accessibility and usability of Perplexica, attracting more users and contributors to the project. Additionally, it would align with the goal of making the project more widely available and user-friendly.

**Comment by ItzCrazyKns** [comment]
Hi, Vercel doesn't supports websockets and Perplexica uses websockets as its core functionality and hence, Perplexica cannot be fully deployed on Vercel.

**Comment by ItzCrazyKns** [comment]
Thank you, I've seen all of those, but that is a completely different story. The backend is separate from the frontend in Perplexica and needs to be deployed separately. Specifically, deploying a backend WebSocket server on Vercel is not possible as Vercel primarily supports stateless functions and static sites, which don't maintain persistent connections required by WebSockets.
