### ISSUE TITLE
Unable to access it within the local network

### ISSUE THREAD

**Issue by futurewin** [ItzCrazyKns/Perplexica#80]
**Describe the bug**
Unable to access it within the local network （192.168.*.*:8080)  ,
when opening the homepage, it's spinning.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ItzCrazyKns** [comment]
Update the IPs in the docker compose file and rebuild the images. We only provide support for the installation of Perplexica not to expose it to network
