### ISSUE TITLE
I don’t know why the search results often have nothing to do with the provided keywords? But if you search the same keyword directly through searxng, the result is correct.

### ISSUE THREAD

**Issue by edisonzf2020** [ItzCrazyKns/Perplexica#84]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by edisonzf2020** [comment]
Please allow me to try again. I am using the Groq model. What I want to describe is not that the final answer of the language model is of poor quality, but that I find that sometimes there is a problem with the quality of the source of information returned by the entered keywords? That is to say, the search information returned from the search engine has nothing to do with the entered keywords. I think this is unlikely to be caused by the model. Is there any problem in the process of passing it to the search engine? Because I give the keywords directly to searxng, the search engine that this project relies on, the search results returned are no problem.
PS: This situation usually occurs when using Chinese as the language for inputting keywords, but is not found when using English.

**Comment by ItzCrazyKns** [comment]
> Please allow me to try again. I am using the Groq model. What I want to describe is not that the final answer of the language model is of poor quality, but that I find that sometimes there is a problem with the quality of the source of information returned by the entered keywords? That is to say, the search information returned from the search engine has nothing to do with the entered keywords. I think this is unlikely to be caused by the model. Is there any problem in the process of passing it to the search engine? Because I give the keywords directly to searxng, the search engine that this project relies on, the search results returned are no problem. PS: This situation usually occurs when using Chinese as the language for inputting keywords, but is not found when using English.

I get it, Groq hosts open-source models and they are still little bad at multiple languages. We process the search using LLMs then a few algorithms to get the best result. Currently Chinese would be hard for the language models and hence the results are bad. I would recommend you to use English as we slowly reach the level of closed source models with open-source the quality of search results would also increase.
