### ISSUE TITLE
Allow users to run Perplexica queries from the address bar

### ISSUE THREAD

**Issue by rattlebones1** [ItzCrazyKns/Perplexica#98]
I'd like to propose a feature that allows users to run Perplexica queries directly from the browser's address bar. This would enable users to quickly search for information using Perplexica without having to navigate to the application or use the query interface.

![image](https://github.com/ItzCrazyKns/Perplexica/assets/90204806/d87da5d0-afff-4fda-8eb0-09406c59ac4f)

Normally you should be able to add this with a right click on the browser:

![image](https://github.com/ItzCrazyKns/Perplexica/assets/90204806/52b01cba-c3ff-4b33-9f95-525ae38e60f7)

And from what I understand you can't really add queries from url using Perplexica like this: https://duckduckgo.com/?q=yourquery

**Comment by ItzCrazyKns** [comment]
This is a nice idea!

**Comment by ItzCrazyKns** [comment]
Implemented: https://github.com/ItzCrazyKns/Perplexica/commit/3ef39c69a76eb67278aba6af2132e69da461cbe7
