### ISSUE TITLE
timestamp in logs

### ISSUE THREAD

**Issue by iandoug** [ItzCrazyKns/Perplexica#99]
**Is your feature request related to a problem? Please describe.**
Current logs have no time stamp.

**Describe the solution you'd like**
A time stamp.

**Describe alternatives you've considered**
not everyone has syslog-ng etc

**Additional context**
Apparently docker will do it if containers are launched with "--log-opt timestamp"

**Comment by ItzCrazyKns** [comment]
I don't think there are any needs for timestamps. The `app.log` file created has timestamps and we don't really need it for error logging or fixing bugs. If you wish to use it, you can definitely use it but that's not required for everyone.
